"""Capture the MLB hitting-spine oracle corpus (T6.2, Task 0.1).

Run (from repo root, network required):

    SDV_PY_LIVE_TESTS=1 PYTHONIOENCODING=utf-8 uv run python dev/mlb_hitting/capture_fixtures.py

Produces (committed to ``tests/fixtures/mlb_hitting/``):
  - statcast_sample_2024.parquet   ~3 weeks of 2024 Statcast pitches (batter
                                    view), real Savant columns, snake_case.
  - expected_stats_2024.parquet    Savant "expected stats" leaderboard, 2024.
  - swing_take_2024.parquet        Savant "swing/take" leaderboard, 2024.
  - home_runs_2024.parquet         Savant "home runs" (xHR) leaderboard, 2024.
  - park_factors_2024.parquet      Savant "park factors" leaderboard, 2024.
  - reference_grid_2024.parquet    coarse full-season EV x LA grid, built with
                                    the Phase-1 ``build_outcome_grid`` (this
                                    file is regenerated by
                                    ``build_reference_grid.py`` AFTER Task 1.1
                                    lands -- see the fixtures README for the
                                    two-step ordering note).

Wrapper functions used (confirmed present in sportsdataverse/mlb/):
  mlb_statcast_search (mlb_statcast_extra), mlb_statcast_leaderboard_expected_stats /
  _swing_take / _home_runs / _park_factors (mlb_statcast, codegen-generated).
"""

from __future__ import annotations

import sys
from pathlib import Path

import polars as pl

from sportsdataverse.mlb.mlb_statcast_extra import mlb_statcast_search
from sportsdataverse.mlb.mlb_statcast import (
    mlb_statcast_leaderboard_expected_stats,
    mlb_statcast_leaderboard_home_runs,
    mlb_statcast_leaderboard_park_factors,
    mlb_statcast_leaderboard_swing_take,
)

FIXTURES = Path(__file__).resolve().parents[2] / "tests" / "fixtures" / "mlb_hitting"

#: Trimmed column contract for the committed sample -- the full 119-column
#: Savant CSV is ~13MB for 3 weeks (over the repo's pre-commit large-file
#: gate); this subset is everything the four hitting models + oracle gates
#: actually read.
_SAMPLE_COLUMNS = [
    "game_pk",
    "game_date",
    "batter",
    "player_name",
    "events",
    "description",
    "type",
    "zone",
    "balls",
    "strikes",
    "launch_speed",
    "launch_angle",
    "hc_x",
    "hc_y",
    "bb_type",
    "stand",
    "home_team",
    "woba_value",
    "woba_denom",
    "delta_run_exp",
    "estimated_woba_using_speedangle",
    "estimated_ba_using_speedangle",
    "game_year",
]


def _pin_int64(df: pl.DataFrame, col: str) -> pl.DataFrame:
    if col in df.columns:
        return df.with_columns(pl.col(col).cast(pl.Int64))
    return df


def main() -> None:
    FIXTURES.mkdir(parents=True, exist_ok=True)

    print("Pulling 2024-06-01..2024-06-21 Statcast batter sample ...")
    sample = mlb_statcast_search("2024-06-01", "2024-06-21", player_type="batter")
    sample = _pin_int64(sample, "batter")
    sample = _pin_int64(sample, "game_pk")
    sample = sample.select([c for c in _SAMPLE_COLUMNS if c in sample.columns])
    print("statcast_sample_2024.shape =", sample.shape)
    assert sample.height > 20000, f"expected >20000 pitches, got {sample.height}"
    sample.write_parquet(FIXTURES / "statcast_sample_2024.parquet")

    print("Pulling expected_stats leaderboard 2024 ...")
    exp = mlb_statcast_leaderboard_expected_stats(year=2024)
    print("expected_stats_2024 columns =", exp.columns)
    print("expected_stats_2024.shape =", exp.shape)
    assert exp.height > 200, f"expected >200 players, got {exp.height}"
    exp.write_parquet(FIXTURES / "expected_stats_2024.parquet")

    print("Pulling swing_take leaderboard 2024 ...")
    st = mlb_statcast_leaderboard_swing_take(year=2024)
    print("swing_take_2024 columns =", st.columns)
    print("swing_take_2024.shape =", st.shape)
    st.write_parquet(FIXTURES / "swing_take_2024.parquet")

    print("Pulling home_runs leaderboard 2024 ...")
    hr = mlb_statcast_leaderboard_home_runs(year=2024)
    print("home_runs_2024 columns =", hr.columns)
    print("home_runs_2024.shape =", hr.shape)
    hr.write_parquet(FIXTURES / "home_runs_2024.parquet")

    print("Pulling park_factors leaderboard 2024 ...")
    pf = mlb_statcast_leaderboard_park_factors(year=2024)
    print("park_factors_2024 columns =", pf.columns)
    print("park_factors_2024.shape =", pf.shape)
    pf.write_parquet(FIXTURES / "park_factors_2024.parquet")

    print("Done. NOTE: reference_grid_2024.parquet is built separately by")
    print("build_reference_grid.py once mlb_expected_stats.build_outcome_grid exists.")


if __name__ == "__main__":
    sys.exit(main())
