# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

from __future__ import annotations

# -- Path setup --------------------------------------------------------------
# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, 'D:\\GitHub-Data\\sdv-dev\\sdv-py')


# -- Project information -----------------------------------------------------

project = "sdv-py"
copyright = "2022, Saiem Gilani"
author = "Saiem Gilani"


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.doctest",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
    "sphinx.ext.todo",
    "sphinx_markdown_builder",
]

# -- Napoleon (Google-style docstring) settings ------------------------------
napoleon_google_docstring = True
napoleon_numpy_docstring = False
napoleon_include_init_with_doc = False
napoleon_include_private_with_doc = False
napoleon_include_special_with_doc = True
napoleon_use_admonition_for_examples = False
napoleon_use_admonition_for_notes = False
napoleon_use_admonition_for_references = False
napoleon_use_ivar = False
napoleon_use_param = True
napoleon_use_rtype = True
napoleon_attr_annotations = True

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "sphinx-material"

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]


# -- Extension configuration -------------------------------------------------

# -- Options for todo extension ----------------------------------------------

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True
import os
import sys

sys.path.insert(0, os.path.abspath("../"))


def skip(app, what, name, obj, would_skip, options):
    if name in ("__init__",):
        return False
    return would_skip


def _patch_markdown_builder_for_abbreviation():
    """Teach sphinx_markdown_builder how to render docutils abbreviation nodes.

    Sphinx 9 emits ``abbreviation`` nodes for the keyword-only ``*`` separator
    in rendered function signatures (and a few other inline contexts).
    sphinx_markdown_builder 0.6.10 has no visitor for that node type, so each
    occurrence raises ``unknown node type`` warnings during the build. We
    register a no-op visitor that just emits the inner text — the markdown
    output is identical to what visit_Text would have produced.
    """
    try:
        from sphinx_markdown_builder.translator import MarkdownTranslator
    except ImportError:
        return

    if hasattr(MarkdownTranslator, "visit_abbreviation"):
        return

    def _visit_abbreviation(self, node):
        self.add(node.astext())
        raise __import__("docutils").nodes.SkipNode

    def _depart_abbreviation(self, node):
        pass

    MarkdownTranslator.visit_abbreviation = _visit_abbreviation
    MarkdownTranslator.depart_abbreviation = _depart_abbreviation


_patch_markdown_builder_for_abbreviation()


def setup(app):
    app.connect("autodoc-skip-member", skip)
