# GENERATED by tools/codegen/generate.py -- DO NOT EDIT.
# Source: tools/codegen/endpoints/releases.yaml
"""sportsdataverse.mlb dataset loaders (sportsdataverse-data releases). Generated."""

from __future__ import annotations

import polars as pl

from sportsdataverse._codegen_runtime import (
    SeasonNotFoundError,  # noqa: F401
    _as_season_list,
    _cast_ids_int64,  # noqa: F401  (used only by loaders declaring id_int64)
    _read_release_parquet,
    cli_warn,
)

__all__ = [
    "load_mlb_re24_matrix",
    "load_mlb_we_table",
    "load_mlb_wpa",
    "load_mlb_expected_stats",
    "load_mlb_expected_hr",
    "load_mlb_batter_projection",
    "load_mlb_oaa",
    "load_mlb_catcher_framing",
    "load_mlb_xera",
    "load_mlb_stuff_plus",
    "load_mlb_command_plus",
    "load_ncaa_baseball_pbp",
    "load_ncaa_baseball_schedule",
    "load_ncaa_baseball_teams",
    "load_ncaa_baseball_rosters",
    "load_ncaa_baseball_linescore",
    "load_ncaa_baseball_team_stats",
    "load_ncaa_baseball_player_stats",
    "load_ncaa_baseball_situational_stats",
    "load_ncaa_baseball_games",
]


def load_mlb_re24_matrix(seasons, return_as_pandas: bool = False):
    """Load mlb_game_state (sportsdataverse-data release).

    Source: https://github.com/sportsdataverse/sportsdataverse-data/releases/tag/mlb_game_state

    Args:
        seasons: an int or iterable of seasons (>= 2015).
        return_as_pandas: return a pandas DataFrame instead of polars.

    Returns:
        A polars (or pandas) DataFrame; seasons with no published asset are
        skipped with a warning rather than raising (404-safe).

        |col_name   |type    |
        |:----------|:-------|
        |base_state |String  |
        |outs       |Int64   |
        |re         |Float64 |
        |n          |UInt32  |
        |season     |Int64   |

    Raises:
        SeasonNotFoundError: if a requested season is below 2015.

    Example:
        Quick start::

            load_mlb_re24_matrix(seasons=2024)
    """
    frames, missing = [], []
    for season in _as_season_list(seasons):
        if int(season) < 2015:
            raise SeasonNotFoundError("season cannot be less than 2015")
        df = _read_release_parquet(
            f"https://github.com/sportsdataverse/sportsdataverse-data/releases/download/mlb_game_state/mlb_re24_matrix_{season}.parquet"
        )
        if df is None:
            missing.append(season)
            continue
        frames.append(df)
    if missing:
        cli_warn("load_mlb_re24_matrix: no data for season(s) {missing} (skipped)".format(missing=missing))
    # diagonal: per-season release schemas can drift (columns added/dropped
    # over the years) -- union columns, null-fill gaps.
    out = pl.concat(frames, how="diagonal_relaxed") if frames else pl.DataFrame()
    return out.to_pandas(use_pyarrow_extension_array=True) if return_as_pandas else out


def load_mlb_we_table(seasons, return_as_pandas: bool = False):
    """Load mlb_game_state (sportsdataverse-data release).

    Source: https://github.com/sportsdataverse/sportsdataverse-data/releases/tag/mlb_game_state

    Args:
        seasons: an int or iterable of seasons (>= 2015).
        return_as_pandas: return a pandas DataFrame instead of polars.

    Returns:
        A polars (or pandas) DataFrame; seasons with no published asset are
        skipped with a warning rather than raising (404-safe).

        |col_name          |type    |
        |:-----------------|:-------|
        |inning_capped     |Int64   |
        |half              |String  |
        |base_state        |String  |
        |outs_start        |Int64   |
        |score_diff_bucket |Int64   |
        |home_win_exp      |Float64 |
        |n                 |UInt32  |
        |thin              |Boolean |
        |season            |Int64   |

    Raises:
        SeasonNotFoundError: if a requested season is below 2015.

    Example:
        Quick start::

            load_mlb_we_table(seasons=2024)
    """
    frames, missing = [], []
    for season in _as_season_list(seasons):
        if int(season) < 2015:
            raise SeasonNotFoundError("season cannot be less than 2015")
        df = _read_release_parquet(
            f"https://github.com/sportsdataverse/sportsdataverse-data/releases/download/mlb_game_state/mlb_we_table_{season}.parquet"
        )
        if df is None:
            missing.append(season)
            continue
        frames.append(df)
    if missing:
        cli_warn("load_mlb_we_table: no data for season(s) {missing} (skipped)".format(missing=missing))
    # diagonal: per-season release schemas can drift (columns added/dropped
    # over the years) -- union columns, null-fill gaps.
    out = pl.concat(frames, how="diagonal_relaxed") if frames else pl.DataFrame()
    return out.to_pandas(use_pyarrow_extension_array=True) if return_as_pandas else out


def load_mlb_wpa(seasons, return_as_pandas: bool = False):
    """Load mlb_game_state (sportsdataverse-data release).

    Source: https://github.com/sportsdataverse/sportsdataverse-data/releases/tag/mlb_game_state

    Args:
        seasons: an int or iterable of seasons (>= 2015).
        return_as_pandas: return a pandas DataFrame instead of polars.

    Returns:
        A polars (or pandas) DataFrame; seasons with no published asset are
        skipped with a warning rather than raising (404-safe).

        |col_name     |type    |
        |:------------|:-------|
        |game_id      |String  |
        |at_bat_index |Int64   |
        |wpa          |Float64 |
        |season       |Int64   |

    Raises:
        SeasonNotFoundError: if a requested season is below 2015.

    Example:
        Quick start::

            load_mlb_wpa(seasons=2024)
    """
    frames, missing = [], []
    for season in _as_season_list(seasons):
        if int(season) < 2015:
            raise SeasonNotFoundError("season cannot be less than 2015")
        df = _read_release_parquet(
            f"https://github.com/sportsdataverse/sportsdataverse-data/releases/download/mlb_game_state/mlb_wpa_{season}.parquet"
        )
        if df is None:
            missing.append(season)
            continue
        frames.append(df)
    if missing:
        cli_warn("load_mlb_wpa: no data for season(s) {missing} (skipped)".format(missing=missing))
    # diagonal: per-season release schemas can drift (columns added/dropped
    # over the years) -- union columns, null-fill gaps.
    out = pl.concat(frames, how="diagonal_relaxed") if frames else pl.DataFrame()
    return out.to_pandas(use_pyarrow_extension_array=True) if return_as_pandas else out


def load_mlb_expected_stats(seasons, return_as_pandas: bool = False):
    """Load mlb_hitting_models (sportsdataverse-data release).

    Source: https://github.com/sportsdataverse/sportsdataverse-data/releases/tag/mlb_hitting_models

    Args:
        seasons: an int or iterable of seasons (>= 2015).
        return_as_pandas: return a pandas DataFrame instead of polars.

    Returns:
        A polars (or pandas) DataFrame; seasons with no published asset are
        skipped with a warning rather than raising (404-safe).

        |col_name |type    |
        |:--------|:-------|
        |batter   |Int64   |
        |season   |Int64   |
        |pa       |Int64   |
        |ab       |Int64   |
        |xwoba    |Float64 |
        |xba      |Float64 |
        |xslg     |Float64 |
        |woba     |Float64 |
        |ba       |Float64 |

    Raises:
        SeasonNotFoundError: if a requested season is below 2015.

    Example:
        Quick start::

            load_mlb_expected_stats(seasons=2024)
    """
    frames, missing = [], []
    for season in _as_season_list(seasons):
        if int(season) < 2015:
            raise SeasonNotFoundError("season cannot be less than 2015")
        df = _read_release_parquet(
            f"https://github.com/sportsdataverse/sportsdataverse-data/releases/download/mlb_hitting_models/mlb_expected_stats_{season}.parquet"
        )
        if df is None:
            missing.append(season)
            continue
        frames.append(df)
    if missing:
        cli_warn("load_mlb_expected_stats: no data for season(s) {missing} (skipped)".format(missing=missing))
    # diagonal: per-season release schemas can drift (columns added/dropped
    # over the years) -- union columns, null-fill gaps.
    out = pl.concat(frames, how="diagonal_relaxed") if frames else pl.DataFrame()
    return out.to_pandas(use_pyarrow_extension_array=True) if return_as_pandas else out


def load_mlb_expected_hr(seasons, return_as_pandas: bool = False):
    """Load mlb_hitting_models (sportsdataverse-data release).

    Source: https://github.com/sportsdataverse/sportsdataverse-data/releases/tag/mlb_hitting_models

    Args:
        seasons: an int or iterable of seasons (>= 2015).
        return_as_pandas: return a pandas DataFrame instead of polars.

    Returns:
        A polars (or pandas) DataFrame; seasons with no published asset are
        skipped with a warning rather than raising (404-safe).

        |col_name          |type    |
        |:-----------------|:-------|
        |batter            |Int64   |
        |season            |Int64   |
        |hr                |Int64   |
        |xhr_neutral       |Float64 |
        |xhr_park_adj      |Float64 |
        |hr_above_expected |Float64 |

    Raises:
        SeasonNotFoundError: if a requested season is below 2015.

    Example:
        Quick start::

            load_mlb_expected_hr(seasons=2024)
    """
    frames, missing = [], []
    for season in _as_season_list(seasons):
        if int(season) < 2015:
            raise SeasonNotFoundError("season cannot be less than 2015")
        df = _read_release_parquet(
            f"https://github.com/sportsdataverse/sportsdataverse-data/releases/download/mlb_hitting_models/mlb_expected_hr_{season}.parquet"
        )
        if df is None:
            missing.append(season)
            continue
        frames.append(df)
    if missing:
        cli_warn("load_mlb_expected_hr: no data for season(s) {missing} (skipped)".format(missing=missing))
    # diagonal: per-season release schemas can drift (columns added/dropped
    # over the years) -- union columns, null-fill gaps.
    out = pl.concat(frames, how="diagonal_relaxed") if frames else pl.DataFrame()
    return out.to_pandas(use_pyarrow_extension_array=True) if return_as_pandas else out


def load_mlb_batter_projection(seasons, return_as_pandas: bool = False):
    """Load mlb_hitting_models (sportsdataverse-data release).

    Source: https://github.com/sportsdataverse/sportsdataverse-data/releases/tag/mlb_hitting_models

    Args:
        seasons: an int or iterable of seasons (>= 2016).
        return_as_pandas: return a pandas DataFrame instead of polars.

    Returns:
        A polars (or pandas) DataFrame; seasons with no published asset are
        skipped with a warning rather than raising (404-safe).

        |col_name   |type    |
        |:----------|:-------|
        |batter     |Int64   |
        |age        |Int64   |
        |proj_xwoba |Float64 |
        |proj_pa    |Float64 |

    Raises:
        SeasonNotFoundError: if a requested season is below 2016.

    Example:
        Quick start::

            load_mlb_batter_projection(seasons=2024)
    """
    frames, missing = [], []
    for season in _as_season_list(seasons):
        if int(season) < 2016:
            raise SeasonNotFoundError("season cannot be less than 2016")
        df = _read_release_parquet(
            f"https://github.com/sportsdataverse/sportsdataverse-data/releases/download/mlb_hitting_models/mlb_batter_projection_{season}.parquet"
        )
        if df is None:
            missing.append(season)
            continue
        frames.append(df)
    if missing:
        cli_warn("load_mlb_batter_projection: no data for season(s) {missing} (skipped)".format(missing=missing))
    # diagonal: per-season release schemas can drift (columns added/dropped
    # over the years) -- union columns, null-fill gaps.
    out = pl.concat(frames, how="diagonal_relaxed") if frames else pl.DataFrame()
    return out.to_pandas(use_pyarrow_extension_array=True) if return_as_pandas else out


def load_mlb_oaa(seasons, return_as_pandas: bool = False):
    """Load mlb_fielding_models (sportsdataverse-data release).

    Source: https://github.com/sportsdataverse/sportsdataverse-data/releases/tag/mlb_fielding_models

    Args:
        seasons: an int or iterable of seasons (>= 2015).
        return_as_pandas: return a pandas DataFrame instead of polars.

    Returns:
        A polars (or pandas) DataFrame; seasons with no published asset are
        skipped with a warning rather than raising (404-safe).

        |col_name      |type    |
        |:-------------|:-------|
        |fielder_id    |String  |
        |position      |Int64   |
        |opportunities |UInt32  |
        |oaa           |Float64 |
        |season        |Int64   |

    Raises:
        SeasonNotFoundError: if a requested season is below 2015.

    Example:
        Quick start::

            load_mlb_oaa(seasons=2024)
    """
    frames, missing = [], []
    for season in _as_season_list(seasons):
        if int(season) < 2015:
            raise SeasonNotFoundError("season cannot be less than 2015")
        df = _read_release_parquet(
            f"https://github.com/sportsdataverse/sportsdataverse-data/releases/download/mlb_fielding_models/mlb_oaa_{season}.parquet"
        )
        if df is None:
            missing.append(season)
            continue
        frames.append(df)
    if missing:
        cli_warn("load_mlb_oaa: no data for season(s) {missing} (skipped)".format(missing=missing))
    # diagonal: per-season release schemas can drift (columns added/dropped
    # over the years) -- union columns, null-fill gaps.
    out = pl.concat(frames, how="diagonal_relaxed") if frames else pl.DataFrame()
    return out.to_pandas(use_pyarrow_extension_array=True) if return_as_pandas else out


def load_mlb_catcher_framing(seasons, return_as_pandas: bool = False):
    """Load mlb_fielding_models (sportsdataverse-data release).

    Source: https://github.com/sportsdataverse/sportsdataverse-data/releases/tag/mlb_fielding_models

    Args:
        seasons: an int or iterable of seasons (>= 2015).
        return_as_pandas: return a pandas DataFrame instead of polars.

    Returns:
        A polars (or pandas) DataFrame; seasons with no published asset are
        skipped with a warning rather than raising (404-safe).

        |col_name       |type    |
        |:--------------|:-------|
        |catcher_id     |String  |
        |takes          |UInt32  |
        |framing_runs   |Float64 |
        |strikes_gained |Float64 |
        |season         |Int64   |

    Raises:
        SeasonNotFoundError: if a requested season is below 2015.

    Example:
        Quick start::

            load_mlb_catcher_framing(seasons=2024)
    """
    frames, missing = [], []
    for season in _as_season_list(seasons):
        if int(season) < 2015:
            raise SeasonNotFoundError("season cannot be less than 2015")
        df = _read_release_parquet(
            f"https://github.com/sportsdataverse/sportsdataverse-data/releases/download/mlb_fielding_models/mlb_catcher_framing_{season}.parquet"
        )
        if df is None:
            missing.append(season)
            continue
        frames.append(df)
    if missing:
        cli_warn("load_mlb_catcher_framing: no data for season(s) {missing} (skipped)".format(missing=missing))
    # diagonal: per-season release schemas can drift (columns added/dropped
    # over the years) -- union columns, null-fill gaps.
    out = pl.concat(frames, how="diagonal_relaxed") if frames else pl.DataFrame()
    return out.to_pandas(use_pyarrow_extension_array=True) if return_as_pandas else out


def load_mlb_xera(seasons, return_as_pandas: bool = False):
    """Load mlb_pitching_models (sportsdataverse-data release).

    Source: https://github.com/sportsdataverse/sportsdataverse-data/releases/tag/mlb_pitching_models

    Args:
        seasons: an int or iterable of seasons (>= 2015).
        return_as_pandas: return a pandas DataFrame instead of polars.

    Returns:
        A polars (or pandas) DataFrame; seasons with no published asset are
        skipped with a warning rather than raising (404-safe).

        |col_name |type    |
        |:--------|:-------|
        |pitcher  |Int64   |
        |season   |Int64   |
        |x_woba   |Float64 |
        |x_era    |Float64 |

    Raises:
        SeasonNotFoundError: if a requested season is below 2015.

    Example:
        Quick start::

            load_mlb_xera(seasons=2024)
    """
    frames, missing = [], []
    for season in _as_season_list(seasons):
        if int(season) < 2015:
            raise SeasonNotFoundError("season cannot be less than 2015")
        df = _read_release_parquet(
            f"https://github.com/sportsdataverse/sportsdataverse-data/releases/download/mlb_pitching_models/mlb_xera_{season}.parquet"
        )
        if df is None:
            missing.append(season)
            continue
        frames.append(df)
    if missing:
        cli_warn("load_mlb_xera: no data for season(s) {missing} (skipped)".format(missing=missing))
    # diagonal: per-season release schemas can drift (columns added/dropped
    # over the years) -- union columns, null-fill gaps.
    out = pl.concat(frames, how="diagonal_relaxed") if frames else pl.DataFrame()
    return out.to_pandas(use_pyarrow_extension_array=True) if return_as_pandas else out


def load_mlb_stuff_plus(seasons, return_as_pandas: bool = False):
    """Load mlb_pitching_models (sportsdataverse-data release).

    Source: https://github.com/sportsdataverse/sportsdataverse-data/releases/tag/mlb_pitching_models

    Args:
        seasons: an int or iterable of seasons (>= 2015).
        return_as_pandas: return a pandas DataFrame instead of polars.

    Returns:
        A polars (or pandas) DataFrame; seasons with no published asset are
        skipped with a warning rather than raising (404-safe).

        |col_name     |type    |
        |:------------|:-------|
        |pitcher      |Int64   |
        |pitch_type   |String  |
        |stuff_rv_hat |Float64 |
        |stuff_plus   |Float64 |
        |season       |Int64   |

    Raises:
        SeasonNotFoundError: if a requested season is below 2015.

    Example:
        Quick start::

            load_mlb_stuff_plus(seasons=2024)
    """
    frames, missing = [], []
    for season in _as_season_list(seasons):
        if int(season) < 2015:
            raise SeasonNotFoundError("season cannot be less than 2015")
        df = _read_release_parquet(
            f"https://github.com/sportsdataverse/sportsdataverse-data/releases/download/mlb_pitching_models/mlb_stuff_plus_{season}.parquet"
        )
        if df is None:
            missing.append(season)
            continue
        frames.append(df)
    if missing:
        cli_warn("load_mlb_stuff_plus: no data for season(s) {missing} (skipped)".format(missing=missing))
    # diagonal: per-season release schemas can drift (columns added/dropped
    # over the years) -- union columns, null-fill gaps.
    out = pl.concat(frames, how="diagonal_relaxed") if frames else pl.DataFrame()
    return out.to_pandas(use_pyarrow_extension_array=True) if return_as_pandas else out


def load_mlb_command_plus(seasons, return_as_pandas: bool = False):
    """Load mlb_pitching_models (sportsdataverse-data release).

    Source: https://github.com/sportsdataverse/sportsdataverse-data/releases/tag/mlb_pitching_models

    Args:
        seasons: an int or iterable of seasons (>= 2015).
        return_as_pandas: return a pandas DataFrame instead of polars.

    Returns:
        A polars (or pandas) DataFrame; seasons with no published asset are
        skipped with a warning rather than raising (404-safe).

        |col_name        |type    |
        |:---------------|:-------|
        |pitcher         |Int64   |
        |location_rv_hat |Float64 |
        |command_plus    |Float64 |
        |season          |Int64   |

    Raises:
        SeasonNotFoundError: if a requested season is below 2015.

    Example:
        Quick start::

            load_mlb_command_plus(seasons=2024)
    """
    frames, missing = [], []
    for season in _as_season_list(seasons):
        if int(season) < 2015:
            raise SeasonNotFoundError("season cannot be less than 2015")
        df = _read_release_parquet(
            f"https://github.com/sportsdataverse/sportsdataverse-data/releases/download/mlb_pitching_models/mlb_command_plus_{season}.parquet"
        )
        if df is None:
            missing.append(season)
            continue
        frames.append(df)
    if missing:
        cli_warn("load_mlb_command_plus: no data for season(s) {missing} (skipped)".format(missing=missing))
    # diagonal: per-season release schemas can drift (columns added/dropped
    # over the years) -- union columns, null-fill gaps.
    out = pl.concat(frames, how="diagonal_relaxed") if frames else pl.DataFrame()
    return out.to_pandas(use_pyarrow_extension_array=True) if return_as_pandas else out


def load_ncaa_baseball_pbp(seasons, return_as_pandas: bool = False):
    """Load ncaa_baseball_pbp (sportsdataverse-data release).

    Source: https://github.com/sportsdataverse/sportsdataverse-data/releases/tag/ncaa_baseball_pbp

    Args:
        seasons: an int or iterable of seasons (>= 2017).
        return_as_pandas: return a pandas DataFrame instead of polars.

    Returns:
        A polars (or pandas) DataFrame; seasons with no published asset are
        skipped with a warning rather than raising (404-safe).

        |col_name         |type         |
        |:----------------|:------------|
        |contest_id       |String       |
        |inning           |Int64        |
        |inning_top_bot   |String       |
        |batting          |String       |
        |fielding         |String       |
        |play_number      |Int64        |
        |score_away       |Int64        |
        |score_home       |Int64        |
        |batter           |String       |
        |play_type        |String       |
        |hit_trajectory   |String       |
        |fielded_position |String       |
        |is_hit           |Boolean      |
        |is_out           |Boolean      |
        |strikeout_type   |String       |
        |is_sacrifice     |Boolean      |
        |sac_type         |String       |
        |is_double_play   |Boolean      |
        |rbi              |Int64        |
        |count_balls      |Int64        |
        |count_strikes    |Int64        |
        |pitch_sequence   |String       |
        |error_position   |String       |
        |unearned         |Boolean      |
        |runs_scored      |Int64        |
        |scoring_runners  |List(String) |
        |runners_advanced |List(String) |
        |outs_on_play     |Int64        |
        |is_scoring_play  |Boolean      |
        |description      |String       |
        |source           |String       |
        |espn_game_id     |String       |
        |game_key         |String       |
        |game_date        |String       |
        |location         |String       |
        |attendance       |Int64        |
        |season           |Int64        |

    Raises:
        SeasonNotFoundError: if a requested season is below 2017.

    Example:
        Quick start::

            load_ncaa_baseball_pbp(seasons=2023)
    """
    frames, missing = [], []
    for season in _as_season_list(seasons):
        if int(season) < 2017:
            raise SeasonNotFoundError("season cannot be less than 2017")
        df = _read_release_parquet(
            f"https://github.com/sportsdataverse/sportsdataverse-data/releases/download/ncaa_baseball_pbp/ncaa_baseball_pbp_{season}.parquet"
        )
        if df is None:
            missing.append(season)
            continue
        frames.append(df)
    if missing:
        cli_warn("load_ncaa_baseball_pbp: no data for season(s) {missing} (skipped)".format(missing=missing))
    # diagonal: per-season release schemas can drift (columns added/dropped
    # over the years) -- union columns, null-fill gaps.
    out = pl.concat(frames, how="diagonal_relaxed") if frames else pl.DataFrame()
    return out.to_pandas(use_pyarrow_extension_array=True) if return_as_pandas else out


def load_ncaa_baseball_schedule(seasons, return_as_pandas: bool = False):
    """Load ncaa_baseball_schedules (sportsdataverse-data release).

    Source: https://github.com/sportsdataverse/sportsdataverse-data/releases/tag/ncaa_baseball_schedules

    Args:
        seasons: an int or iterable of seasons (>= 2012).
        return_as_pandas: return a pandas DataFrame instead of polars.

    Returns:
        A polars (or pandas) DataFrame; seasons with no published asset are
        skipped with a warning rather than raising (404-safe).

        |col_name       |type   |
        |:--------------|:------|
        |team_id        |String |
        |team_name      |String |
        |date           |String |
        |game_number    |Int64  |
        |opponent_id    |String |
        |opponent       |String |
        |result         |String |
        |outcome        |String |
        |team_score     |Int64  |
        |opponent_score |Int64  |
        |contest_id     |String |
        |attendance     |Int64  |
        |division       |Int64  |
        |season         |Int64  |

    Raises:
        SeasonNotFoundError: if a requested season is below 2012.

    Example:
        Quick start::

            load_ncaa_baseball_schedule(seasons=2023)
    """
    frames, missing = [], []
    for season in _as_season_list(seasons):
        if int(season) < 2012:
            raise SeasonNotFoundError("season cannot be less than 2012")
        df = _read_release_parquet(
            f"https://github.com/sportsdataverse/sportsdataverse-data/releases/download/ncaa_baseball_schedules/ncaa_baseball_schedule_{season}.parquet"
        )
        if df is None:
            missing.append(season)
            continue
        frames.append(df)
    if missing:
        cli_warn("load_ncaa_baseball_schedule: no data for season(s) {missing} (skipped)".format(missing=missing))
    # diagonal: per-season release schemas can drift (columns added/dropped
    # over the years) -- union columns, null-fill gaps.
    out = pl.concat(frames, how="diagonal_relaxed") if frames else pl.DataFrame()
    return out.to_pandas(use_pyarrow_extension_array=True) if return_as_pandas else out


def load_ncaa_baseball_teams(seasons, return_as_pandas: bool = False):
    """Load ncaa_baseball_teams (sportsdataverse-data release).

    Source: https://github.com/sportsdataverse/sportsdataverse-data/releases/tag/ncaa_baseball_teams

    Args:
        seasons: an int or iterable of seasons (>= 2024).
        return_as_pandas: return a pandas DataFrame instead of polars.

    Returns:
        A polars (or pandas) DataFrame; seasons with no published asset are
        skipped with a warning rather than raising (404-safe).

        |col_name  |type   |
        |:---------|:------|
        |team_id   |String |
        |team_name |String |
        |division  |Int64  |
        |season    |Int64  |

    Raises:
        SeasonNotFoundError: if a requested season is below 2024.

    Example:
        Quick start::

            load_ncaa_baseball_teams(seasons=2025)
    """
    frames, missing = [], []
    for season in _as_season_list(seasons):
        if int(season) < 2024:
            raise SeasonNotFoundError("season cannot be less than 2024")
        df = _read_release_parquet(
            f"https://github.com/sportsdataverse/sportsdataverse-data/releases/download/ncaa_baseball_teams/ncaa_baseball_teams_{season}.parquet"
        )
        if df is None:
            missing.append(season)
            continue
        frames.append(df)
    if missing:
        cli_warn("load_ncaa_baseball_teams: no data for season(s) {missing} (skipped)".format(missing=missing))
    # diagonal: per-season release schemas can drift (columns added/dropped
    # over the years) -- union columns, null-fill gaps.
    out = pl.concat(frames, how="diagonal_relaxed") if frames else pl.DataFrame()
    return out.to_pandas(use_pyarrow_extension_array=True) if return_as_pandas else out


def load_ncaa_baseball_rosters(seasons, return_as_pandas: bool = False):
    """Load ncaa_baseball_rosters (sportsdataverse-data release).

    Source: https://github.com/sportsdataverse/sportsdataverse-data/releases/tag/ncaa_baseball_rosters

    Args:
        seasons: an int or iterable of seasons (>= 2024).
        return_as_pandas: return a pandas DataFrame instead of polars.

    Returns:
        A polars (or pandas) DataFrame; seasons with no published asset are
        skipped with a warning rather than raising (404-safe).

        |col_name        |type   |
        |:---------------|:------|
        |team_id         |String |
        |team_name       |String |
        |player_id       |String |
        |player_name     |String |
        |jersey          |String |
        |statcrew_jersey |String |
        |player_class    |String |
        |position        |String |
        |height          |String |
        |weight          |Int64  |
        |hometown        |String |
        |high_school     |String |
        |games_played    |Int64  |
        |games_started   |Int64  |
        |season          |Int64  |

    Raises:
        SeasonNotFoundError: if a requested season is below 2024.

    Example:
        Quick start::

            load_ncaa_baseball_rosters(seasons=2025)
    """
    frames, missing = [], []
    for season in _as_season_list(seasons):
        if int(season) < 2024:
            raise SeasonNotFoundError("season cannot be less than 2024")
        df = _read_release_parquet(
            f"https://github.com/sportsdataverse/sportsdataverse-data/releases/download/ncaa_baseball_rosters/ncaa_baseball_rosters_{season}.parquet"
        )
        if df is None:
            missing.append(season)
            continue
        frames.append(df)
    if missing:
        cli_warn("load_ncaa_baseball_rosters: no data for season(s) {missing} (skipped)".format(missing=missing))
    # diagonal: per-season release schemas can drift (columns added/dropped
    # over the years) -- union columns, null-fill gaps.
    out = pl.concat(frames, how="diagonal_relaxed") if frames else pl.DataFrame()
    return out.to_pandas(use_pyarrow_extension_array=True) if return_as_pandas else out


def load_ncaa_baseball_linescore(seasons, return_as_pandas: bool = False):
    """Load ncaa_baseball_linescore (sportsdataverse-data release).

    Source: https://github.com/sportsdataverse/sportsdataverse-data/releases/tag/ncaa_baseball_linescore

    Args:
        seasons: an int or iterable of seasons (>= 2024).
        return_as_pandas: return a pandas DataFrame instead of polars.

    Returns:
        A polars (or pandas) DataFrame; seasons with no published asset are
        skipped with a warning rather than raising (404-safe).

        |col_name     |type   |
        |:------------|:------|
        |contest_id   |String |
        |team         |String |
        |home_away    |String |
        |inning       |String |
        |runs         |Int64  |
        |runs_total   |Int64  |
        |hits         |Int64  |
        |errors       |Int64  |
        |game_date    |String |
        |venue        |String |
        |attendance   |Int64  |
        |source       |String |
        |espn_game_id |String |
        |game_key     |String |
        |location     |String |
        |season       |Int64  |

    Raises:
        SeasonNotFoundError: if a requested season is below 2024.

    Example:
        Quick start::

            load_ncaa_baseball_linescore(seasons=2025)
    """
    frames, missing = [], []
    for season in _as_season_list(seasons):
        if int(season) < 2024:
            raise SeasonNotFoundError("season cannot be less than 2024")
        df = _read_release_parquet(
            f"https://github.com/sportsdataverse/sportsdataverse-data/releases/download/ncaa_baseball_linescore/ncaa_baseball_linescore_{season}.parquet"
        )
        if df is None:
            missing.append(season)
            continue
        frames.append(df)
    if missing:
        cli_warn("load_ncaa_baseball_linescore: no data for season(s) {missing} (skipped)".format(missing=missing))
    # diagonal: per-season release schemas can drift (columns added/dropped
    # over the years) -- union columns, null-fill gaps.
    out = pl.concat(frames, how="diagonal_relaxed") if frames else pl.DataFrame()
    return out.to_pandas(use_pyarrow_extension_array=True) if return_as_pandas else out


def load_ncaa_baseball_team_stats(seasons, return_as_pandas: bool = False):
    """Load ncaa_baseball_team_stats (sportsdataverse-data release).

    Source: https://github.com/sportsdataverse/sportsdataverse-data/releases/tag/ncaa_baseball_team_stats

    Args:
        seasons: an int or iterable of seasons (>= 2024).
        return_as_pandas: return a pandas DataFrame instead of polars.

    Returns:
        A polars (or pandas) DataFrame; seasons with no published asset are
        skipped with a warning rather than raising (404-safe).

        |col_name     |type   |
        |:------------|:------|
        |contest_id   |String |
        |category     |String |
        |stat         |String |
        |period       |String |
        |away_team    |String |
        |away_value   |String |
        |home_team    |String |
        |home_value   |String |
        |source       |String |
        |espn_game_id |String |
        |game_key     |String |
        |game_date    |String |
        |location     |String |
        |attendance   |Int64  |
        |season       |Int64  |

    Raises:
        SeasonNotFoundError: if a requested season is below 2024.

    Example:
        Quick start::

            load_ncaa_baseball_team_stats(seasons=2025)
    """
    frames, missing = [], []
    for season in _as_season_list(seasons):
        if int(season) < 2024:
            raise SeasonNotFoundError("season cannot be less than 2024")
        df = _read_release_parquet(
            f"https://github.com/sportsdataverse/sportsdataverse-data/releases/download/ncaa_baseball_team_stats/ncaa_baseball_team_stats_{season}.parquet"
        )
        if df is None:
            missing.append(season)
            continue
        frames.append(df)
    if missing:
        cli_warn("load_ncaa_baseball_team_stats: no data for season(s) {missing} (skipped)".format(missing=missing))
    # diagonal: per-season release schemas can drift (columns added/dropped
    # over the years) -- union columns, null-fill gaps.
    out = pl.concat(frames, how="diagonal_relaxed") if frames else pl.DataFrame()
    return out.to_pandas(use_pyarrow_extension_array=True) if return_as_pandas else out


def load_ncaa_baseball_player_stats(seasons, return_as_pandas: bool = False):
    """Load ncaa_baseball_player_stats (sportsdataverse-data release).

    Source: https://github.com/sportsdataverse/sportsdataverse-data/releases/tag/ncaa_baseball_player_stats

    Args:
        seasons: an int or iterable of seasons (>= 2024).
        return_as_pandas: return a pandas DataFrame instead of polars.

    Returns:
        A polars (or pandas) DataFrame; seasons with no published asset are
        skipped with a warning rather than raising (404-safe).

        |col_name      |type   |
        |:-------------|:------|
        |contest_id    |String |
        |team_id       |String |
        |number        |String |
        |name          |String |
        |position      |String |
        |r             |String |
        |ab            |String |
        |h             |String |
        |2b            |String |
        |3b            |String |
        |tb            |String |
        |hr            |String |
        |rbi           |String |
        |bb            |String |
        |hbp           |String |
        |sf            |String |
        |sh            |String |
        |k             |String |
        |opp_dp        |String |
        |cs            |String |
        |picked        |String |
        |sb            |String |
        |ibb           |String |
        |kl            |String |
        |category      |String |
        |source        |String |
        |espn_game_id  |String |
        |game_key      |String |
        |game_date     |String |
        |location      |String |
        |attendance    |Int64  |
        |ip            |String |
        |er            |String |
        |so            |String |
        |bf            |String |
        |2b_a          |String |
        |3b_a          |String |
        |bk            |String |
        |hr_a          |String |
        |wp            |String |
        |hb            |String |
        |inh_run       |String |
        |inh_run_score |String |
        |sha           |String |
        |sfa           |String |
        |tuer          |String |
        |pickoffs      |String |
        |po            |String |
        |a             |String |
        |tc            |String |
        |e             |String |
        |ci            |String |
        |pb            |String |
        |sba           |String |
        |csb           |String |
        |idp           |String |
        |tp            |String |
        |sbapct        |String |
        |season        |Int64  |

    Raises:
        SeasonNotFoundError: if a requested season is below 2024.

    Example:
        Quick start::

            load_ncaa_baseball_player_stats(seasons=2025)
    """
    frames, missing = [], []
    for season in _as_season_list(seasons):
        if int(season) < 2024:
            raise SeasonNotFoundError("season cannot be less than 2024")
        df = _read_release_parquet(
            f"https://github.com/sportsdataverse/sportsdataverse-data/releases/download/ncaa_baseball_player_stats/ncaa_baseball_player_stats_{season}.parquet"
        )
        if df is None:
            missing.append(season)
            continue
        frames.append(df)
    if missing:
        cli_warn("load_ncaa_baseball_player_stats: no data for season(s) {missing} (skipped)".format(missing=missing))
    # diagonal: per-season release schemas can drift (columns added/dropped
    # over the years) -- union columns, null-fill gaps.
    out = pl.concat(frames, how="diagonal_relaxed") if frames else pl.DataFrame()
    return out.to_pandas(use_pyarrow_extension_array=True) if return_as_pandas else out


def load_ncaa_baseball_situational_stats(seasons, return_as_pandas: bool = False):
    """Load ncaa_baseball_situational_stats (sportsdataverse-data release).

    Source: https://github.com/sportsdataverse/sportsdataverse-data/releases/tag/ncaa_baseball_situational_stats

    Args:
        seasons: an int or iterable of seasons (>= 2024).
        return_as_pandas: return a pandas DataFrame instead of polars.

    Returns:
        A polars (or pandas) DataFrame; seasons with no published asset are
        skipped with a warning rather than raising (404-safe).

        |col_name       |type   |
        |:--------------|:------|
        |contest_id     |String |
        |team_seq       |Int64  |
        |player         |String |
        |position       |String |
        |with_runrs     |String |
        |hits_scorepos  |String |
        |vs_lhp         |String |
        |vs_rhp         |String |
        |leadoff_pct    |String |
        |rbi3rd         |String |
        |h_pinchit      |String |
        |adv_ops        |String |
        |with_2_outs    |String |
        |with_runrs2    |String |
        |with_scorepos2 |String |
        |bases_empty    |String |
        |bases_loaded   |String |
        |category       |String |
        |source         |String |
        |espn_game_id   |String |
        |game_key       |String |
        |game_date      |String |
        |location       |String |
        |attendance     |Int64  |
        |runners        |String |
        |vs_lhb         |String |
        |with_2outs     |String |
        |emtpy          |String |
        |with_scorepos  |String |
        |with_runners2  |String |
        |vs_rhb         |String |
        |field_pct      |String |
        |season         |Int64  |

    Raises:
        SeasonNotFoundError: if a requested season is below 2024.

    Example:
        Quick start::

            load_ncaa_baseball_situational_stats(seasons=2025)
    """
    frames, missing = [], []
    for season in _as_season_list(seasons):
        if int(season) < 2024:
            raise SeasonNotFoundError("season cannot be less than 2024")
        df = _read_release_parquet(
            f"https://github.com/sportsdataverse/sportsdataverse-data/releases/download/ncaa_baseball_situational_stats/ncaa_baseball_situational_stats_{season}.parquet"
        )
        if df is None:
            missing.append(season)
            continue
        frames.append(df)
    if missing:
        cli_warn(
            "load_ncaa_baseball_situational_stats: no data for season(s) {missing} (skipped)".format(missing=missing)
        )
    # diagonal: per-season release schemas can drift (columns added/dropped
    # over the years) -- union columns, null-fill gaps.
    out = pl.concat(frames, how="diagonal_relaxed") if frames else pl.DataFrame()
    return out.to_pandas(use_pyarrow_extension_array=True) if return_as_pandas else out


def load_ncaa_baseball_games(seasons, return_as_pandas: bool = False):
    """Load ncaa_baseball_games (sportsdataverse-data release).

    Source: https://github.com/sportsdataverse/sportsdataverse-data/releases/tag/ncaa_baseball_games

    Args:
        seasons: an int or iterable of seasons (>= 2017).
        return_as_pandas: return a pandas DataFrame instead of polars.

    Returns:
        A polars (or pandas) DataFrame; seasons with no published asset are
        skipped with a warning rather than raising (404-safe).

        |col_name     |type   |
        |:------------|:------|
        |game_key     |String |
        |contest_id   |String |
        |game_pbp_id  |Int64  |
        |season       |Int64  |
        |source       |String |
        |espn_game_id |String |
        |away_team    |String |
        |away_final   |Int64  |
        |home_team    |String |
        |home_final   |Int64  |

    Raises:
        SeasonNotFoundError: if a requested season is below 2017.

    Example:
        Quick start::

            load_ncaa_baseball_games(seasons=2024)
    """
    frames, missing = [], []
    for season in _as_season_list(seasons):
        if int(season) < 2017:
            raise SeasonNotFoundError("season cannot be less than 2017")
        df = _read_release_parquet(
            f"https://github.com/sportsdataverse/sportsdataverse-data/releases/download/ncaa_baseball_games/ncaa_baseball_games_{season}.parquet"
        )
        if df is None:
            missing.append(season)
            continue
        frames.append(df)
    if missing:
        cli_warn("load_ncaa_baseball_games: no data for season(s) {missing} (skipped)".format(missing=missing))
    # diagonal: per-season release schemas can drift (columns added/dropped
    # over the years) -- union columns, null-fill gaps.
    out = pl.concat(frames, how="diagonal_relaxed") if frames else pl.DataFrame()
    return out.to_pandas(use_pyarrow_extension_array=True) if return_as_pandas else out
