# GENERATED by tools/codegen/generate.py -- DO NOT EDIT.
# Source: tools/codegen/endpoints/mlb_statcast.yaml
"""mlb_statcast wrappers (host https://baseballsavant.mlb.com). Generated."""

from __future__ import annotations

from typing import TYPE_CHECKING, Dict, List, Optional, Union  # noqa: F401

from sportsdataverse._codegen_runtime import _get
from sportsdataverse.mlb.mlb_statcast_parsers import parse_mlb_statcast_gamefeed, parse_mlb_statcast_leaderboard

if TYPE_CHECKING:  # pragma: no cover -- annotation-only imports (PEP 563 defers eval)
    import pandas as pd
    import polars as pl

__all__ = [
    "mlb_statcast_leaderboard_expected_stats",
    "mlb_statcast_gamefeed",
    "mlb_statcast_player_percentile_rankings",
]


def mlb_statcast_leaderboard_expected_stats(
    type: Optional[str] = None,
    year: Optional[Union[int, str]] = None,
    csv: Optional[bool] = "true",
    *,
    return_parsed: bool = True,
    return_as_pandas: bool = False,
    **kwargs,
) -> Union[pl.DataFrame, pd.DataFrame, Dict]:
    """GET /leaderboard/expected_statistics — xBA/xSLG/xwOBA leaderboard (csv=true).

    Endpoint: ``GET https://baseballsavant.mlb.com/leaderboard/expected_statistics``
    Example URL: https://baseballsavant.mlb.com/leaderboard/expected_statistics

    Args:
        type: type query parameter.
        year: year query parameter.
        csv: csv query parameter.
        return_parsed: parse the payload through parse_mlb_statcast_leaderboard -> polars DataFrame (default True). Pass return_parsed=False for the raw JSON Dict.
        return_as_pandas: with return_parsed, return a pandas DataFrame instead of polars.

    Returns:
        A polars/pandas DataFrame by default; the raw JSON ``Dict`` when ``return_parsed=False``.

    Example:
        >>> mlb_statcast_leaderboard_expected_stats()
    """
    raw = _get(
        "https://baseballsavant.mlb.com/leaderboard/expected_statistics",
        params={
            "type": type,
            "year": year,
            "csv": csv,
            **{_k: _v for _k, _v in kwargs.items() if _v is not None},
        },
    )
    if return_parsed:
        return parse_mlb_statcast_leaderboard(raw, return_as_pandas=return_as_pandas)
    return raw


def mlb_statcast_gamefeed(
    game_pk: Optional[int] = None,
    *,
    return_parsed: bool = True,
    return_as_pandas: bool = False,
    **kwargs,
) -> Union[pl.DataFrame, pd.DataFrame, Dict]:
    """GET /gf — Savant per-game JSON feed.

    Endpoint: ``GET https://baseballsavant.mlb.com/gf``
    Example URL: https://baseballsavant.mlb.com/gf

    Args:
        game_pk: game_pk query parameter.
        return_parsed: parse the payload through parse_mlb_statcast_gamefeed -> polars DataFrame (default True). Pass return_parsed=False for the raw JSON Dict.
        return_as_pandas: with return_parsed, return a pandas DataFrame instead of polars.

    Returns:
        A polars/pandas DataFrame by default; the raw JSON ``Dict`` when ``return_parsed=False``.

    Example:
        >>> mlb_statcast_gamefeed()
    """
    raw = _get(
        "https://baseballsavant.mlb.com/gf",
        params={
            "game_pk": game_pk,
            **{_k: _v for _k, _v in kwargs.items() if _v is not None},
        },
    )
    if return_parsed:
        return parse_mlb_statcast_gamefeed(raw, return_as_pandas=return_as_pandas)
    return raw


def mlb_statcast_player_percentile_rankings(
    type: Optional[str] = None,
    year: Optional[Union[int, str]] = None,
    csv: Optional[bool] = "true",
    *,
    return_parsed: bool = True,
    return_as_pandas: bool = False,
    **kwargs,
) -> Union[pl.DataFrame, pd.DataFrame, Dict]:
    """GET /leaderboard/percentile-rankings — player percentile sliders (csv=true).

    Endpoint: ``GET https://baseballsavant.mlb.com/leaderboard/percentile-rankings``
    Example URL: https://baseballsavant.mlb.com/leaderboard/percentile-rankings

    Args:
        type: type query parameter.
        year: year query parameter.
        csv: csv query parameter.
        return_parsed: parse the payload through parse_mlb_statcast_leaderboard -> polars DataFrame (default True). Pass return_parsed=False for the raw JSON Dict.
        return_as_pandas: with return_parsed, return a pandas DataFrame instead of polars.

    Returns:
        A polars/pandas DataFrame by default; the raw JSON ``Dict`` when ``return_parsed=False``.

    Example:
        >>> mlb_statcast_player_percentile_rankings()
    """
    raw = _get(
        "https://baseballsavant.mlb.com/leaderboard/percentile-rankings",
        params={
            "type": type,
            "year": year,
            "csv": csv,
            **{_k: _v for _k, _v in kwargs.items() if _v is not None},
        },
    )
    if return_parsed:
        return parse_mlb_statcast_leaderboard(raw, return_as_pandas=return_as_pandas)
    return raw
