"""Generated wrappers must let a caller's ``params=`` reach the transport.

ESPN pages list endpoints (rosters at 100, positions at 25) with no signature
parameter for ``limit``/``page``. Before this, every generated wrapper pinned
``params={...}`` at the ``_get`` call site, so ``params={"limit": 500}`` raised
``TypeError: got multiple values for argument 'params'`` -- there was no way to
reach the query string, and a truncated page is indistinguishable from a whole
one. Assert the merged dict actually ARRIVES at the transport; a test that only
asserts "no TypeError" would pass on a wrapper that silently drops the params.
"""

from pathlib import Path
from unittest.mock import patch

import pytest

from sportsdataverse.cfb.cfb_espn_ext import espn_cfb_scoreboard, espn_cfb_team_roster
from sportsdataverse.mlb.mlb_api import mlb_schedule_postseason
from sportsdataverse.nba.nba_stats import nba_stats_leaguedashplayerstats


class _FakeResp:
    def json(self):
        return {}


def _download_spy():
    return patch("sportsdataverse._codegen_runtime.download", return_value=_FakeResp())


def test_espn_wrapper_forwards_caller_params():
    """The roster case that truncated at 100 players in cfbfastR-cfb-raw."""
    with _download_spy() as dl:
        espn_cfb_team_roster(333, params={"limit": 500}, return_parsed=False)
    assert dl.call_args.kwargs["params"] == {"limit": 500}


def test_espn_wrapper_without_caller_params_keeps_generated_defaults():
    with _download_spy() as dl:
        espn_cfb_scoreboard(dates="20240115", limit=25, return_parsed=False)
    # _get strips the None-valued generated entries before the request.
    assert dl.call_args.kwargs["params"] == {"dates": "20240115", "limit": 25}


def test_caller_params_win_over_generated_defaults():
    with _download_spy() as dl:
        espn_cfb_scoreboard(dates="20240115", limit=25, params={"limit": 900}, return_parsed=False)
    assert dl.call_args.kwargs["params"] == {"dates": "20240115", "limit": 900}


def test_passthrough_query_family_forwards_caller_params():
    """``passthrough_query: true`` families (mlb_api, nhl_records, ...) splat
    kwargs into the query string, so ``params=`` must be popped out first."""
    with _download_spy() as dl:
        mlb_schedule_postseason(season=2024, params={"gameType": "W"}, return_parsed=False)
    sent = dl.call_args.kwargs["params"]
    assert sent["gameType"] == "W"
    assert sent["season"] == 2024
    assert "params" not in sent


def test_getter_module_family_forwards_caller_params():
    """Families with their own ``_get`` (nba_stats/wnba_stats, nfl_api, statcast)."""
    seen = {}

    def fake_transport(url, params, headers, proxy_url):
        seen.update(params)
        return 200, '{"resultSets": []}'

    nba_stats_leaguedashplayerstats(league_id="00", params={"PORound": 1}, transport=fake_transport)
    assert seen["PORound"] == 1
    assert seen["LeagueID"] == "00"


_GENERATED = sorted(
    p
    for p in Path(__file__).resolve().parents[2].joinpath("sportsdataverse").rglob("*.py")
    if p.read_text(encoding="utf-8").startswith("# GENERATED by tools/codegen/generate.py")
)


def test_no_generated_module_pins_params_at_the_call_site():
    """Regression guard for the whole surface, not just the four probes above."""
    assert _GENERATED, "no generated modules found -- the marker comment moved?"
    offenders = [str(p) for p in _GENERATED if "        params={" in p.read_text(encoding="utf-8")]
    assert offenders == []


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(pytest.main([__file__, "-q"]))
