# GENERATED by tools/codegen/generate.py -- DO NOT EDIT.
# Source: tools/codegen/endpoints/nflpro.yaml
"""nflpro wrappers (host https://pro.nfl.com). Generated."""

from __future__ import annotations

from typing import TYPE_CHECKING, Dict, List, Optional, Union  # noqa: F401

from sportsdataverse.nfl.nflpro_runtime import _get
from sportsdataverse.nfl.nflpro_parsers import parse_nfl_pro_stats

if TYPE_CHECKING:  # pragma: no cover -- annotation-only imports (PEP 563 defers eval)
    import pandas as pd
    import polars as pl

__all__ = [
    "nfl_pro_players_offense_passing_season",
    "nfl_pro_players_offense_passing_week",
    "nfl_pro_players_offense_rushing_season",
    "nfl_pro_players_offense_rushing_week",
    "nfl_pro_players_offense_receiving_season",
    "nfl_pro_players_offense_receiving_week",
    "nfl_pro_defense_overview_season",
    "nfl_pro_defense_overview_week",
    "nfl_pro_defense_nearest_season",
    "nfl_pro_defense_nearest_week",
    "nfl_pro_team_offense_overview_season",
    "nfl_pro_team_offense_overview_week",
    "nfl_pro_team_defense_overview_season",
    "nfl_pro_team_defense_overview_week",
    "nfl_pro_fantasy_season",
    "nfl_pro_fantasy_game",
]


def nfl_pro_players_offense_passing_season(
    season: Optional[int] = 2024,
    season_type: Optional[str] = "REG",
    limit: Optional[int] = 500,
    offset: Optional[int] = None,
    sort_key: Optional[str] = None,
    sort_value: Optional[str] = None,
    qualified: Optional[bool] = None,
    headers: Optional[Dict[str, str]] = None,
    *,
    return_parsed: bool = True,
    return_as_pandas: bool = False,
    **kwargs,
) -> Union[pl.DataFrame, pd.DataFrame, Dict]:
    """GET /api/secured/stats/players-offense/passing/season — one row per passer for the season — quarterback passing incl. Next Gen time-to-throw, aggressiveness and CPOE.

    Endpoint: ``GET https://pro.nfl.com/api/secured/stats/players-offense/passing/season``
    Example URL: https://pro.nfl.com/api/secured/stats/players-offense/passing/season?season=2024&seasonType=REG

    Args:
        season: season query parameter.
        season_type: seasonType query parameter.
        limit: limit query parameter.
        offset: offset query parameter.
        sort_key: sortKey query parameter.
        sort_value: sortValue query parameter.
        qualified: qualifiedPasser query parameter.
        headers: optional pre-minted auth headers dict from ``nflpro_headers_gen()`` to reuse across calls (obtaining a token costs a browser login). A token is resolved when omitted; note an anonymous/client-credentials token is NOT usable here -- every ``/api/secured/*`` route 401s without an active NFL+ plan.
        return_parsed: parse the payload through parse_nfl_pro_stats -> polars DataFrame (default True). Pass return_parsed=False for the raw JSON Dict.
        return_as_pandas: with return_parsed, return a pandas DataFrame instead of polars.
        **kwargs: Forwarded to the underlying HTTP getter.

    Returns:
        A polars/pandas DataFrame by default; the raw JSON ``Dict`` when ``return_parsed=False``.

    Raises:
        NFLProAuthError: No user-bound NFL Pro token could be resolved (pass ``token=`` or ``email=``/``password=``, or set ``NFLPRO_TOKEN``, or ``NFLPRO_EMAIL``/``NFLPRO_PW``), or the resolved token carries no active NFL_PLUS_* plan.
        ValueError: pro.nfl.com returned HTTP 200 with an empty body -- how it signals rejected query params, since it sends no error envelope.

    Example:
        Quick start::

            from sportsdataverse.nfl import nfl_pro_players_offense_passing_season
            nfl_pro_players_offense_passing_season(season=2024, season_type='REG')
    """
    _caller_params = kwargs.pop("params", None) or {}
    _params = {
        "season": season,
        "seasonType": season_type,
        "limit": limit,
        "offset": offset,
        "sortKey": sort_key,
        "sortValue": sort_value,
        "qualifiedPasser": qualified,
    }
    _params.update(_caller_params)
    raw = _get(
        "https://pro.nfl.com/api/secured/stats/players-offense/passing/season",
        params=_params,
        headers=headers,
        **kwargs,
    )
    if return_parsed:
        return parse_nfl_pro_stats(raw, return_as_pandas=return_as_pandas)
    return raw


def nfl_pro_players_offense_passing_week(
    season: Optional[int] = 2024,
    season_type: Optional[str] = "REG",
    limit: Optional[int] = 500,
    offset: Optional[int] = None,
    sort_key: Optional[str] = None,
    sort_value: Optional[str] = None,
    qualified: Optional[bool] = None,
    nfl_id: Optional[int] = None,
    headers: Optional[Dict[str, str]] = None,
    *,
    return_parsed: bool = True,
    return_as_pandas: bool = False,
    **kwargs,
) -> Union[pl.DataFrame, pd.DataFrame, Dict]:
    """GET /api/secured/stats/players-offense/passing/week — one row per passer per week — quarterback passing incl. Next Gen time-to-throw, aggressiveness and CPOE.

    Endpoint: ``GET https://pro.nfl.com/api/secured/stats/players-offense/passing/week``
    Example URL: https://pro.nfl.com/api/secured/stats/players-offense/passing/week?season=2024&seasonType=REG

    Args:
        season: season query parameter.
        season_type: seasonType query parameter.
        limit: limit query parameter.
        offset: offset query parameter.
        sort_key: sortKey query parameter.
        sort_value: sortValue query parameter.
        qualified: qualifiedPasser query parameter.
        nfl_id: nflId query parameter.
        headers: optional pre-minted auth headers dict from ``nflpro_headers_gen()`` to reuse across calls (obtaining a token costs a browser login). A token is resolved when omitted; note an anonymous/client-credentials token is NOT usable here -- every ``/api/secured/*`` route 401s without an active NFL+ plan.
        return_parsed: parse the payload through parse_nfl_pro_stats -> polars DataFrame (default True). Pass return_parsed=False for the raw JSON Dict.
        return_as_pandas: with return_parsed, return a pandas DataFrame instead of polars.
        **kwargs: Forwarded to the underlying HTTP getter.

    Returns:
        A polars/pandas DataFrame by default; the raw JSON ``Dict`` when ``return_parsed=False``.

    Raises:
        NFLProAuthError: No user-bound NFL Pro token could be resolved (pass ``token=`` or ``email=``/``password=``, or set ``NFLPRO_TOKEN``, or ``NFLPRO_EMAIL``/``NFLPRO_PW``), or the resolved token carries no active NFL_PLUS_* plan.
        ValueError: pro.nfl.com returned HTTP 200 with an empty body -- how it signals rejected query params, since it sends no error envelope.

    Example:
        Quick start::

            from sportsdataverse.nfl import nfl_pro_players_offense_passing_week
            nfl_pro_players_offense_passing_week(season=2024, season_type='REG')
    """
    _caller_params = kwargs.pop("params", None) or {}
    _params = {
        "season": season,
        "seasonType": season_type,
        "limit": limit,
        "offset": offset,
        "sortKey": sort_key,
        "sortValue": sort_value,
        "qualifiedPasser": qualified,
        "nflId": nfl_id,
    }
    _params.update(_caller_params)
    raw = _get(
        "https://pro.nfl.com/api/secured/stats/players-offense/passing/week",
        params=_params,
        headers=headers,
        **kwargs,
    )
    if return_parsed:
        return parse_nfl_pro_stats(raw, return_as_pandas=return_as_pandas)
    return raw


def nfl_pro_players_offense_rushing_season(
    season: Optional[int] = 2024,
    season_type: Optional[str] = "REG",
    limit: Optional[int] = 500,
    offset: Optional[int] = None,
    sort_key: Optional[str] = None,
    sort_value: Optional[str] = None,
    qualified: Optional[bool] = None,
    headers: Optional[Dict[str, str]] = None,
    *,
    return_parsed: bool = True,
    return_as_pandas: bool = False,
    **kwargs,
) -> Union[pl.DataFrame, pd.DataFrame, Dict]:
    """GET /api/secured/stats/players-offense/rushing/season — one row per rusher for the season — rushing incl. Next Gen efficiency, yards over expected and defenders-in-box.

    Endpoint: ``GET https://pro.nfl.com/api/secured/stats/players-offense/rushing/season``
    Example URL: https://pro.nfl.com/api/secured/stats/players-offense/rushing/season?season=2024&seasonType=REG

    Args:
        season: season query parameter.
        season_type: seasonType query parameter.
        limit: limit query parameter.
        offset: offset query parameter.
        sort_key: sortKey query parameter.
        sort_value: sortValue query parameter.
        qualified: qualifiedRusher query parameter.
        headers: optional pre-minted auth headers dict from ``nflpro_headers_gen()`` to reuse across calls (obtaining a token costs a browser login). A token is resolved when omitted; note an anonymous/client-credentials token is NOT usable here -- every ``/api/secured/*`` route 401s without an active NFL+ plan.
        return_parsed: parse the payload through parse_nfl_pro_stats -> polars DataFrame (default True). Pass return_parsed=False for the raw JSON Dict.
        return_as_pandas: with return_parsed, return a pandas DataFrame instead of polars.
        **kwargs: Forwarded to the underlying HTTP getter.

    Returns:
        A polars/pandas DataFrame by default; the raw JSON ``Dict`` when ``return_parsed=False``.

    Raises:
        NFLProAuthError: No user-bound NFL Pro token could be resolved (pass ``token=`` or ``email=``/``password=``, or set ``NFLPRO_TOKEN``, or ``NFLPRO_EMAIL``/``NFLPRO_PW``), or the resolved token carries no active NFL_PLUS_* plan.
        ValueError: pro.nfl.com returned HTTP 200 with an empty body -- how it signals rejected query params, since it sends no error envelope.

    Example:
        Quick start::

            from sportsdataverse.nfl import nfl_pro_players_offense_rushing_season
            nfl_pro_players_offense_rushing_season(season=2024, season_type='REG')
    """
    _caller_params = kwargs.pop("params", None) or {}
    _params = {
        "season": season,
        "seasonType": season_type,
        "limit": limit,
        "offset": offset,
        "sortKey": sort_key,
        "sortValue": sort_value,
        "qualifiedRusher": qualified,
    }
    _params.update(_caller_params)
    raw = _get(
        "https://pro.nfl.com/api/secured/stats/players-offense/rushing/season",
        params=_params,
        headers=headers,
        **kwargs,
    )
    if return_parsed:
        return parse_nfl_pro_stats(raw, return_as_pandas=return_as_pandas)
    return raw


def nfl_pro_players_offense_rushing_week(
    season: Optional[int] = 2024,
    season_type: Optional[str] = "REG",
    limit: Optional[int] = 500,
    offset: Optional[int] = None,
    sort_key: Optional[str] = None,
    sort_value: Optional[str] = None,
    qualified: Optional[bool] = None,
    nfl_id: Optional[int] = None,
    headers: Optional[Dict[str, str]] = None,
    *,
    return_parsed: bool = True,
    return_as_pandas: bool = False,
    **kwargs,
) -> Union[pl.DataFrame, pd.DataFrame, Dict]:
    """GET /api/secured/stats/players-offense/rushing/week — one row per rusher per week — rushing incl. Next Gen efficiency, yards over expected and defenders-in-box.

    Endpoint: ``GET https://pro.nfl.com/api/secured/stats/players-offense/rushing/week``
    Example URL: https://pro.nfl.com/api/secured/stats/players-offense/rushing/week?season=2024&seasonType=REG

    Args:
        season: season query parameter.
        season_type: seasonType query parameter.
        limit: limit query parameter.
        offset: offset query parameter.
        sort_key: sortKey query parameter.
        sort_value: sortValue query parameter.
        qualified: qualifiedRusher query parameter.
        nfl_id: nflId query parameter.
        headers: optional pre-minted auth headers dict from ``nflpro_headers_gen()`` to reuse across calls (obtaining a token costs a browser login). A token is resolved when omitted; note an anonymous/client-credentials token is NOT usable here -- every ``/api/secured/*`` route 401s without an active NFL+ plan.
        return_parsed: parse the payload through parse_nfl_pro_stats -> polars DataFrame (default True). Pass return_parsed=False for the raw JSON Dict.
        return_as_pandas: with return_parsed, return a pandas DataFrame instead of polars.
        **kwargs: Forwarded to the underlying HTTP getter.

    Returns:
        A polars/pandas DataFrame by default; the raw JSON ``Dict`` when ``return_parsed=False``.

    Raises:
        NFLProAuthError: No user-bound NFL Pro token could be resolved (pass ``token=`` or ``email=``/``password=``, or set ``NFLPRO_TOKEN``, or ``NFLPRO_EMAIL``/``NFLPRO_PW``), or the resolved token carries no active NFL_PLUS_* plan.
        ValueError: pro.nfl.com returned HTTP 200 with an empty body -- how it signals rejected query params, since it sends no error envelope.

    Example:
        Quick start::

            from sportsdataverse.nfl import nfl_pro_players_offense_rushing_week
            nfl_pro_players_offense_rushing_week(season=2024, season_type='REG')
    """
    _caller_params = kwargs.pop("params", None) or {}
    _params = {
        "season": season,
        "seasonType": season_type,
        "limit": limit,
        "offset": offset,
        "sortKey": sort_key,
        "sortValue": sort_value,
        "qualifiedRusher": qualified,
        "nflId": nfl_id,
    }
    _params.update(_caller_params)
    raw = _get(
        "https://pro.nfl.com/api/secured/stats/players-offense/rushing/week",
        params=_params,
        headers=headers,
        **kwargs,
    )
    if return_parsed:
        return parse_nfl_pro_stats(raw, return_as_pandas=return_as_pandas)
    return raw


def nfl_pro_players_offense_receiving_season(
    season: Optional[int] = 2024,
    season_type: Optional[str] = "REG",
    limit: Optional[int] = 500,
    offset: Optional[int] = None,
    sort_key: Optional[str] = None,
    sort_value: Optional[str] = None,
    qualified: Optional[bool] = None,
    headers: Optional[Dict[str, str]] = None,
    *,
    return_parsed: bool = True,
    return_as_pandas: bool = False,
    **kwargs,
) -> Union[pl.DataFrame, pd.DataFrame, Dict]:
    """GET /api/secured/stats/players-offense/receiving/season — one row per receiver for the season — receiving incl. Next Gen separation, cushion and catch rate over expected.

    Endpoint: ``GET https://pro.nfl.com/api/secured/stats/players-offense/receiving/season``
    Example URL: https://pro.nfl.com/api/secured/stats/players-offense/receiving/season?season=2024&seasonType=REG

    Args:
        season: season query parameter.
        season_type: seasonType query parameter.
        limit: limit query parameter.
        offset: offset query parameter.
        sort_key: sortKey query parameter.
        sort_value: sortValue query parameter.
        qualified: qualifiedReceiver query parameter.
        headers: optional pre-minted auth headers dict from ``nflpro_headers_gen()`` to reuse across calls (obtaining a token costs a browser login). A token is resolved when omitted; note an anonymous/client-credentials token is NOT usable here -- every ``/api/secured/*`` route 401s without an active NFL+ plan.
        return_parsed: parse the payload through parse_nfl_pro_stats -> polars DataFrame (default True). Pass return_parsed=False for the raw JSON Dict.
        return_as_pandas: with return_parsed, return a pandas DataFrame instead of polars.
        **kwargs: Forwarded to the underlying HTTP getter.

    Returns:
        A polars/pandas DataFrame by default; the raw JSON ``Dict`` when ``return_parsed=False``.

    Raises:
        NFLProAuthError: No user-bound NFL Pro token could be resolved (pass ``token=`` or ``email=``/``password=``, or set ``NFLPRO_TOKEN``, or ``NFLPRO_EMAIL``/``NFLPRO_PW``), or the resolved token carries no active NFL_PLUS_* plan.
        ValueError: pro.nfl.com returned HTTP 200 with an empty body -- how it signals rejected query params, since it sends no error envelope.

    Example:
        Quick start::

            from sportsdataverse.nfl import nfl_pro_players_offense_receiving_season
            nfl_pro_players_offense_receiving_season(season=2024, season_type='REG')
    """
    _caller_params = kwargs.pop("params", None) or {}
    _params = {
        "season": season,
        "seasonType": season_type,
        "limit": limit,
        "offset": offset,
        "sortKey": sort_key,
        "sortValue": sort_value,
        "qualifiedReceiver": qualified,
    }
    _params.update(_caller_params)
    raw = _get(
        "https://pro.nfl.com/api/secured/stats/players-offense/receiving/season",
        params=_params,
        headers=headers,
        **kwargs,
    )
    if return_parsed:
        return parse_nfl_pro_stats(raw, return_as_pandas=return_as_pandas)
    return raw


def nfl_pro_players_offense_receiving_week(
    season: Optional[int] = 2024,
    season_type: Optional[str] = "REG",
    limit: Optional[int] = 500,
    offset: Optional[int] = None,
    sort_key: Optional[str] = None,
    sort_value: Optional[str] = None,
    qualified: Optional[bool] = None,
    nfl_id: Optional[int] = None,
    headers: Optional[Dict[str, str]] = None,
    *,
    return_parsed: bool = True,
    return_as_pandas: bool = False,
    **kwargs,
) -> Union[pl.DataFrame, pd.DataFrame, Dict]:
    """GET /api/secured/stats/players-offense/receiving/week — one row per receiver per week — receiving incl. Next Gen separation, cushion and catch rate over expected.

    Endpoint: ``GET https://pro.nfl.com/api/secured/stats/players-offense/receiving/week``
    Example URL: https://pro.nfl.com/api/secured/stats/players-offense/receiving/week?season=2024&seasonType=REG

    Args:
        season: season query parameter.
        season_type: seasonType query parameter.
        limit: limit query parameter.
        offset: offset query parameter.
        sort_key: sortKey query parameter.
        sort_value: sortValue query parameter.
        qualified: qualifiedReceiver query parameter.
        nfl_id: nflId query parameter.
        headers: optional pre-minted auth headers dict from ``nflpro_headers_gen()`` to reuse across calls (obtaining a token costs a browser login). A token is resolved when omitted; note an anonymous/client-credentials token is NOT usable here -- every ``/api/secured/*`` route 401s without an active NFL+ plan.
        return_parsed: parse the payload through parse_nfl_pro_stats -> polars DataFrame (default True). Pass return_parsed=False for the raw JSON Dict.
        return_as_pandas: with return_parsed, return a pandas DataFrame instead of polars.
        **kwargs: Forwarded to the underlying HTTP getter.

    Returns:
        A polars/pandas DataFrame by default; the raw JSON ``Dict`` when ``return_parsed=False``.

    Raises:
        NFLProAuthError: No user-bound NFL Pro token could be resolved (pass ``token=`` or ``email=``/``password=``, or set ``NFLPRO_TOKEN``, or ``NFLPRO_EMAIL``/``NFLPRO_PW``), or the resolved token carries no active NFL_PLUS_* plan.
        ValueError: pro.nfl.com returned HTTP 200 with an empty body -- how it signals rejected query params, since it sends no error envelope.

    Example:
        Quick start::

            from sportsdataverse.nfl import nfl_pro_players_offense_receiving_week
            nfl_pro_players_offense_receiving_week(season=2024, season_type='REG')
    """
    _caller_params = kwargs.pop("params", None) or {}
    _params = {
        "season": season,
        "seasonType": season_type,
        "limit": limit,
        "offset": offset,
        "sortKey": sort_key,
        "sortValue": sort_value,
        "qualifiedReceiver": qualified,
        "nflId": nfl_id,
    }
    _params.update(_caller_params)
    raw = _get(
        "https://pro.nfl.com/api/secured/stats/players-offense/receiving/week",
        params=_params,
        headers=headers,
        **kwargs,
    )
    if return_parsed:
        return parse_nfl_pro_stats(raw, return_as_pandas=return_as_pandas)
    return raw


def nfl_pro_defense_overview_season(
    season: Optional[int] = 2024,
    season_type: Optional[str] = "REG",
    limit: Optional[int] = 500,
    offset: Optional[int] = None,
    sort_key: Optional[str] = None,
    sort_value: Optional[str] = None,
    qualified: Optional[bool] = None,
    headers: Optional[Dict[str, str]] = None,
    *,
    return_parsed: bool = True,
    return_as_pandas: bool = False,
    **kwargs,
) -> Union[pl.DataFrame, pd.DataFrame, Dict]:
    """GET /api/secured/stats/defense/overview/season — one row per defender for the season — defensive overview incl. snap counts, pressures and havoc stops.

    Endpoint: ``GET https://pro.nfl.com/api/secured/stats/defense/overview/season``
    Example URL: https://pro.nfl.com/api/secured/stats/defense/overview/season?season=2024&seasonType=REG

    Args:
        season: season query parameter.
        season_type: seasonType query parameter.
        limit: limit query parameter.
        offset: offset query parameter.
        sort_key: sortKey query parameter.
        sort_value: sortValue query parameter.
        qualified: qualifiedDefender query parameter.
        headers: optional pre-minted auth headers dict from ``nflpro_headers_gen()`` to reuse across calls (obtaining a token costs a browser login). A token is resolved when omitted; note an anonymous/client-credentials token is NOT usable here -- every ``/api/secured/*`` route 401s without an active NFL+ plan.
        return_parsed: parse the payload through parse_nfl_pro_stats -> polars DataFrame (default True). Pass return_parsed=False for the raw JSON Dict.
        return_as_pandas: with return_parsed, return a pandas DataFrame instead of polars.
        **kwargs: Forwarded to the underlying HTTP getter.

    Returns:
        A polars/pandas DataFrame by default; the raw JSON ``Dict`` when ``return_parsed=False``.

    Raises:
        NFLProAuthError: No user-bound NFL Pro token could be resolved (pass ``token=`` or ``email=``/``password=``, or set ``NFLPRO_TOKEN``, or ``NFLPRO_EMAIL``/``NFLPRO_PW``), or the resolved token carries no active NFL_PLUS_* plan.
        ValueError: pro.nfl.com returned HTTP 200 with an empty body -- how it signals rejected query params, since it sends no error envelope.

    Example:
        Quick start::

            from sportsdataverse.nfl import nfl_pro_defense_overview_season
            nfl_pro_defense_overview_season(season=2024, season_type='REG')
    """
    _caller_params = kwargs.pop("params", None) or {}
    _params = {
        "season": season,
        "seasonType": season_type,
        "limit": limit,
        "offset": offset,
        "sortKey": sort_key,
        "sortValue": sort_value,
        "qualifiedDefender": qualified,
    }
    _params.update(_caller_params)
    raw = _get(
        "https://pro.nfl.com/api/secured/stats/defense/overview/season",
        params=_params,
        headers=headers,
        **kwargs,
    )
    if return_parsed:
        return parse_nfl_pro_stats(raw, return_as_pandas=return_as_pandas)
    return raw


def nfl_pro_defense_overview_week(
    season: Optional[int] = 2024,
    season_type: Optional[str] = "REG",
    limit: Optional[int] = 500,
    offset: Optional[int] = None,
    sort_key: Optional[str] = None,
    sort_value: Optional[str] = None,
    qualified: Optional[bool] = None,
    nfl_id: Optional[int] = None,
    headers: Optional[Dict[str, str]] = None,
    *,
    return_parsed: bool = True,
    return_as_pandas: bool = False,
    **kwargs,
) -> Union[pl.DataFrame, pd.DataFrame, Dict]:
    """GET /api/secured/stats/defense/overview/week — one row per defender per week — defensive overview incl. snap counts, pressures and havoc stops.

    Endpoint: ``GET https://pro.nfl.com/api/secured/stats/defense/overview/week``
    Example URL: https://pro.nfl.com/api/secured/stats/defense/overview/week?season=2024&seasonType=REG

    Args:
        season: season query parameter.
        season_type: seasonType query parameter.
        limit: limit query parameter.
        offset: offset query parameter.
        sort_key: sortKey query parameter.
        sort_value: sortValue query parameter.
        qualified: qualifiedDefender query parameter.
        nfl_id: nflId query parameter.
        headers: optional pre-minted auth headers dict from ``nflpro_headers_gen()`` to reuse across calls (obtaining a token costs a browser login). A token is resolved when omitted; note an anonymous/client-credentials token is NOT usable here -- every ``/api/secured/*`` route 401s without an active NFL+ plan.
        return_parsed: parse the payload through parse_nfl_pro_stats -> polars DataFrame (default True). Pass return_parsed=False for the raw JSON Dict.
        return_as_pandas: with return_parsed, return a pandas DataFrame instead of polars.
        **kwargs: Forwarded to the underlying HTTP getter.

    Returns:
        A polars/pandas DataFrame by default; the raw JSON ``Dict`` when ``return_parsed=False``.

    Raises:
        NFLProAuthError: No user-bound NFL Pro token could be resolved (pass ``token=`` or ``email=``/``password=``, or set ``NFLPRO_TOKEN``, or ``NFLPRO_EMAIL``/``NFLPRO_PW``), or the resolved token carries no active NFL_PLUS_* plan.
        ValueError: pro.nfl.com returned HTTP 200 with an empty body -- how it signals rejected query params, since it sends no error envelope.

    Example:
        Quick start::

            from sportsdataverse.nfl import nfl_pro_defense_overview_week
            nfl_pro_defense_overview_week(season=2024, season_type='REG')
    """
    _caller_params = kwargs.pop("params", None) or {}
    _params = {
        "season": season,
        "seasonType": season_type,
        "limit": limit,
        "offset": offset,
        "sortKey": sort_key,
        "sortValue": sort_value,
        "qualifiedDefender": qualified,
        "nflId": nfl_id,
    }
    _params.update(_caller_params)
    raw = _get(
        "https://pro.nfl.com/api/secured/stats/defense/overview/week",
        params=_params,
        headers=headers,
        **kwargs,
    )
    if return_parsed:
        return parse_nfl_pro_stats(raw, return_as_pandas=return_as_pandas)
    return raw


def nfl_pro_defense_nearest_season(
    season: Optional[int] = 2024,
    season_type: Optional[str] = "REG",
    limit: Optional[int] = 500,
    offset: Optional[int] = None,
    sort_key: Optional[str] = None,
    sort_value: Optional[str] = None,
    qualified: Optional[bool] = None,
    headers: Optional[Dict[str, str]] = None,
    *,
    return_parsed: bool = True,
    return_as_pandas: bool = False,
    **kwargs,
) -> Union[pl.DataFrame, pd.DataFrame, Dict]:
    """GET /api/secured/stats/defense/nearest/season — one row per defender for the season — nearest-defender coverage incl. targets, catch rate and CROE allowed.

    Endpoint: ``GET https://pro.nfl.com/api/secured/stats/defense/nearest/season``
    Example URL: https://pro.nfl.com/api/secured/stats/defense/nearest/season?season=2024&seasonType=REG

    Args:
        season: season query parameter.
        season_type: seasonType query parameter.
        limit: limit query parameter.
        offset: offset query parameter.
        sort_key: sortKey query parameter.
        sort_value: sortValue query parameter.
        qualified: qualifiedDefender query parameter.
        headers: optional pre-minted auth headers dict from ``nflpro_headers_gen()`` to reuse across calls (obtaining a token costs a browser login). A token is resolved when omitted; note an anonymous/client-credentials token is NOT usable here -- every ``/api/secured/*`` route 401s without an active NFL+ plan.
        return_parsed: parse the payload through parse_nfl_pro_stats -> polars DataFrame (default True). Pass return_parsed=False for the raw JSON Dict.
        return_as_pandas: with return_parsed, return a pandas DataFrame instead of polars.
        **kwargs: Forwarded to the underlying HTTP getter.

    Returns:
        A polars/pandas DataFrame by default; the raw JSON ``Dict`` when ``return_parsed=False``.

    Raises:
        NFLProAuthError: No user-bound NFL Pro token could be resolved (pass ``token=`` or ``email=``/``password=``, or set ``NFLPRO_TOKEN``, or ``NFLPRO_EMAIL``/``NFLPRO_PW``), or the resolved token carries no active NFL_PLUS_* plan.
        ValueError: pro.nfl.com returned HTTP 200 with an empty body -- how it signals rejected query params, since it sends no error envelope.

    Example:
        Quick start::

            from sportsdataverse.nfl import nfl_pro_defense_nearest_season
            nfl_pro_defense_nearest_season(season=2024, season_type='REG')
    """
    _caller_params = kwargs.pop("params", None) or {}
    _params = {
        "season": season,
        "seasonType": season_type,
        "limit": limit,
        "offset": offset,
        "sortKey": sort_key,
        "sortValue": sort_value,
        "qualifiedDefender": qualified,
    }
    _params.update(_caller_params)
    raw = _get(
        "https://pro.nfl.com/api/secured/stats/defense/nearest/season",
        params=_params,
        headers=headers,
        **kwargs,
    )
    if return_parsed:
        return parse_nfl_pro_stats(raw, return_as_pandas=return_as_pandas)
    return raw


def nfl_pro_defense_nearest_week(
    season: Optional[int] = 2024,
    season_type: Optional[str] = "REG",
    limit: Optional[int] = 500,
    offset: Optional[int] = None,
    sort_key: Optional[str] = None,
    sort_value: Optional[str] = None,
    qualified: Optional[bool] = None,
    nfl_id: Optional[int] = None,
    headers: Optional[Dict[str, str]] = None,
    *,
    return_parsed: bool = True,
    return_as_pandas: bool = False,
    **kwargs,
) -> Union[pl.DataFrame, pd.DataFrame, Dict]:
    """GET /api/secured/stats/defense/nearest/week — one row per defender per week — nearest-defender coverage incl. targets, catch rate and CROE allowed.

    Endpoint: ``GET https://pro.nfl.com/api/secured/stats/defense/nearest/week``
    Example URL: https://pro.nfl.com/api/secured/stats/defense/nearest/week?season=2024&seasonType=REG

    Args:
        season: season query parameter.
        season_type: seasonType query parameter.
        limit: limit query parameter.
        offset: offset query parameter.
        sort_key: sortKey query parameter.
        sort_value: sortValue query parameter.
        qualified: qualifiedDefender query parameter.
        nfl_id: nflId query parameter.
        headers: optional pre-minted auth headers dict from ``nflpro_headers_gen()`` to reuse across calls (obtaining a token costs a browser login). A token is resolved when omitted; note an anonymous/client-credentials token is NOT usable here -- every ``/api/secured/*`` route 401s without an active NFL+ plan.
        return_parsed: parse the payload through parse_nfl_pro_stats -> polars DataFrame (default True). Pass return_parsed=False for the raw JSON Dict.
        return_as_pandas: with return_parsed, return a pandas DataFrame instead of polars.
        **kwargs: Forwarded to the underlying HTTP getter.

    Returns:
        A polars/pandas DataFrame by default; the raw JSON ``Dict`` when ``return_parsed=False``.

    Raises:
        NFLProAuthError: No user-bound NFL Pro token could be resolved (pass ``token=`` or ``email=``/``password=``, or set ``NFLPRO_TOKEN``, or ``NFLPRO_EMAIL``/``NFLPRO_PW``), or the resolved token carries no active NFL_PLUS_* plan.
        ValueError: pro.nfl.com returned HTTP 200 with an empty body -- how it signals rejected query params, since it sends no error envelope.

    Example:
        Quick start::

            from sportsdataverse.nfl import nfl_pro_defense_nearest_week
            nfl_pro_defense_nearest_week(season=2024, season_type='REG')
    """
    _caller_params = kwargs.pop("params", None) or {}
    _params = {
        "season": season,
        "seasonType": season_type,
        "limit": limit,
        "offset": offset,
        "sortKey": sort_key,
        "sortValue": sort_value,
        "qualifiedDefender": qualified,
        "nflId": nfl_id,
    }
    _params.update(_caller_params)
    raw = _get(
        "https://pro.nfl.com/api/secured/stats/defense/nearest/week",
        params=_params,
        headers=headers,
        **kwargs,
    )
    if return_parsed:
        return parse_nfl_pro_stats(raw, return_as_pandas=return_as_pandas)
    return raw


def nfl_pro_team_offense_overview_season(
    season: Optional[int] = 2024,
    season_type: Optional[str] = "REG",
    limit: Optional[int] = 500,
    offset: Optional[int] = None,
    sort_key: Optional[str] = None,
    sort_value: Optional[str] = None,
    headers: Optional[Dict[str, str]] = None,
    *,
    return_parsed: bool = True,
    return_as_pandas: bool = False,
    **kwargs,
) -> Union[pl.DataFrame, pd.DataFrame, Dict]:
    """GET /api/secured/stats/team-offense/overview/season — one row per team for the season — team offensive overview incl. EPA per play, pass and rush splits.

    Endpoint: ``GET https://pro.nfl.com/api/secured/stats/team-offense/overview/season``
    Example URL: https://pro.nfl.com/api/secured/stats/team-offense/overview/season?season=2024&seasonType=REG

    Args:
        season: season query parameter.
        season_type: seasonType query parameter.
        limit: limit query parameter.
        offset: offset query parameter.
        sort_key: sortKey query parameter.
        sort_value: sortValue query parameter.
        headers: optional pre-minted auth headers dict from ``nflpro_headers_gen()`` to reuse across calls (obtaining a token costs a browser login). A token is resolved when omitted; note an anonymous/client-credentials token is NOT usable here -- every ``/api/secured/*`` route 401s without an active NFL+ plan.
        return_parsed: parse the payload through parse_nfl_pro_stats -> polars DataFrame (default True). Pass return_parsed=False for the raw JSON Dict.
        return_as_pandas: with return_parsed, return a pandas DataFrame instead of polars.
        **kwargs: Forwarded to the underlying HTTP getter.

    Returns:
        A polars/pandas DataFrame by default; the raw JSON ``Dict`` when ``return_parsed=False``.

    Raises:
        NFLProAuthError: No user-bound NFL Pro token could be resolved (pass ``token=`` or ``email=``/``password=``, or set ``NFLPRO_TOKEN``, or ``NFLPRO_EMAIL``/``NFLPRO_PW``), or the resolved token carries no active NFL_PLUS_* plan.
        ValueError: pro.nfl.com returned HTTP 200 with an empty body -- how it signals rejected query params, since it sends no error envelope.

    Example:
        Quick start::

            from sportsdataverse.nfl import nfl_pro_team_offense_overview_season
            nfl_pro_team_offense_overview_season(season=2024, season_type='REG')
    """
    _caller_params = kwargs.pop("params", None) or {}
    _params = {
        "season": season,
        "seasonType": season_type,
        "limit": limit,
        "offset": offset,
        "sortKey": sort_key,
        "sortValue": sort_value,
    }
    _params.update(_caller_params)
    raw = _get(
        "https://pro.nfl.com/api/secured/stats/team-offense/overview/season",
        params=_params,
        headers=headers,
        **kwargs,
    )
    if return_parsed:
        return parse_nfl_pro_stats(raw, return_as_pandas=return_as_pandas)
    return raw


def nfl_pro_team_offense_overview_week(
    season: Optional[int] = 2024,
    season_type: Optional[str] = "REG",
    limit: Optional[int] = 500,
    offset: Optional[int] = None,
    sort_key: Optional[str] = None,
    sort_value: Optional[str] = None,
    nfl_id: Optional[int] = None,
    headers: Optional[Dict[str, str]] = None,
    *,
    return_parsed: bool = True,
    return_as_pandas: bool = False,
    **kwargs,
) -> Union[pl.DataFrame, pd.DataFrame, Dict]:
    """GET /api/secured/stats/team-offense/overview/week — one row per team per week — team offensive overview incl. EPA per play, pass and rush splits.

    Endpoint: ``GET https://pro.nfl.com/api/secured/stats/team-offense/overview/week``
    Example URL: https://pro.nfl.com/api/secured/stats/team-offense/overview/week?season=2024&seasonType=REG

    Args:
        season: season query parameter.
        season_type: seasonType query parameter.
        limit: limit query parameter.
        offset: offset query parameter.
        sort_key: sortKey query parameter.
        sort_value: sortValue query parameter.
        nfl_id: nflId query parameter.
        headers: optional pre-minted auth headers dict from ``nflpro_headers_gen()`` to reuse across calls (obtaining a token costs a browser login). A token is resolved when omitted; note an anonymous/client-credentials token is NOT usable here -- every ``/api/secured/*`` route 401s without an active NFL+ plan.
        return_parsed: parse the payload through parse_nfl_pro_stats -> polars DataFrame (default True). Pass return_parsed=False for the raw JSON Dict.
        return_as_pandas: with return_parsed, return a pandas DataFrame instead of polars.
        **kwargs: Forwarded to the underlying HTTP getter.

    Returns:
        A polars/pandas DataFrame by default; the raw JSON ``Dict`` when ``return_parsed=False``.

    Raises:
        NFLProAuthError: No user-bound NFL Pro token could be resolved (pass ``token=`` or ``email=``/``password=``, or set ``NFLPRO_TOKEN``, or ``NFLPRO_EMAIL``/``NFLPRO_PW``), or the resolved token carries no active NFL_PLUS_* plan.
        ValueError: pro.nfl.com returned HTTP 200 with an empty body -- how it signals rejected query params, since it sends no error envelope.

    Example:
        Quick start::

            from sportsdataverse.nfl import nfl_pro_team_offense_overview_week
            nfl_pro_team_offense_overview_week(season=2024, season_type='REG')
    """
    _caller_params = kwargs.pop("params", None) or {}
    _params = {
        "season": season,
        "seasonType": season_type,
        "limit": limit,
        "offset": offset,
        "sortKey": sort_key,
        "sortValue": sort_value,
        "nflId": nfl_id,
    }
    _params.update(_caller_params)
    raw = _get(
        "https://pro.nfl.com/api/secured/stats/team-offense/overview/week",
        params=_params,
        headers=headers,
        **kwargs,
    )
    if return_parsed:
        return parse_nfl_pro_stats(raw, return_as_pandas=return_as_pandas)
    return raw


def nfl_pro_team_defense_overview_season(
    season: Optional[int] = 2024,
    season_type: Optional[str] = "REG",
    limit: Optional[int] = 500,
    offset: Optional[int] = None,
    sort_key: Optional[str] = None,
    sort_value: Optional[str] = None,
    headers: Optional[Dict[str, str]] = None,
    *,
    return_parsed: bool = True,
    return_as_pandas: bool = False,
    **kwargs,
) -> Union[pl.DataFrame, pd.DataFrame, Dict]:
    """GET /api/secured/stats/team-defense/overview/season — one row per team for the season — team defensive overview incl. EPA allowed per play and takeaways.

    Endpoint: ``GET https://pro.nfl.com/api/secured/stats/team-defense/overview/season``
    Example URL: https://pro.nfl.com/api/secured/stats/team-defense/overview/season?season=2024&seasonType=REG

    Args:
        season: season query parameter.
        season_type: seasonType query parameter.
        limit: limit query parameter.
        offset: offset query parameter.
        sort_key: sortKey query parameter.
        sort_value: sortValue query parameter.
        headers: optional pre-minted auth headers dict from ``nflpro_headers_gen()`` to reuse across calls (obtaining a token costs a browser login). A token is resolved when omitted; note an anonymous/client-credentials token is NOT usable here -- every ``/api/secured/*`` route 401s without an active NFL+ plan.
        return_parsed: parse the payload through parse_nfl_pro_stats -> polars DataFrame (default True). Pass return_parsed=False for the raw JSON Dict.
        return_as_pandas: with return_parsed, return a pandas DataFrame instead of polars.
        **kwargs: Forwarded to the underlying HTTP getter.

    Returns:
        A polars/pandas DataFrame by default; the raw JSON ``Dict`` when ``return_parsed=False``.

    Raises:
        NFLProAuthError: No user-bound NFL Pro token could be resolved (pass ``token=`` or ``email=``/``password=``, or set ``NFLPRO_TOKEN``, or ``NFLPRO_EMAIL``/``NFLPRO_PW``), or the resolved token carries no active NFL_PLUS_* plan.
        ValueError: pro.nfl.com returned HTTP 200 with an empty body -- how it signals rejected query params, since it sends no error envelope.

    Example:
        Quick start::

            from sportsdataverse.nfl import nfl_pro_team_defense_overview_season
            nfl_pro_team_defense_overview_season(season=2024, season_type='REG')
    """
    _caller_params = kwargs.pop("params", None) or {}
    _params = {
        "season": season,
        "seasonType": season_type,
        "limit": limit,
        "offset": offset,
        "sortKey": sort_key,
        "sortValue": sort_value,
    }
    _params.update(_caller_params)
    raw = _get(
        "https://pro.nfl.com/api/secured/stats/team-defense/overview/season",
        params=_params,
        headers=headers,
        **kwargs,
    )
    if return_parsed:
        return parse_nfl_pro_stats(raw, return_as_pandas=return_as_pandas)
    return raw


def nfl_pro_team_defense_overview_week(
    season: Optional[int] = 2024,
    season_type: Optional[str] = "REG",
    limit: Optional[int] = 500,
    offset: Optional[int] = None,
    sort_key: Optional[str] = None,
    sort_value: Optional[str] = None,
    nfl_id: Optional[int] = None,
    headers: Optional[Dict[str, str]] = None,
    *,
    return_parsed: bool = True,
    return_as_pandas: bool = False,
    **kwargs,
) -> Union[pl.DataFrame, pd.DataFrame, Dict]:
    """GET /api/secured/stats/team-defense/overview/week — one row per team per week — team defensive overview incl. EPA allowed per play and takeaways.

    Endpoint: ``GET https://pro.nfl.com/api/secured/stats/team-defense/overview/week``
    Example URL: https://pro.nfl.com/api/secured/stats/team-defense/overview/week?season=2024&seasonType=REG

    Args:
        season: season query parameter.
        season_type: seasonType query parameter.
        limit: limit query parameter.
        offset: offset query parameter.
        sort_key: sortKey query parameter.
        sort_value: sortValue query parameter.
        nfl_id: nflId query parameter.
        headers: optional pre-minted auth headers dict from ``nflpro_headers_gen()`` to reuse across calls (obtaining a token costs a browser login). A token is resolved when omitted; note an anonymous/client-credentials token is NOT usable here -- every ``/api/secured/*`` route 401s without an active NFL+ plan.
        return_parsed: parse the payload through parse_nfl_pro_stats -> polars DataFrame (default True). Pass return_parsed=False for the raw JSON Dict.
        return_as_pandas: with return_parsed, return a pandas DataFrame instead of polars.
        **kwargs: Forwarded to the underlying HTTP getter.

    Returns:
        A polars/pandas DataFrame by default; the raw JSON ``Dict`` when ``return_parsed=False``.

    Raises:
        NFLProAuthError: No user-bound NFL Pro token could be resolved (pass ``token=`` or ``email=``/``password=``, or set ``NFLPRO_TOKEN``, or ``NFLPRO_EMAIL``/``NFLPRO_PW``), or the resolved token carries no active NFL_PLUS_* plan.
        ValueError: pro.nfl.com returned HTTP 200 with an empty body -- how it signals rejected query params, since it sends no error envelope.

    Example:
        Quick start::

            from sportsdataverse.nfl import nfl_pro_team_defense_overview_week
            nfl_pro_team_defense_overview_week(season=2024, season_type='REG')
    """
    _caller_params = kwargs.pop("params", None) or {}
    _params = {
        "season": season,
        "seasonType": season_type,
        "limit": limit,
        "offset": offset,
        "sortKey": sort_key,
        "sortValue": sort_value,
        "nflId": nfl_id,
    }
    _params.update(_caller_params)
    raw = _get(
        "https://pro.nfl.com/api/secured/stats/team-defense/overview/week",
        params=_params,
        headers=headers,
        **kwargs,
    )
    if return_parsed:
        return parse_nfl_pro_stats(raw, return_as_pandas=return_as_pandas)
    return raw


def nfl_pro_fantasy_season(
    season: Optional[int] = 2024,
    season_type: Optional[str] = "REG",
    limit: Optional[int] = 500,
    offset: Optional[int] = None,
    nfl_id: Optional[int] = None,
    position_group: Optional[str] = None,
    sort_key: Optional[str] = None,
    sort_value: Optional[str] = None,
    headers: Optional[Dict[str, str]] = None,
    *,
    return_parsed: bool = True,
    return_as_pandas: bool = False,
    **kwargs,
) -> Union[pl.DataFrame, pd.DataFrame, Dict]:
    """GET /api/secured/stats/fantasy/season — one row per player for the season — fantasy points, opportunity and usage.

    Endpoint: ``GET https://pro.nfl.com/api/secured/stats/fantasy/season``
    Example URL: https://pro.nfl.com/api/secured/stats/fantasy/season?season=2024&seasonType=REG

    Args:
        season: season query parameter.
        season_type: seasonType query parameter.
        limit: limit query parameter.
        offset: offset query parameter.
        nfl_id: nflId query parameter.
        position_group: positionGroup query parameter.
        sort_key: sortKey query parameter.
        sort_value: sortValue query parameter.
        headers: optional pre-minted auth headers dict from ``nflpro_headers_gen()`` to reuse across calls (obtaining a token costs a browser login). A token is resolved when omitted; note an anonymous/client-credentials token is NOT usable here -- every ``/api/secured/*`` route 401s without an active NFL+ plan.
        return_parsed: parse the payload through parse_nfl_pro_stats -> polars DataFrame (default True). Pass return_parsed=False for the raw JSON Dict.
        return_as_pandas: with return_parsed, return a pandas DataFrame instead of polars.
        **kwargs: Forwarded to the underlying HTTP getter.

    Returns:
        A polars/pandas DataFrame by default; the raw JSON ``Dict`` when ``return_parsed=False``.

    Raises:
        NFLProAuthError: No user-bound NFL Pro token could be resolved (pass ``token=`` or ``email=``/``password=``, or set ``NFLPRO_TOKEN``, or ``NFLPRO_EMAIL``/``NFLPRO_PW``), or the resolved token carries no active NFL_PLUS_* plan.
        ValueError: pro.nfl.com returned HTTP 200 with an empty body -- how it signals rejected query params, since it sends no error envelope.

    Example:
        Quick start::

            from sportsdataverse.nfl import nfl_pro_fantasy_season
            nfl_pro_fantasy_season(season=2024, season_type='REG')
    """
    _caller_params = kwargs.pop("params", None) or {}
    _params = {
        "season": season,
        "seasonType": season_type,
        "limit": limit,
        "offset": offset,
        "nflId": nfl_id,
        "positionGroup": position_group,
        "sortKey": sort_key,
        "sortValue": sort_value,
    }
    _params.update(_caller_params)
    raw = _get(
        "https://pro.nfl.com/api/secured/stats/fantasy/season",
        params=_params,
        headers=headers,
        **kwargs,
    )
    if return_parsed:
        return parse_nfl_pro_stats(raw, return_as_pandas=return_as_pandas)
    return raw


def nfl_pro_fantasy_game(
    season: Optional[int] = 2024,
    season_type: Optional[str] = "REG",
    limit: Optional[int] = 500,
    offset: Optional[int] = None,
    nfl_id: Optional[int] = None,
    position_group: Optional[str] = None,
    sort_key: Optional[str] = None,
    sort_value: Optional[str] = None,
    headers: Optional[Dict[str, str]] = None,
    *,
    return_parsed: bool = True,
    return_as_pandas: bool = False,
    **kwargs,
) -> Union[pl.DataFrame, pd.DataFrame, Dict]:
    """GET /api/secured/stats/fantasy/game — one row per player-game — fantasy scoring by game. Requires ``position_group``.

    Endpoint: ``GET https://pro.nfl.com/api/secured/stats/fantasy/game``
    Example URL: https://pro.nfl.com/api/secured/stats/fantasy/game?season=2024&seasonType=REG&positionGroup=QB

    Args:
        season: season query parameter.
        season_type: seasonType query parameter.
        limit: limit query parameter.
        offset: offset query parameter.
        nfl_id: nflId query parameter.
        position_group: positionGroup query parameter.
        sort_key: sortKey query parameter.
        sort_value: sortValue query parameter.
        headers: optional pre-minted auth headers dict from ``nflpro_headers_gen()`` to reuse across calls (obtaining a token costs a browser login). A token is resolved when omitted; note an anonymous/client-credentials token is NOT usable here -- every ``/api/secured/*`` route 401s without an active NFL+ plan.
        return_parsed: parse the payload through parse_nfl_pro_stats -> polars DataFrame (default True). Pass return_parsed=False for the raw JSON Dict.
        return_as_pandas: with return_parsed, return a pandas DataFrame instead of polars.
        **kwargs: Forwarded to the underlying HTTP getter.

    Returns:
        A polars/pandas DataFrame by default; the raw JSON ``Dict`` when ``return_parsed=False``.

    Raises:
        NFLProAuthError: No user-bound NFL Pro token could be resolved (pass ``token=`` or ``email=``/``password=``, or set ``NFLPRO_TOKEN``, or ``NFLPRO_EMAIL``/``NFLPRO_PW``), or the resolved token carries no active NFL_PLUS_* plan.
        ValueError: pro.nfl.com returned HTTP 200 with an empty body -- how it signals rejected query params, since it sends no error envelope.

    Example:
        Quick start::

            from sportsdataverse.nfl import nfl_pro_fantasy_game
            nfl_pro_fantasy_game(season=2024, season_type='REG', position_group='QB')
    """
    _caller_params = kwargs.pop("params", None) or {}
    _params = {
        "season": season,
        "seasonType": season_type,
        "limit": limit,
        "offset": offset,
        "nflId": nfl_id,
        "positionGroup": position_group,
        "sortKey": sort_key,
        "sortValue": sort_value,
    }
    _params.update(_caller_params)
    raw = _get(
        "https://pro.nfl.com/api/secured/stats/fantasy/game",
        params=_params,
        headers=headers,
        **kwargs,
    )
    if return_parsed:
        return parse_nfl_pro_stats(raw, return_as_pandas=return_as_pandas)
    return raw
