# GENERATED by tools/codegen/generate.py -- DO NOT EDIT.
# Source: tools/codegen/endpoints/sleeper.yaml
"""sleeper wrappers (host https://api.sleeper.app/v1). Generated."""

from __future__ import annotations

from typing import TYPE_CHECKING, Dict, List, Optional, Union  # noqa: F401

from sportsdataverse._codegen_runtime import _get
from sportsdataverse.nfl.sleeper_parsers import parse_sleeper

if TYPE_CHECKING:  # pragma: no cover -- annotation-only imports (PEP 563 defers eval)
    import pandas as pd
    import polars as pl

__all__ = [
    "sleeper_draft",
    "sleeper_draft_picks",
    "sleeper_drafts",
    "sleeper_league",
    "sleeper_matchups",
    "sleeper_players",
    "sleeper_rosters",
    "sleeper_state",
    "sleeper_traded_picks",
    "sleeper_transactions",
    "sleeper_trending_adds",
    "sleeper_user",
    "sleeper_user_leagues",
    "sleeper_users",
    "sleeper_winners_bracket",
]


def sleeper_draft(
    draft_id: str,
    *,
    return_parsed: bool = True,
    return_as_pandas: bool = False,
    **kwargs,
) -> Union[pl.DataFrame, pd.DataFrame, Dict]:
    """A draft

    Endpoint: ``GET https://api.sleeper.app/v1/draft/{draft_id}``
    Example URL: https://api.sleeper.app/v1/draft/257270643320426496

    Args:
        draft_id: draft_id path parameter.
        return_parsed: parse the payload through parse_sleeper -> polars DataFrame (default True). Pass return_parsed=False for the raw JSON Dict.
        return_as_pandas: with return_parsed, return a pandas DataFrame instead of polars.
        **kwargs: Forwarded to the underlying HTTP getter.

    Returns:
        A polars/pandas DataFrame by default; the raw JSON ``Dict`` when ``return_parsed=False``.

    Raises:
        sportsdataverse.errors.NoDataError: the Sleeper API returned 404 (unknown user, league or draft id).
        ValueError: The host answered 400 / 422 -- the request is wrong; retrying cannot help.
        AssetFetchError: The fetch failed (a non-2xx answer or a connection failure after retries, e.g. 401/403/429/5xx, or an empty or unreadable 200 body) -- the answer is unknown, not empty.

    Example:
        Quick start::

            from sportsdataverse.nfl import sleeper_draft
            sleeper_draft(draft_id='257270643320426496')

        See Also:
            * `Sleeper API docs`_ - official route reference (keyless, read-only, ~1000 req/min; fetch /players/nfl at most once a day)

        .. _Sleeper API docs: https://docs.sleeper.com/
    """
    _caller_params = kwargs.pop("params", None) or {}
    _params = {}
    _params.update(_caller_params)
    raw = _get(
        f"https://api.sleeper.app/v1/draft/{draft_id}",
        params=_params,
        **kwargs,
    )
    if return_parsed:
        return parse_sleeper(raw, return_as_pandas=return_as_pandas)
    return raw


def sleeper_draft_picks(
    draft_id: str,
    *,
    return_parsed: bool = True,
    return_as_pandas: bool = False,
    **kwargs,
) -> Union[pl.DataFrame, pd.DataFrame, Dict]:
    """Picks of a draft

    Endpoint: ``GET https://api.sleeper.app/v1/draft/{draft_id}/picks``
    Example URL: https://api.sleeper.app/v1/draft/257270643320426496/picks

    Args:
        draft_id: draft_id path parameter.
        return_parsed: parse the payload through parse_sleeper -> polars DataFrame (default True). Pass return_parsed=False for the raw JSON Dict.
        return_as_pandas: with return_parsed, return a pandas DataFrame instead of polars.
        **kwargs: Forwarded to the underlying HTTP getter.

    Returns:
        A polars/pandas DataFrame by default; the raw JSON ``Dict`` when ``return_parsed=False``.

    Raises:
        sportsdataverse.errors.NoDataError: the Sleeper API returned 404 (unknown user, league or draft id).
        ValueError: The host answered 400 / 422 -- the request is wrong; retrying cannot help.
        AssetFetchError: The fetch failed (a non-2xx answer or a connection failure after retries, e.g. 401/403/429/5xx, or an empty or unreadable 200 body) -- the answer is unknown, not empty.

    Example:
        Quick start::

            from sportsdataverse.nfl import sleeper_draft_picks
            sleeper_draft_picks(draft_id='257270643320426496')

        See Also:
            * `Sleeper API docs`_ - official route reference (keyless, read-only, ~1000 req/min; fetch /players/nfl at most once a day)

        .. _Sleeper API docs: https://docs.sleeper.com/
    """
    _caller_params = kwargs.pop("params", None) or {}
    _params = {}
    _params.update(_caller_params)
    raw = _get(
        f"https://api.sleeper.app/v1/draft/{draft_id}/picks",
        params=_params,
        **kwargs,
    )
    if return_parsed:
        return parse_sleeper(raw, return_as_pandas=return_as_pandas)
    return raw


def sleeper_drafts(
    league_id: str,
    *,
    return_parsed: bool = True,
    return_as_pandas: bool = False,
    **kwargs,
) -> Union[pl.DataFrame, pd.DataFrame, Dict]:
    """Drafts of a league

    Endpoint: ``GET https://api.sleeper.app/v1/league/{league_id}/drafts``
    Example URL: https://api.sleeper.app/v1/league/289646328504385536/drafts

    Args:
        league_id: league_id path parameter.
        return_parsed: parse the payload through parse_sleeper -> polars DataFrame (default True). Pass return_parsed=False for the raw JSON Dict.
        return_as_pandas: with return_parsed, return a pandas DataFrame instead of polars.
        **kwargs: Forwarded to the underlying HTTP getter.

    Returns:
        A polars/pandas DataFrame by default; the raw JSON ``Dict`` when ``return_parsed=False``.

    Raises:
        sportsdataverse.errors.NoDataError: the Sleeper API returned 404 (unknown user, league or draft id).
        ValueError: The host answered 400 / 422 -- the request is wrong; retrying cannot help.
        AssetFetchError: The fetch failed (a non-2xx answer or a connection failure after retries, e.g. 401/403/429/5xx, or an empty or unreadable 200 body) -- the answer is unknown, not empty.

    Example:
        Quick start::

            from sportsdataverse.nfl import sleeper_drafts
            sleeper_drafts(league_id='289646328504385536')

        See Also:
            * `Sleeper API docs`_ - official route reference (keyless, read-only, ~1000 req/min; fetch /players/nfl at most once a day)

        .. _Sleeper API docs: https://docs.sleeper.com/
    """
    _caller_params = kwargs.pop("params", None) or {}
    _params = {}
    _params.update(_caller_params)
    raw = _get(
        f"https://api.sleeper.app/v1/league/{league_id}/drafts",
        params=_params,
        **kwargs,
    )
    if return_parsed:
        return parse_sleeper(raw, return_as_pandas=return_as_pandas)
    return raw


def sleeper_league(
    league_id: str,
    *,
    return_parsed: bool = True,
    return_as_pandas: bool = False,
    **kwargs,
) -> Union[pl.DataFrame, pd.DataFrame, Dict]:
    """A league

    Endpoint: ``GET https://api.sleeper.app/v1/league/{league_id}``
    Example URL: https://api.sleeper.app/v1/league/289646328504385536

    Args:
        league_id: league_id path parameter.
        return_parsed: parse the payload through parse_sleeper -> polars DataFrame (default True). Pass return_parsed=False for the raw JSON Dict.
        return_as_pandas: with return_parsed, return a pandas DataFrame instead of polars.
        **kwargs: Forwarded to the underlying HTTP getter.

    Returns:
        A polars/pandas DataFrame by default; the raw JSON ``Dict`` when ``return_parsed=False``.

    Raises:
        sportsdataverse.errors.NoDataError: the Sleeper API returned 404 (unknown user, league or draft id).
        ValueError: The host answered 400 / 422 -- the request is wrong; retrying cannot help.
        AssetFetchError: The fetch failed (a non-2xx answer or a connection failure after retries, e.g. 401/403/429/5xx, or an empty or unreadable 200 body) -- the answer is unknown, not empty.

    Example:
        Quick start::

            from sportsdataverse.nfl import sleeper_league
            sleeper_league(league_id='289646328504385536')

        See Also:
            * `Sleeper API docs`_ - official route reference (keyless, read-only, ~1000 req/min; fetch /players/nfl at most once a day)

        .. _Sleeper API docs: https://docs.sleeper.com/
    """
    _caller_params = kwargs.pop("params", None) or {}
    _params = {}
    _params.update(_caller_params)
    raw = _get(
        f"https://api.sleeper.app/v1/league/{league_id}",
        params=_params,
        **kwargs,
    )
    if return_parsed:
        return parse_sleeper(raw, return_as_pandas=return_as_pandas)
    return raw


def sleeper_matchups(
    league_id: str,
    week: str,
    *,
    return_parsed: bool = True,
    return_as_pandas: bool = False,
    **kwargs,
) -> Union[pl.DataFrame, pd.DataFrame, Dict]:
    """Matchups for a week

    Endpoint: ``GET https://api.sleeper.app/v1/league/{league_id}/matchups/{week}``
    Example URL: https://api.sleeper.app/v1/league/289646328504385536/matchups/1

    Args:
        league_id: league_id path parameter.
        week: week path parameter.
        return_parsed: parse the payload through parse_sleeper -> polars DataFrame (default True). Pass return_parsed=False for the raw JSON Dict.
        return_as_pandas: with return_parsed, return a pandas DataFrame instead of polars.
        **kwargs: Forwarded to the underlying HTTP getter.

    Returns:
        A polars/pandas DataFrame by default; the raw JSON ``Dict`` when ``return_parsed=False``.

    Raises:
        sportsdataverse.errors.NoDataError: the Sleeper API returned 404 (unknown user, league or draft id).
        ValueError: The host answered 400 / 422 -- the request is wrong; retrying cannot help.
        AssetFetchError: The fetch failed (a non-2xx answer or a connection failure after retries, e.g. 401/403/429/5xx, or an empty or unreadable 200 body) -- the answer is unknown, not empty.

    Example:
        Quick start::

            from sportsdataverse.nfl import sleeper_matchups
            sleeper_matchups(league_id='289646328504385536', week='1')

        See Also:
            * `Sleeper API docs`_ - official route reference (keyless, read-only, ~1000 req/min; fetch /players/nfl at most once a day)

        .. _Sleeper API docs: https://docs.sleeper.com/
    """
    _caller_params = kwargs.pop("params", None) or {}
    _params = {}
    _params.update(_caller_params)
    raw = _get(
        f"https://api.sleeper.app/v1/league/{league_id}/matchups/{week}",
        params=_params,
        **kwargs,
    )
    if return_parsed:
        return parse_sleeper(raw, return_as_pandas=return_as_pandas)
    return raw


def sleeper_players(
    *,
    return_parsed: bool = True,
    return_as_pandas: bool = False,
    **kwargs,
) -> Union[pl.DataFrame, pd.DataFrame, Dict]:
    """All NFL players (large; fetch at most once per day)

    Endpoint: ``GET https://api.sleeper.app/v1/players/nfl``
    Example URL: https://api.sleeper.app/v1/players/nfl

    Args:
        return_parsed: parse the payload through parse_sleeper -> polars DataFrame (default True). Pass return_parsed=False for the raw JSON Dict.
        return_as_pandas: with return_parsed, return a pandas DataFrame instead of polars.
        **kwargs: Forwarded to the underlying HTTP getter.

    Returns:
        A polars/pandas DataFrame by default; the raw JSON ``Dict`` when ``return_parsed=False``.

    Raises:
        sportsdataverse.errors.NoDataError: the Sleeper API returned 404 (unknown user, league or draft id).
        ValueError: The host answered 400 / 422 -- the request is wrong; retrying cannot help.
        AssetFetchError: The fetch failed (a non-2xx answer or a connection failure after retries, e.g. 401/403/429/5xx, or an empty or unreadable 200 body) -- the answer is unknown, not empty.

    Example:
        Quick start::

            from sportsdataverse.nfl import sleeper_players
            sleeper_players()

        See Also:
            * `Sleeper API docs`_ - official route reference (keyless, read-only, ~1000 req/min; fetch /players/nfl at most once a day)

        .. _Sleeper API docs: https://docs.sleeper.com/
    """
    _caller_params = kwargs.pop("params", None) or {}
    _params = {}
    _params.update(_caller_params)
    raw = _get(
        "https://api.sleeper.app/v1/players/nfl",
        params=_params,
        **kwargs,
    )
    if return_parsed:
        return parse_sleeper(raw, return_as_pandas=return_as_pandas)
    return raw


def sleeper_rosters(
    league_id: str,
    *,
    return_parsed: bool = True,
    return_as_pandas: bool = False,
    **kwargs,
) -> Union[pl.DataFrame, pd.DataFrame, Dict]:
    """Rosters in a league

    Endpoint: ``GET https://api.sleeper.app/v1/league/{league_id}/rosters``
    Example URL: https://api.sleeper.app/v1/league/289646328504385536/rosters

    Args:
        league_id: league_id path parameter.
        return_parsed: parse the payload through parse_sleeper -> polars DataFrame (default True). Pass return_parsed=False for the raw JSON Dict.
        return_as_pandas: with return_parsed, return a pandas DataFrame instead of polars.
        **kwargs: Forwarded to the underlying HTTP getter.

    Returns:
        A polars/pandas DataFrame by default; the raw JSON ``Dict`` when ``return_parsed=False``.

    Raises:
        sportsdataverse.errors.NoDataError: the Sleeper API returned 404 (unknown user, league or draft id).
        ValueError: The host answered 400 / 422 -- the request is wrong; retrying cannot help.
        AssetFetchError: The fetch failed (a non-2xx answer or a connection failure after retries, e.g. 401/403/429/5xx, or an empty or unreadable 200 body) -- the answer is unknown, not empty.

    Example:
        Quick start::

            from sportsdataverse.nfl import sleeper_rosters
            sleeper_rosters(league_id='289646328504385536')

        See Also:
            * `Sleeper API docs`_ - official route reference (keyless, read-only, ~1000 req/min; fetch /players/nfl at most once a day)

        .. _Sleeper API docs: https://docs.sleeper.com/
    """
    _caller_params = kwargs.pop("params", None) or {}
    _params = {}
    _params.update(_caller_params)
    raw = _get(
        f"https://api.sleeper.app/v1/league/{league_id}/rosters",
        params=_params,
        **kwargs,
    )
    if return_parsed:
        return parse_sleeper(raw, return_as_pandas=return_as_pandas)
    return raw


def sleeper_state(
    *,
    return_parsed: bool = True,
    return_as_pandas: bool = False,
    **kwargs,
) -> Union[pl.DataFrame, pd.DataFrame, Dict]:
    """Current NFL week and season state

    Endpoint: ``GET https://api.sleeper.app/v1/state/nfl``
    Example URL: https://api.sleeper.app/v1/state/nfl

    Args:
        return_parsed: parse the payload through parse_sleeper -> polars DataFrame (default True). Pass return_parsed=False for the raw JSON Dict.
        return_as_pandas: with return_parsed, return a pandas DataFrame instead of polars.
        **kwargs: Forwarded to the underlying HTTP getter.

    Returns:
        A polars/pandas DataFrame by default; the raw JSON ``Dict`` when ``return_parsed=False``.

    Raises:
        sportsdataverse.errors.NoDataError: the Sleeper API returned 404 (unknown user, league or draft id).
        ValueError: The host answered 400 / 422 -- the request is wrong; retrying cannot help.
        AssetFetchError: The fetch failed (a non-2xx answer or a connection failure after retries, e.g. 401/403/429/5xx, or an empty or unreadable 200 body) -- the answer is unknown, not empty.

    Example:
        Quick start::

            from sportsdataverse.nfl import sleeper_state
            sleeper_state()

        See Also:
            * `Sleeper API docs`_ - official route reference (keyless, read-only, ~1000 req/min; fetch /players/nfl at most once a day)

        .. _Sleeper API docs: https://docs.sleeper.com/
    """
    _caller_params = kwargs.pop("params", None) or {}
    _params = {}
    _params.update(_caller_params)
    raw = _get(
        "https://api.sleeper.app/v1/state/nfl",
        params=_params,
        **kwargs,
    )
    if return_parsed:
        return parse_sleeper(raw, return_as_pandas=return_as_pandas)
    return raw


def sleeper_traded_picks(
    league_id: str,
    *,
    return_parsed: bool = True,
    return_as_pandas: bool = False,
    **kwargs,
) -> Union[pl.DataFrame, pd.DataFrame, Dict]:
    """Traded draft picks

    Endpoint: ``GET https://api.sleeper.app/v1/league/{league_id}/traded_picks``
    Example URL: https://api.sleeper.app/v1/league/289646328504385536/traded_picks

    Args:
        league_id: league_id path parameter.
        return_parsed: parse the payload through parse_sleeper -> polars DataFrame (default True). Pass return_parsed=False for the raw JSON Dict.
        return_as_pandas: with return_parsed, return a pandas DataFrame instead of polars.
        **kwargs: Forwarded to the underlying HTTP getter.

    Returns:
        A polars/pandas DataFrame by default; the raw JSON ``Dict`` when ``return_parsed=False``.

    Raises:
        sportsdataverse.errors.NoDataError: the Sleeper API returned 404 (unknown user, league or draft id).
        ValueError: The host answered 400 / 422 -- the request is wrong; retrying cannot help.
        AssetFetchError: The fetch failed (a non-2xx answer or a connection failure after retries, e.g. 401/403/429/5xx, or an empty or unreadable 200 body) -- the answer is unknown, not empty.

    Example:
        Quick start::

            from sportsdataverse.nfl import sleeper_traded_picks
            sleeper_traded_picks(league_id='289646328504385536')

        See Also:
            * `Sleeper API docs`_ - official route reference (keyless, read-only, ~1000 req/min; fetch /players/nfl at most once a day)

        .. _Sleeper API docs: https://docs.sleeper.com/
    """
    _caller_params = kwargs.pop("params", None) or {}
    _params = {}
    _params.update(_caller_params)
    raw = _get(
        f"https://api.sleeper.app/v1/league/{league_id}/traded_picks",
        params=_params,
        **kwargs,
    )
    if return_parsed:
        return parse_sleeper(raw, return_as_pandas=return_as_pandas)
    return raw


def sleeper_transactions(
    league_id: str,
    week: str,
    *,
    return_parsed: bool = True,
    return_as_pandas: bool = False,
    **kwargs,
) -> Union[pl.DataFrame, pd.DataFrame, Dict]:
    """Transactions for a week

    Endpoint: ``GET https://api.sleeper.app/v1/league/{league_id}/transactions/{week}``
    Example URL: https://api.sleeper.app/v1/league/289646328504385536/transactions/1

    Args:
        league_id: league_id path parameter.
        week: week path parameter.
        return_parsed: parse the payload through parse_sleeper -> polars DataFrame (default True). Pass return_parsed=False for the raw JSON Dict.
        return_as_pandas: with return_parsed, return a pandas DataFrame instead of polars.
        **kwargs: Forwarded to the underlying HTTP getter.

    Returns:
        A polars/pandas DataFrame by default; the raw JSON ``Dict`` when ``return_parsed=False``.

    Raises:
        sportsdataverse.errors.NoDataError: the Sleeper API returned 404 (unknown user, league or draft id).
        ValueError: The host answered 400 / 422 -- the request is wrong; retrying cannot help.
        AssetFetchError: The fetch failed (a non-2xx answer or a connection failure after retries, e.g. 401/403/429/5xx, or an empty or unreadable 200 body) -- the answer is unknown, not empty.

    Example:
        Quick start::

            from sportsdataverse.nfl import sleeper_transactions
            sleeper_transactions(league_id='289646328504385536', week='1')

        See Also:
            * `Sleeper API docs`_ - official route reference (keyless, read-only, ~1000 req/min; fetch /players/nfl at most once a day)

        .. _Sleeper API docs: https://docs.sleeper.com/
    """
    _caller_params = kwargs.pop("params", None) or {}
    _params = {}
    _params.update(_caller_params)
    raw = _get(
        f"https://api.sleeper.app/v1/league/{league_id}/transactions/{week}",
        params=_params,
        **kwargs,
    )
    if return_parsed:
        return parse_sleeper(raw, return_as_pandas=return_as_pandas)
    return raw


def sleeper_trending_adds(
    lookback_hours: Optional[str] = None,
    limit: Optional[str] = None,
    *,
    return_parsed: bool = True,
    return_as_pandas: bool = False,
    **kwargs,
) -> Union[pl.DataFrame, pd.DataFrame, Dict]:
    """Trending adds (lookback_hours, limit)

    Endpoint: ``GET https://api.sleeper.app/v1/players/nfl/trending/add``
    Example URL: https://api.sleeper.app/v1/players/nfl/trending/add

    Args:
        lookback_hours: Hours to look back (default 24).
        limit: Number of players (default 25).
        return_parsed: parse the payload through parse_sleeper -> polars DataFrame (default True). Pass return_parsed=False for the raw JSON Dict.
        return_as_pandas: with return_parsed, return a pandas DataFrame instead of polars.
        **kwargs: Forwarded to the underlying HTTP getter.

    Returns:
        A polars/pandas DataFrame by default; the raw JSON ``Dict`` when ``return_parsed=False``.

    Raises:
        sportsdataverse.errors.NoDataError: the Sleeper API returned 404 (unknown user, league or draft id).
        ValueError: The host answered 400 / 422 -- the request is wrong; retrying cannot help.
        AssetFetchError: The fetch failed (a non-2xx answer or a connection failure after retries, e.g. 401/403/429/5xx, or an empty or unreadable 200 body) -- the answer is unknown, not empty.

    Example:
        Quick start::

            from sportsdataverse.nfl import sleeper_trending_adds
            sleeper_trending_adds()

        See Also:
            * `Sleeper API docs`_ - official route reference (keyless, read-only, ~1000 req/min; fetch /players/nfl at most once a day)

        .. _Sleeper API docs: https://docs.sleeper.com/
    """
    _caller_params = kwargs.pop("params", None) or {}
    _params = {
        "lookback_hours": lookback_hours,
        "limit": limit,
    }
    _params.update(_caller_params)
    raw = _get(
        "https://api.sleeper.app/v1/players/nfl/trending/add",
        params=_params,
        **kwargs,
    )
    if return_parsed:
        return parse_sleeper(raw, return_as_pandas=return_as_pandas)
    return raw


def sleeper_user(
    username: str,
    *,
    return_parsed: bool = True,
    return_as_pandas: bool = False,
    **kwargs,
) -> Union[pl.DataFrame, pd.DataFrame, Dict]:
    """Look up a user by username or id

    Endpoint: ``GET https://api.sleeper.app/v1/user/{username}``
    Example URL: https://api.sleeper.app/v1/user/457511950237696

    Args:
        username: username path parameter.
        return_parsed: parse the payload through parse_sleeper -> polars DataFrame (default True). Pass return_parsed=False for the raw JSON Dict.
        return_as_pandas: with return_parsed, return a pandas DataFrame instead of polars.
        **kwargs: Forwarded to the underlying HTTP getter.

    Returns:
        A polars/pandas DataFrame by default; the raw JSON ``Dict`` when ``return_parsed=False``.

    Raises:
        sportsdataverse.errors.NoDataError: the Sleeper API returned 404 (unknown user, league or draft id).
        ValueError: The host answered 400 / 422 -- the request is wrong; retrying cannot help.
        AssetFetchError: The fetch failed (a non-2xx answer or a connection failure after retries, e.g. 401/403/429/5xx, or an empty or unreadable 200 body) -- the answer is unknown, not empty.

    Example:
        Quick start::

            from sportsdataverse.nfl import sleeper_user
            sleeper_user(username='457511950237696')

        See Also:
            * `Sleeper API docs`_ - official route reference (keyless, read-only, ~1000 req/min; fetch /players/nfl at most once a day)

        .. _Sleeper API docs: https://docs.sleeper.com/
    """
    _caller_params = kwargs.pop("params", None) or {}
    _params = {}
    _params.update(_caller_params)
    raw = _get(
        f"https://api.sleeper.app/v1/user/{username}",
        params=_params,
        **kwargs,
    )
    if return_parsed:
        return parse_sleeper(raw, return_as_pandas=return_as_pandas)
    return raw


def sleeper_user_leagues(
    user_id: str,
    season: str,
    *,
    return_parsed: bool = True,
    return_as_pandas: bool = False,
    **kwargs,
) -> Union[pl.DataFrame, pd.DataFrame, Dict]:
    """Leagues a user is in for a season

    Endpoint: ``GET https://api.sleeper.app/v1/user/{user_id}/leagues/nfl/{season}``
    Example URL: https://api.sleeper.app/v1/user/457511950237696/leagues/nfl/2018

    Args:
        user_id: user_id path parameter.
        season: season path parameter.
        return_parsed: parse the payload through parse_sleeper -> polars DataFrame (default True). Pass return_parsed=False for the raw JSON Dict.
        return_as_pandas: with return_parsed, return a pandas DataFrame instead of polars.
        **kwargs: Forwarded to the underlying HTTP getter.

    Returns:
        A polars/pandas DataFrame by default; the raw JSON ``Dict`` when ``return_parsed=False``.

    Raises:
        sportsdataverse.errors.NoDataError: the Sleeper API returned 404 (unknown user, league or draft id).
        ValueError: The host answered 400 / 422 -- the request is wrong; retrying cannot help.
        AssetFetchError: The fetch failed (a non-2xx answer or a connection failure after retries, e.g. 401/403/429/5xx, or an empty or unreadable 200 body) -- the answer is unknown, not empty.

    Example:
        Quick start::

            from sportsdataverse.nfl import sleeper_user_leagues
            sleeper_user_leagues(season='2018', user_id='457511950237696')

        See Also:
            * `Sleeper API docs`_ - official route reference (keyless, read-only, ~1000 req/min; fetch /players/nfl at most once a day)

        .. _Sleeper API docs: https://docs.sleeper.com/
    """
    _caller_params = kwargs.pop("params", None) or {}
    _params = {}
    _params.update(_caller_params)
    raw = _get(
        f"https://api.sleeper.app/v1/user/{user_id}/leagues/nfl/{season}",
        params=_params,
        **kwargs,
    )
    if return_parsed:
        return parse_sleeper(raw, return_as_pandas=return_as_pandas)
    return raw


def sleeper_users(
    league_id: str,
    *,
    return_parsed: bool = True,
    return_as_pandas: bool = False,
    **kwargs,
) -> Union[pl.DataFrame, pd.DataFrame, Dict]:
    """Users in a league

    Endpoint: ``GET https://api.sleeper.app/v1/league/{league_id}/users``
    Example URL: https://api.sleeper.app/v1/league/289646328504385536/users

    Args:
        league_id: league_id path parameter.
        return_parsed: parse the payload through parse_sleeper -> polars DataFrame (default True). Pass return_parsed=False for the raw JSON Dict.
        return_as_pandas: with return_parsed, return a pandas DataFrame instead of polars.
        **kwargs: Forwarded to the underlying HTTP getter.

    Returns:
        A polars/pandas DataFrame by default; the raw JSON ``Dict`` when ``return_parsed=False``.

    Raises:
        sportsdataverse.errors.NoDataError: the Sleeper API returned 404 (unknown user, league or draft id).
        ValueError: The host answered 400 / 422 -- the request is wrong; retrying cannot help.
        AssetFetchError: The fetch failed (a non-2xx answer or a connection failure after retries, e.g. 401/403/429/5xx, or an empty or unreadable 200 body) -- the answer is unknown, not empty.

    Example:
        Quick start::

            from sportsdataverse.nfl import sleeper_users
            sleeper_users(league_id='289646328504385536')

        See Also:
            * `Sleeper API docs`_ - official route reference (keyless, read-only, ~1000 req/min; fetch /players/nfl at most once a day)

        .. _Sleeper API docs: https://docs.sleeper.com/
    """
    _caller_params = kwargs.pop("params", None) or {}
    _params = {}
    _params.update(_caller_params)
    raw = _get(
        f"https://api.sleeper.app/v1/league/{league_id}/users",
        params=_params,
        **kwargs,
    )
    if return_parsed:
        return parse_sleeper(raw, return_as_pandas=return_as_pandas)
    return raw


def sleeper_winners_bracket(
    league_id: str,
    *,
    return_parsed: bool = True,
    return_as_pandas: bool = False,
    **kwargs,
) -> Union[pl.DataFrame, pd.DataFrame, Dict]:
    """Playoff bracket

    Endpoint: ``GET https://api.sleeper.app/v1/league/{league_id}/winners_bracket``
    Example URL: https://api.sleeper.app/v1/league/289646328504385536/winners_bracket

    Args:
        league_id: league_id path parameter.
        return_parsed: parse the payload through parse_sleeper -> polars DataFrame (default True). Pass return_parsed=False for the raw JSON Dict.
        return_as_pandas: with return_parsed, return a pandas DataFrame instead of polars.
        **kwargs: Forwarded to the underlying HTTP getter.

    Returns:
        A polars/pandas DataFrame by default; the raw JSON ``Dict`` when ``return_parsed=False``.

    Raises:
        sportsdataverse.errors.NoDataError: the Sleeper API returned 404 (unknown user, league or draft id).
        ValueError: The host answered 400 / 422 -- the request is wrong; retrying cannot help.
        AssetFetchError: The fetch failed (a non-2xx answer or a connection failure after retries, e.g. 401/403/429/5xx, or an empty or unreadable 200 body) -- the answer is unknown, not empty.

    Example:
        Quick start::

            from sportsdataverse.nfl import sleeper_winners_bracket
            sleeper_winners_bracket(league_id='289646328504385536')

        See Also:
            * `Sleeper API docs`_ - official route reference (keyless, read-only, ~1000 req/min; fetch /players/nfl at most once a day)

        .. _Sleeper API docs: https://docs.sleeper.com/
    """
    _caller_params = kwargs.pop("params", None) or {}
    _params = {}
    _params.update(_caller_params)
    raw = _get(
        f"https://api.sleeper.app/v1/league/{league_id}/winners_bracket",
        params=_params,
        **kwargs,
    )
    if return_parsed:
        return parse_sleeper(raw, return_as_pandas=return_as_pandas)
    return raw
