# GENERATED by tools/codegen/generate.py -- DO NOT EDIT.
# Source: tools/codegen/endpoints/on3.yaml
"""on3 wrappers (host https://www.on3.com). Generated."""

from __future__ import annotations

from typing import TYPE_CHECKING, Dict, List, Optional, Union  # noqa: F401

from sportsdataverse.cfb.on3_runtime import _get
from sportsdataverse.cfb.on3_parsers import parse_on3_rankings, parse_on3_team_rankings

if TYPE_CHECKING:  # pragma: no cover -- annotation-only imports (PEP 563 defers eval)
    import pandas as pd
    import polars as pl

__all__ = [
    "on3_player_rankings",
    "on3_industry_player_rankings",
    "on3_team_rankings",
    "on3_industry_team_rankings",
]


def on3_player_rankings(
    year: Union[int, str],
    sport_slug: str = "football",
    page: Optional[int] = None,
    *,
    return_parsed: bool = True,
    return_as_pandas: bool = False,
    **kwargs,
) -> Union[pl.DataFrame, pd.DataFrame, Dict]:
    """On3 player rankings for a recruiting class year — On3's own ratings (rankingType=player).

    Endpoint: ``GET https://www.on3.com/rivals/rankings/player/{sport_slug}/{year}.json``
    Example URL: https://www.on3.com/rivals/rankings/player/football/2026.json

    Args:
        year: year path parameter.
        sport_slug: sport_slug path parameter.
        page: page query parameter.
        return_parsed: parse the payload through parse_on3_rankings -> polars DataFrame (default True). Pass return_parsed=False for the raw JSON Dict.
        return_as_pandas: with return_parsed, return a pandas DataFrame instead of polars.

    Returns:
        A polars/pandas DataFrame by default; the raw JSON ``Dict`` when ``return_parsed=False``.

    Example:
        Quick start::

            on3_player_rankings(year=2026, sport_slug='football')
    """
    raw = _get(
        f"https://www.on3.com/rivals/rankings/player/{sport_slug}/{year}.json",
        params={
            "page": page,
            **{_k: _v for _k, _v in kwargs.items() if _v is not None},
        },
    )
    if return_parsed:
        return parse_on3_rankings(raw, return_as_pandas=return_as_pandas)
    return raw


def on3_industry_player_rankings(
    year: Union[int, str],
    sport_slug: str = "football",
    page: Optional[int] = None,
    *,
    return_parsed: bool = True,
    return_as_pandas: bool = False,
    **kwargs,
) -> Union[pl.DataFrame, pd.DataFrame, Dict]:
    """On3 Industry Comparison player rankings (consensus across On3/Rivals/247/ESPN; rankingType=industry-player).

    Endpoint: ``GET https://www.on3.com/rivals/rankings/industry-player/{sport_slug}/{year}.json``
    Example URL: https://www.on3.com/rivals/rankings/industry-player/football/2026.json

    Args:
        year: year path parameter.
        sport_slug: sport_slug path parameter.
        page: page query parameter.
        return_parsed: parse the payload through parse_on3_rankings -> polars DataFrame (default True). Pass return_parsed=False for the raw JSON Dict.
        return_as_pandas: with return_parsed, return a pandas DataFrame instead of polars.

    Returns:
        A polars/pandas DataFrame by default; the raw JSON ``Dict`` when ``return_parsed=False``.

    Example:
        Quick start::

            on3_industry_player_rankings(year=2026, sport_slug='football')
    """
    raw = _get(
        f"https://www.on3.com/rivals/rankings/industry-player/{sport_slug}/{year}.json",
        params={
            "page": page,
            **{_k: _v for _k, _v in kwargs.items() if _v is not None},
        },
    )
    if return_parsed:
        return parse_on3_rankings(raw, return_as_pandas=return_as_pandas)
    return raw


def on3_team_rankings(
    year: Union[int, str],
    sport_slug: str = "football",
    page: Optional[int] = None,
    *,
    return_parsed: bool = True,
    return_as_pandas: bool = False,
    **kwargs,
) -> Union[pl.DataFrame, pd.DataFrame, Dict]:
    """On3 team recruiting-class rankings for a class year (rankingType=team).

    Endpoint: ``GET https://www.on3.com/rivals/rankings/team/{sport_slug}/{year}.json``
    Example URL: https://www.on3.com/rivals/rankings/team/football/2026.json

    Args:
        year: year path parameter.
        sport_slug: sport_slug path parameter.
        page: page query parameter.
        return_parsed: parse the payload through parse_on3_team_rankings -> polars DataFrame (default True). Pass return_parsed=False for the raw JSON Dict.
        return_as_pandas: with return_parsed, return a pandas DataFrame instead of polars.

    Returns:
        A polars/pandas DataFrame by default; the raw JSON ``Dict`` when ``return_parsed=False``.

    Example:
        Quick start::

            on3_team_rankings(year=2026, sport_slug='football')
    """
    raw = _get(
        f"https://www.on3.com/rivals/rankings/team/{sport_slug}/{year}.json",
        params={
            "page": page,
            **{_k: _v for _k, _v in kwargs.items() if _v is not None},
        },
    )
    if return_parsed:
        return parse_on3_team_rankings(raw, return_as_pandas=return_as_pandas)
    return raw


def on3_industry_team_rankings(
    year: Union[int, str],
    sport_slug: str = "football",
    page: Optional[int] = None,
    *,
    return_parsed: bool = True,
    return_as_pandas: bool = False,
    **kwargs,
) -> Union[pl.DataFrame, pd.DataFrame, Dict]:
    """On3 Industry Comparison team recruiting-class rankings (rankingType=industry-team).

    Endpoint: ``GET https://www.on3.com/rivals/rankings/industry-team/{sport_slug}/{year}.json``
    Example URL: https://www.on3.com/rivals/rankings/industry-team/football/2026.json

    Args:
        year: year path parameter.
        sport_slug: sport_slug path parameter.
        page: page query parameter.
        return_parsed: parse the payload through parse_on3_team_rankings -> polars DataFrame (default True). Pass return_parsed=False for the raw JSON Dict.
        return_as_pandas: with return_parsed, return a pandas DataFrame instead of polars.

    Returns:
        A polars/pandas DataFrame by default; the raw JSON ``Dict`` when ``return_parsed=False``.

    Example:
        Quick start::

            on3_industry_team_rankings(year=2026, sport_slug='football')
    """
    raw = _get(
        f"https://www.on3.com/rivals/rankings/industry-team/{sport_slug}/{year}.json",
        params={
            "page": page,
            **{_k: _v for _k, _v in kwargs.items() if _v is not None},
        },
    )
    if return_parsed:
        return parse_on3_team_rankings(raw, return_as_pandas=return_as_pandas)
    return raw
