# GENERATED by tools/codegen/generate.py -- DO NOT EDIT.
"""DataFrame-by-default mirror of :mod:`sportsdataverse.wbb`.

Every wrapper that supports ``return_parsed=True`` has that as its default
here; pass ``return_parsed=False`` to recover the raw ``Dict``. Wrappers
without a parser (loaders, helpers) pass through unchanged. See
:mod:`sportsdataverse.parsed` for the design.
"""

from __future__ import annotations

from sportsdataverse.wbb import espn_wbb_award as _raw_espn_wbb_award
from sportsdataverse.wbb import espn_wbb_awards as _raw_espn_wbb_awards
from sportsdataverse.wbb import espn_wbb_calendar_offseason as _raw_espn_wbb_calendar_offseason
from sportsdataverse.wbb import espn_wbb_calendar_ondays as _raw_espn_wbb_calendar_ondays
from sportsdataverse.wbb import espn_wbb_calendar_postseason as _raw_espn_wbb_calendar_postseason
from sportsdataverse.wbb import espn_wbb_calendar_regular_season as _raw_espn_wbb_calendar_regular_season
from sportsdataverse.wbb import espn_wbb_coach as _raw_espn_wbb_coach
from sportsdataverse.wbb import espn_wbb_coach_record as _raw_espn_wbb_coach_record
from sportsdataverse.wbb import espn_wbb_coach_season as _raw_espn_wbb_coach_season
from sportsdataverse.wbb import espn_wbb_coaches as _raw_espn_wbb_coaches
from sportsdataverse.wbb import espn_wbb_conferences as _raw_espn_wbb_conferences
from sportsdataverse.wbb import espn_wbb_draft as _raw_espn_wbb_draft
from sportsdataverse.wbb import espn_wbb_franchise as _raw_espn_wbb_franchise
from sportsdataverse.wbb import espn_wbb_franchises as _raw_espn_wbb_franchises
from sportsdataverse.wbb import espn_wbb_game as _raw_espn_wbb_game
from sportsdataverse.wbb import espn_wbb_game_broadcasts as _raw_espn_wbb_game_broadcasts
from sportsdataverse.wbb import espn_wbb_game_competition as _raw_espn_wbb_game_competition
from sportsdataverse.wbb import espn_wbb_game_leaders as _raw_espn_wbb_game_leaders
from sportsdataverse.wbb import espn_wbb_game_odds as _raw_espn_wbb_game_odds
from sportsdataverse.wbb import espn_wbb_game_official_detail as _raw_espn_wbb_game_official_detail
from sportsdataverse.wbb import espn_wbb_game_play as _raw_espn_wbb_game_play
from sportsdataverse.wbb import espn_wbb_game_play_personnel as _raw_espn_wbb_game_play_personnel
from sportsdataverse.wbb import espn_wbb_game_plays as _raw_espn_wbb_game_plays
from sportsdataverse.wbb import espn_wbb_game_powerindex as _raw_espn_wbb_game_powerindex
from sportsdataverse.wbb import espn_wbb_game_predictor as _raw_espn_wbb_game_predictor
from sportsdataverse.wbb import espn_wbb_game_probabilities as _raw_espn_wbb_game_probabilities
from sportsdataverse.wbb import espn_wbb_game_propbets as _raw_espn_wbb_game_propbets
from sportsdataverse.wbb import espn_wbb_game_scoringplays as _raw_espn_wbb_game_scoringplays
from sportsdataverse.wbb import espn_wbb_game_situation as _raw_espn_wbb_game_situation
from sportsdataverse.wbb import espn_wbb_game_status as _raw_espn_wbb_game_status
from sportsdataverse.wbb import espn_wbb_game_team as _raw_espn_wbb_game_team
from sportsdataverse.wbb import espn_wbb_game_team_leaders as _raw_espn_wbb_game_team_leaders
from sportsdataverse.wbb import espn_wbb_game_team_linescores as _raw_espn_wbb_game_team_linescores
from sportsdataverse.wbb import espn_wbb_game_team_record as _raw_espn_wbb_game_team_record
from sportsdataverse.wbb import espn_wbb_game_team_roster as _raw_espn_wbb_game_team_roster
from sportsdataverse.wbb import espn_wbb_game_team_statistics as _raw_espn_wbb_game_team_statistics
from sportsdataverse.wbb import espn_wbb_game_teams as _raw_espn_wbb_game_teams
from sportsdataverse.wbb import espn_wbb_games as _raw_espn_wbb_games
from sportsdataverse.wbb import espn_wbb_injuries as _raw_espn_wbb_injuries
from sportsdataverse.wbb import espn_wbb_leaders as _raw_espn_wbb_leaders
from sportsdataverse.wbb import espn_wbb_leaders_core as _raw_espn_wbb_leaders_core
from sportsdataverse.wbb import espn_wbb_league_notes as _raw_espn_wbb_league_notes
from sportsdataverse.wbb import espn_wbb_league_root as _raw_espn_wbb_league_root
from sportsdataverse.wbb import espn_wbb_news as _raw_espn_wbb_news
from sportsdataverse.wbb import espn_wbb_player_awards as _raw_espn_wbb_player_awards
from sportsdataverse.wbb import espn_wbb_player_bio as _raw_espn_wbb_player_bio
from sportsdataverse.wbb import espn_wbb_player_career_stats as _raw_espn_wbb_player_career_stats
from sportsdataverse.wbb import espn_wbb_player_contracts as _raw_espn_wbb_player_contracts
from sportsdataverse.wbb import espn_wbb_player_core as _raw_espn_wbb_player_core
from sportsdataverse.wbb import espn_wbb_player_eventlog as _raw_espn_wbb_player_eventlog
from sportsdataverse.wbb import espn_wbb_player_gamelog as _raw_espn_wbb_player_gamelog
from sportsdataverse.wbb import espn_wbb_player_info as _raw_espn_wbb_player_info
from sportsdataverse.wbb import espn_wbb_player_injuries as _raw_espn_wbb_player_injuries
from sportsdataverse.wbb import espn_wbb_player_news as _raw_espn_wbb_player_news
from sportsdataverse.wbb import espn_wbb_player_notes as _raw_espn_wbb_player_notes
from sportsdataverse.wbb import espn_wbb_player_overview as _raw_espn_wbb_player_overview
from sportsdataverse.wbb import espn_wbb_player_records as _raw_espn_wbb_player_records
from sportsdataverse.wbb import espn_wbb_player_seasons as _raw_espn_wbb_player_seasons
from sportsdataverse.wbb import espn_wbb_player_splits as _raw_espn_wbb_player_splits
from sportsdataverse.wbb import espn_wbb_player_statisticslog as _raw_espn_wbb_player_statisticslog
from sportsdataverse.wbb import espn_wbb_player_stats_v3 as _raw_espn_wbb_player_stats_v3
from sportsdataverse.wbb import espn_wbb_player_vs_player as _raw_espn_wbb_player_vs_player
from sportsdataverse.wbb import espn_wbb_players_index as _raw_espn_wbb_players_index
from sportsdataverse.wbb import espn_wbb_position as _raw_espn_wbb_position
from sportsdataverse.wbb import espn_wbb_positions as _raw_espn_wbb_positions
from sportsdataverse.wbb import espn_wbb_rankings as _raw_espn_wbb_rankings
from sportsdataverse.wbb import espn_wbb_scoreboard as _raw_espn_wbb_scoreboard
from sportsdataverse.wbb import espn_wbb_season_awards as _raw_espn_wbb_season_awards
from sportsdataverse.wbb import espn_wbb_season_coaches as _raw_espn_wbb_season_coaches
from sportsdataverse.wbb import espn_wbb_season_draft as _raw_espn_wbb_season_draft
from sportsdataverse.wbb import espn_wbb_season_draft_round_picks as _raw_espn_wbb_season_draft_round_picks
from sportsdataverse.wbb import espn_wbb_season_freeagents as _raw_espn_wbb_season_freeagents
from sportsdataverse.wbb import espn_wbb_season_futures as _raw_espn_wbb_season_futures
from sportsdataverse.wbb import espn_wbb_season_group as _raw_espn_wbb_season_group
from sportsdataverse.wbb import espn_wbb_season_group_children as _raw_espn_wbb_season_group_children
from sportsdataverse.wbb import espn_wbb_season_group_teams as _raw_espn_wbb_season_group_teams
from sportsdataverse.wbb import espn_wbb_season_groups as _raw_espn_wbb_season_groups
from sportsdataverse.wbb import espn_wbb_season_info as _raw_espn_wbb_season_info
from sportsdataverse.wbb import espn_wbb_season_players as _raw_espn_wbb_season_players
from sportsdataverse.wbb import espn_wbb_season_pointer as _raw_espn_wbb_season_pointer
from sportsdataverse.wbb import espn_wbb_season_powerindex as _raw_espn_wbb_season_powerindex
from sportsdataverse.wbb import espn_wbb_season_powerindex_leaders as _raw_espn_wbb_season_powerindex_leaders
from sportsdataverse.wbb import espn_wbb_season_recruits as _raw_espn_wbb_season_recruits
from sportsdataverse.wbb import espn_wbb_season_team as _raw_espn_wbb_season_team
from sportsdataverse.wbb import espn_wbb_season_teams as _raw_espn_wbb_season_teams
from sportsdataverse.wbb import espn_wbb_season_type as _raw_espn_wbb_season_type
from sportsdataverse.wbb import espn_wbb_season_type_corrections as _raw_espn_wbb_season_type_corrections
from sportsdataverse.wbb import espn_wbb_season_type_leaders as _raw_espn_wbb_season_type_leaders
from sportsdataverse.wbb import espn_wbb_season_types as _raw_espn_wbb_season_types
from sportsdataverse.wbb import espn_wbb_season_week as _raw_espn_wbb_season_week
from sportsdataverse.wbb import espn_wbb_season_week_games as _raw_espn_wbb_season_week_games
from sportsdataverse.wbb import espn_wbb_season_week_rankings as _raw_espn_wbb_season_week_rankings
from sportsdataverse.wbb import espn_wbb_season_weeks as _raw_espn_wbb_season_weeks
from sportsdataverse.wbb import espn_wbb_seasons as _raw_espn_wbb_seasons
from sportsdataverse.wbb import espn_wbb_standings_core as _raw_espn_wbb_standings_core
from sportsdataverse.wbb import espn_wbb_statistics_league as _raw_espn_wbb_statistics_league
from sportsdataverse.wbb import espn_wbb_summary as _raw_espn_wbb_summary
from sportsdataverse.wbb import espn_wbb_talentpicks as _raw_espn_wbb_talentpicks
from sportsdataverse.wbb import espn_wbb_team as _raw_espn_wbb_team
from sportsdataverse.wbb import espn_wbb_team_core as _raw_espn_wbb_team_core
from sportsdataverse.wbb import espn_wbb_team_depthcharts as _raw_espn_wbb_team_depthcharts
from sportsdataverse.wbb import espn_wbb_team_history as _raw_espn_wbb_team_history
from sportsdataverse.wbb import espn_wbb_team_injuries as _raw_espn_wbb_team_injuries
from sportsdataverse.wbb import espn_wbb_team_leaders as _raw_espn_wbb_team_leaders
from sportsdataverse.wbb import espn_wbb_team_news as _raw_espn_wbb_team_news
from sportsdataverse.wbb import espn_wbb_team_record as _raw_espn_wbb_team_record
from sportsdataverse.wbb import espn_wbb_team_schedule as _raw_espn_wbb_team_schedule
from sportsdataverse.wbb import espn_wbb_team_transactions as _raw_espn_wbb_team_transactions
from sportsdataverse.wbb import espn_wbb_teams_core as _raw_espn_wbb_teams_core
from sportsdataverse.wbb import espn_wbb_teams_site as _raw_espn_wbb_teams_site
from sportsdataverse.wbb import espn_wbb_tournaments as _raw_espn_wbb_tournaments
from sportsdataverse.wbb import espn_wbb_transactions as _raw_espn_wbb_transactions
from sportsdataverse.wbb import espn_wbb_venue as _raw_espn_wbb_venue
from sportsdataverse.wbb import espn_wbb_venues as _raw_espn_wbb_venues
from sportsdataverse.wbb import SeasonNotFoundError as SeasonNotFoundError  # noqa: F401
from sportsdataverse.wbb import download as download  # noqa: F401
from sportsdataverse.wbb import espn_wbb_calendar as espn_wbb_calendar  # noqa: F401
from sportsdataverse.wbb import espn_wbb_game_officials as espn_wbb_game_officials  # noqa: F401
from sportsdataverse.wbb import espn_wbb_game_rosters as espn_wbb_game_rosters  # noqa: F401
from sportsdataverse.wbb import espn_wbb_pbp as espn_wbb_pbp  # noqa: F401
from sportsdataverse.wbb import espn_wbb_player_stats as espn_wbb_player_stats  # noqa: F401
from sportsdataverse.wbb import espn_wbb_schedule as espn_wbb_schedule  # noqa: F401
from sportsdataverse.wbb import espn_wbb_standings as espn_wbb_standings  # noqa: F401
from sportsdataverse.wbb import espn_wbb_team_roster as espn_wbb_team_roster  # noqa: F401
from sportsdataverse.wbb import espn_wbb_team_stats as espn_wbb_team_stats  # noqa: F401
from sportsdataverse.wbb import espn_wbb_teams as espn_wbb_teams  # noqa: F401
from sportsdataverse.wbb import flatten_json_iterative as flatten_json_iterative  # noqa: F401
from sportsdataverse.wbb import helper_wbb_athlete_items as helper_wbb_athlete_items  # noqa: F401
from sportsdataverse.wbb import helper_wbb_game_data as helper_wbb_game_data  # noqa: F401
from sportsdataverse.wbb import helper_wbb_game_items as helper_wbb_game_items  # noqa: F401
from sportsdataverse.wbb import helper_wbb_pbp as helper_wbb_pbp  # noqa: F401
from sportsdataverse.wbb import helper_wbb_pbp_features as helper_wbb_pbp_features  # noqa: F401
from sportsdataverse.wbb import helper_wbb_pickcenter as helper_wbb_pickcenter  # noqa: F401
from sportsdataverse.wbb import helper_wbb_roster_items as helper_wbb_roster_items  # noqa: F401
from sportsdataverse.wbb import helper_wbb_team_items as helper_wbb_team_items  # noqa: F401
from sportsdataverse.wbb import load_wbb_game_rosters as load_wbb_game_rosters  # noqa: F401
from sportsdataverse.wbb import load_wbb_officials as load_wbb_officials  # noqa: F401
from sportsdataverse.wbb import load_wbb_pbp as load_wbb_pbp  # noqa: F401
from sportsdataverse.wbb import load_wbb_player_boxscore as load_wbb_player_boxscore  # noqa: F401
from sportsdataverse.wbb import load_wbb_player_season_stats as load_wbb_player_season_stats  # noqa: F401
from sportsdataverse.wbb import load_wbb_rosters as load_wbb_rosters  # noqa: F401
from sportsdataverse.wbb import load_wbb_schedule as load_wbb_schedule  # noqa: F401
from sportsdataverse.wbb import load_wbb_shots as load_wbb_shots  # noqa: F401
from sportsdataverse.wbb import load_wbb_standings as load_wbb_standings  # noqa: F401
from sportsdataverse.wbb import load_wbb_team_boxscore as load_wbb_team_boxscore  # noqa: F401
from sportsdataverse.wbb import load_wbb_team_season_stats as load_wbb_team_season_stats  # noqa: F401
from sportsdataverse.wbb import most_recent_wbb_season as most_recent_wbb_season  # noqa: F401
from sportsdataverse.wbb import scoreboard_event_parsing as scoreboard_event_parsing  # noqa: F401
from sportsdataverse.wbb import underscore as underscore  # noqa: F401
from sportsdataverse.wbb import wbb_pbp_disk as wbb_pbp_disk  # noqa: F401

__all__ = [
    "SeasonNotFoundError",
    "download",
    "espn_wbb_award",
    "espn_wbb_awards",
    "espn_wbb_calendar",
    "espn_wbb_calendar_offseason",
    "espn_wbb_calendar_ondays",
    "espn_wbb_calendar_postseason",
    "espn_wbb_calendar_regular_season",
    "espn_wbb_coach",
    "espn_wbb_coach_record",
    "espn_wbb_coach_season",
    "espn_wbb_coaches",
    "espn_wbb_conferences",
    "espn_wbb_draft",
    "espn_wbb_franchise",
    "espn_wbb_franchises",
    "espn_wbb_game",
    "espn_wbb_game_broadcasts",
    "espn_wbb_game_competition",
    "espn_wbb_game_leaders",
    "espn_wbb_game_odds",
    "espn_wbb_game_official_detail",
    "espn_wbb_game_officials",
    "espn_wbb_game_play",
    "espn_wbb_game_play_personnel",
    "espn_wbb_game_plays",
    "espn_wbb_game_powerindex",
    "espn_wbb_game_predictor",
    "espn_wbb_game_probabilities",
    "espn_wbb_game_propbets",
    "espn_wbb_game_rosters",
    "espn_wbb_game_scoringplays",
    "espn_wbb_game_situation",
    "espn_wbb_game_status",
    "espn_wbb_game_team",
    "espn_wbb_game_team_leaders",
    "espn_wbb_game_team_linescores",
    "espn_wbb_game_team_record",
    "espn_wbb_game_team_roster",
    "espn_wbb_game_team_statistics",
    "espn_wbb_game_teams",
    "espn_wbb_games",
    "espn_wbb_injuries",
    "espn_wbb_leaders",
    "espn_wbb_leaders_core",
    "espn_wbb_league_notes",
    "espn_wbb_league_root",
    "espn_wbb_news",
    "espn_wbb_pbp",
    "espn_wbb_player_awards",
    "espn_wbb_player_bio",
    "espn_wbb_player_career_stats",
    "espn_wbb_player_contracts",
    "espn_wbb_player_core",
    "espn_wbb_player_eventlog",
    "espn_wbb_player_gamelog",
    "espn_wbb_player_info",
    "espn_wbb_player_injuries",
    "espn_wbb_player_news",
    "espn_wbb_player_notes",
    "espn_wbb_player_overview",
    "espn_wbb_player_records",
    "espn_wbb_player_seasons",
    "espn_wbb_player_splits",
    "espn_wbb_player_statisticslog",
    "espn_wbb_player_stats",
    "espn_wbb_player_stats_v3",
    "espn_wbb_player_vs_player",
    "espn_wbb_players_index",
    "espn_wbb_position",
    "espn_wbb_positions",
    "espn_wbb_rankings",
    "espn_wbb_schedule",
    "espn_wbb_scoreboard",
    "espn_wbb_season_awards",
    "espn_wbb_season_coaches",
    "espn_wbb_season_draft",
    "espn_wbb_season_draft_round_picks",
    "espn_wbb_season_freeagents",
    "espn_wbb_season_futures",
    "espn_wbb_season_group",
    "espn_wbb_season_group_children",
    "espn_wbb_season_group_teams",
    "espn_wbb_season_groups",
    "espn_wbb_season_info",
    "espn_wbb_season_players",
    "espn_wbb_season_pointer",
    "espn_wbb_season_powerindex",
    "espn_wbb_season_powerindex_leaders",
    "espn_wbb_season_recruits",
    "espn_wbb_season_team",
    "espn_wbb_season_teams",
    "espn_wbb_season_type",
    "espn_wbb_season_type_corrections",
    "espn_wbb_season_type_leaders",
    "espn_wbb_season_types",
    "espn_wbb_season_week",
    "espn_wbb_season_week_games",
    "espn_wbb_season_week_rankings",
    "espn_wbb_season_weeks",
    "espn_wbb_seasons",
    "espn_wbb_standings",
    "espn_wbb_standings_core",
    "espn_wbb_statistics_league",
    "espn_wbb_summary",
    "espn_wbb_talentpicks",
    "espn_wbb_team",
    "espn_wbb_team_core",
    "espn_wbb_team_depthcharts",
    "espn_wbb_team_history",
    "espn_wbb_team_injuries",
    "espn_wbb_team_leaders",
    "espn_wbb_team_news",
    "espn_wbb_team_record",
    "espn_wbb_team_roster",
    "espn_wbb_team_schedule",
    "espn_wbb_team_stats",
    "espn_wbb_team_transactions",
    "espn_wbb_teams",
    "espn_wbb_teams_core",
    "espn_wbb_teams_site",
    "espn_wbb_tournaments",
    "espn_wbb_transactions",
    "espn_wbb_venue",
    "espn_wbb_venues",
    "flatten_json_iterative",
    "helper_wbb_athlete_items",
    "helper_wbb_game_data",
    "helper_wbb_game_items",
    "helper_wbb_pbp",
    "helper_wbb_pbp_features",
    "helper_wbb_pickcenter",
    "helper_wbb_roster_items",
    "helper_wbb_team_items",
    "load_wbb_game_rosters",
    "load_wbb_officials",
    "load_wbb_pbp",
    "load_wbb_player_boxscore",
    "load_wbb_player_season_stats",
    "load_wbb_rosters",
    "load_wbb_schedule",
    "load_wbb_shots",
    "load_wbb_standings",
    "load_wbb_team_boxscore",
    "load_wbb_team_season_stats",
    "most_recent_wbb_season",
    "scoreboard_event_parsing",
    "underscore",
    "wbb_pbp_disk",
]


def espn_wbb_award(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_award``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_award` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_award(*args, **kwargs)


def espn_wbb_awards(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_awards``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_awards` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_awards(*args, **kwargs)


def espn_wbb_calendar_offseason(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_calendar_offseason``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_calendar_offseason` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_calendar_offseason(*args, **kwargs)


def espn_wbb_calendar_ondays(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_calendar_ondays``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_calendar_ondays` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_calendar_ondays(*args, **kwargs)


def espn_wbb_calendar_postseason(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_calendar_postseason``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_calendar_postseason` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_calendar_postseason(*args, **kwargs)


def espn_wbb_calendar_regular_season(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_calendar_regular_season``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_calendar_regular_season` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_calendar_regular_season(*args, **kwargs)


def espn_wbb_coach(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_coach``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_coach` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_coach(*args, **kwargs)


def espn_wbb_coach_record(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_coach_record``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_coach_record` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_coach_record(*args, **kwargs)


def espn_wbb_coach_season(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_coach_season``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_coach_season` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_coach_season(*args, **kwargs)


def espn_wbb_coaches(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_coaches``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_coaches` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_coaches(*args, **kwargs)


def espn_wbb_conferences(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_conferences``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_conferences` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_conferences(*args, **kwargs)


def espn_wbb_draft(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_draft``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_draft` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_draft(*args, **kwargs)


def espn_wbb_franchise(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_franchise``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_franchise` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_franchise(*args, **kwargs)


def espn_wbb_franchises(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_franchises``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_franchises` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_franchises(*args, **kwargs)


def espn_wbb_game(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_game``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_game` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_game(*args, **kwargs)


def espn_wbb_game_broadcasts(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_game_broadcasts``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_game_broadcasts` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_game_broadcasts(*args, **kwargs)


def espn_wbb_game_competition(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_game_competition``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_game_competition` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_game_competition(*args, **kwargs)


def espn_wbb_game_leaders(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_game_leaders``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_game_leaders` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_game_leaders(*args, **kwargs)


def espn_wbb_game_odds(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_game_odds``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_game_odds` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_game_odds(*args, **kwargs)


def espn_wbb_game_official_detail(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_game_official_detail``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_game_official_detail` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_game_official_detail(*args, **kwargs)


def espn_wbb_game_play(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_game_play``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_game_play` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_game_play(*args, **kwargs)


def espn_wbb_game_play_personnel(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_game_play_personnel``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_game_play_personnel` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_game_play_personnel(*args, **kwargs)


def espn_wbb_game_plays(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_game_plays``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_game_plays` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_game_plays(*args, **kwargs)


def espn_wbb_game_powerindex(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_game_powerindex``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_game_powerindex` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_game_powerindex(*args, **kwargs)


def espn_wbb_game_predictor(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_game_predictor``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_game_predictor` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_game_predictor(*args, **kwargs)


def espn_wbb_game_probabilities(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_game_probabilities``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_game_probabilities` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_game_probabilities(*args, **kwargs)


def espn_wbb_game_propbets(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_game_propbets``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_game_propbets` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_game_propbets(*args, **kwargs)


def espn_wbb_game_scoringplays(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_game_scoringplays``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_game_scoringplays` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_game_scoringplays(*args, **kwargs)


def espn_wbb_game_situation(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_game_situation``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_game_situation` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_game_situation(*args, **kwargs)


def espn_wbb_game_status(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_game_status``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_game_status` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_game_status(*args, **kwargs)


def espn_wbb_game_team(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_game_team``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_game_team` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_game_team(*args, **kwargs)


def espn_wbb_game_team_leaders(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_game_team_leaders``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_game_team_leaders` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_game_team_leaders(*args, **kwargs)


def espn_wbb_game_team_linescores(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_game_team_linescores``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_game_team_linescores` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_game_team_linescores(*args, **kwargs)


def espn_wbb_game_team_record(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_game_team_record``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_game_team_record` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_game_team_record(*args, **kwargs)


def espn_wbb_game_team_roster(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_game_team_roster``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_game_team_roster` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_game_team_roster(*args, **kwargs)


def espn_wbb_game_team_statistics(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_game_team_statistics``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_game_team_statistics` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_game_team_statistics(*args, **kwargs)


def espn_wbb_game_teams(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_game_teams``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_game_teams` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_game_teams(*args, **kwargs)


def espn_wbb_games(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_games``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_games` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_games(*args, **kwargs)


def espn_wbb_injuries(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_injuries``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_injuries` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_injuries(*args, **kwargs)


def espn_wbb_leaders(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_leaders``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_leaders` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_leaders(*args, **kwargs)


def espn_wbb_leaders_core(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_leaders_core``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_leaders_core` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_leaders_core(*args, **kwargs)


def espn_wbb_league_notes(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_league_notes``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_league_notes` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_league_notes(*args, **kwargs)


def espn_wbb_league_root(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_league_root``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_league_root` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_league_root(*args, **kwargs)


def espn_wbb_news(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_news``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_news` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_news(*args, **kwargs)


def espn_wbb_player_awards(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_player_awards``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_player_awards` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_player_awards(*args, **kwargs)


def espn_wbb_player_bio(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_player_bio``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_player_bio` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_player_bio(*args, **kwargs)


def espn_wbb_player_career_stats(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_player_career_stats``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_player_career_stats` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_player_career_stats(*args, **kwargs)


def espn_wbb_player_contracts(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_player_contracts``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_player_contracts` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_player_contracts(*args, **kwargs)


def espn_wbb_player_core(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_player_core``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_player_core` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_player_core(*args, **kwargs)


def espn_wbb_player_eventlog(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_player_eventlog``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_player_eventlog` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_player_eventlog(*args, **kwargs)


def espn_wbb_player_gamelog(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_player_gamelog``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_player_gamelog` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_player_gamelog(*args, **kwargs)


def espn_wbb_player_info(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_player_info``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_player_info` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_player_info(*args, **kwargs)


def espn_wbb_player_injuries(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_player_injuries``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_player_injuries` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_player_injuries(*args, **kwargs)


def espn_wbb_player_news(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_player_news``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_player_news` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_player_news(*args, **kwargs)


def espn_wbb_player_notes(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_player_notes``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_player_notes` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_player_notes(*args, **kwargs)


def espn_wbb_player_overview(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_player_overview``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_player_overview` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_player_overview(*args, **kwargs)


def espn_wbb_player_records(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_player_records``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_player_records` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_player_records(*args, **kwargs)


def espn_wbb_player_seasons(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_player_seasons``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_player_seasons` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_player_seasons(*args, **kwargs)


def espn_wbb_player_splits(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_player_splits``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_player_splits` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_player_splits(*args, **kwargs)


def espn_wbb_player_statisticslog(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_player_statisticslog``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_player_statisticslog` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_player_statisticslog(*args, **kwargs)


def espn_wbb_player_stats_v3(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_player_stats_v3``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_player_stats_v3` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_player_stats_v3(*args, **kwargs)


def espn_wbb_player_vs_player(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_player_vs_player``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_player_vs_player` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_player_vs_player(*args, **kwargs)


def espn_wbb_players_index(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_players_index``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_players_index` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_players_index(*args, **kwargs)


def espn_wbb_position(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_position``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_position` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_position(*args, **kwargs)


def espn_wbb_positions(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_positions``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_positions` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_positions(*args, **kwargs)


def espn_wbb_rankings(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_rankings``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_rankings` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_rankings(*args, **kwargs)


def espn_wbb_scoreboard(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_scoreboard``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_scoreboard` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_scoreboard(*args, **kwargs)


def espn_wbb_season_awards(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_season_awards``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_season_awards` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_season_awards(*args, **kwargs)


def espn_wbb_season_coaches(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_season_coaches``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_season_coaches` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_season_coaches(*args, **kwargs)


def espn_wbb_season_draft(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_season_draft``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_season_draft` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_season_draft(*args, **kwargs)


def espn_wbb_season_draft_round_picks(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_season_draft_round_picks``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_season_draft_round_picks` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_season_draft_round_picks(*args, **kwargs)


def espn_wbb_season_freeagents(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_season_freeagents``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_season_freeagents` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_season_freeagents(*args, **kwargs)


def espn_wbb_season_futures(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_season_futures``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_season_futures` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_season_futures(*args, **kwargs)


def espn_wbb_season_group(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_season_group``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_season_group` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_season_group(*args, **kwargs)


def espn_wbb_season_group_children(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_season_group_children``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_season_group_children` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_season_group_children(*args, **kwargs)


def espn_wbb_season_group_teams(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_season_group_teams``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_season_group_teams` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_season_group_teams(*args, **kwargs)


def espn_wbb_season_groups(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_season_groups``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_season_groups` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_season_groups(*args, **kwargs)


def espn_wbb_season_info(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_season_info``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_season_info` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_season_info(*args, **kwargs)


def espn_wbb_season_players(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_season_players``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_season_players` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_season_players(*args, **kwargs)


def espn_wbb_season_pointer(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_season_pointer``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_season_pointer` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_season_pointer(*args, **kwargs)


def espn_wbb_season_powerindex(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_season_powerindex``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_season_powerindex` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_season_powerindex(*args, **kwargs)


def espn_wbb_season_powerindex_leaders(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_season_powerindex_leaders``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_season_powerindex_leaders` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_season_powerindex_leaders(*args, **kwargs)


def espn_wbb_season_recruits(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_season_recruits``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_season_recruits` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_season_recruits(*args, **kwargs)


def espn_wbb_season_team(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_season_team``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_season_team` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_season_team(*args, **kwargs)


def espn_wbb_season_teams(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_season_teams``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_season_teams` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_season_teams(*args, **kwargs)


def espn_wbb_season_type(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_season_type``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_season_type` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_season_type(*args, **kwargs)


def espn_wbb_season_type_corrections(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_season_type_corrections``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_season_type_corrections` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_season_type_corrections(*args, **kwargs)


def espn_wbb_season_type_leaders(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_season_type_leaders``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_season_type_leaders` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_season_type_leaders(*args, **kwargs)


def espn_wbb_season_types(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_season_types``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_season_types` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_season_types(*args, **kwargs)


def espn_wbb_season_week(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_season_week``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_season_week` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_season_week(*args, **kwargs)


def espn_wbb_season_week_games(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_season_week_games``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_season_week_games` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_season_week_games(*args, **kwargs)


def espn_wbb_season_week_rankings(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_season_week_rankings``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_season_week_rankings` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_season_week_rankings(*args, **kwargs)


def espn_wbb_season_weeks(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_season_weeks``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_season_weeks` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_season_weeks(*args, **kwargs)


def espn_wbb_seasons(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_seasons``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_seasons` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_seasons(*args, **kwargs)


def espn_wbb_standings_core(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_standings_core``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_standings_core` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_standings_core(*args, **kwargs)


def espn_wbb_statistics_league(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_statistics_league``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_statistics_league` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_statistics_league(*args, **kwargs)


def espn_wbb_summary(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_summary``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_summary` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_summary(*args, **kwargs)


def espn_wbb_talentpicks(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_talentpicks``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_talentpicks` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_talentpicks(*args, **kwargs)


def espn_wbb_team(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_team``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_team` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_team(*args, **kwargs)


def espn_wbb_team_core(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_team_core``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_team_core` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_team_core(*args, **kwargs)


def espn_wbb_team_depthcharts(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_team_depthcharts``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_team_depthcharts` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_team_depthcharts(*args, **kwargs)


def espn_wbb_team_history(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_team_history``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_team_history` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_team_history(*args, **kwargs)


def espn_wbb_team_injuries(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_team_injuries``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_team_injuries` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_team_injuries(*args, **kwargs)


def espn_wbb_team_leaders(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_team_leaders``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_team_leaders` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_team_leaders(*args, **kwargs)


def espn_wbb_team_news(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_team_news``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_team_news` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_team_news(*args, **kwargs)


def espn_wbb_team_record(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_team_record``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_team_record` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_team_record(*args, **kwargs)


def espn_wbb_team_schedule(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_team_schedule``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_team_schedule` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_team_schedule(*args, **kwargs)


def espn_wbb_team_transactions(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_team_transactions``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_team_transactions` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_team_transactions(*args, **kwargs)


def espn_wbb_teams_core(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_teams_core``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_teams_core` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_teams_core(*args, **kwargs)


def espn_wbb_teams_site(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_teams_site``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_teams_site` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_teams_site(*args, **kwargs)


def espn_wbb_tournaments(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_tournaments``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_tournaments` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_tournaments(*args, **kwargs)


def espn_wbb_transactions(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_transactions``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_transactions` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_transactions(*args, **kwargs)


def espn_wbb_venue(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_venue``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_venue` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_venue(*args, **kwargs)


def espn_wbb_venues(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wbb.espn_wbb_venues``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wbb.espn_wbb_venues` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wbb_venues(*args, **kwargs)
