# GENERATED by tools/codegen/generate.py -- DO NOT EDIT.
"""DataFrame-by-default mirror of :mod:`sportsdataverse.wnba`.

Every wrapper that supports ``return_parsed=True`` has that as its default
here; pass ``return_parsed=False`` to recover the raw ``Dict``. Wrappers
without a parser (loaders, helpers) pass through unchanged. See
:mod:`sportsdataverse.parsed` for the design.
"""

from __future__ import annotations

from sportsdataverse.wnba import espn_wnba_award as _raw_espn_wnba_award
from sportsdataverse.wnba import espn_wnba_awards as _raw_espn_wnba_awards
from sportsdataverse.wnba import espn_wnba_calendar_offseason as _raw_espn_wnba_calendar_offseason
from sportsdataverse.wnba import espn_wnba_calendar_ondays as _raw_espn_wnba_calendar_ondays
from sportsdataverse.wnba import espn_wnba_calendar_postseason as _raw_espn_wnba_calendar_postseason
from sportsdataverse.wnba import espn_wnba_calendar_regular_season as _raw_espn_wnba_calendar_regular_season
from sportsdataverse.wnba import espn_wnba_coach as _raw_espn_wnba_coach
from sportsdataverse.wnba import espn_wnba_coach_record as _raw_espn_wnba_coach_record
from sportsdataverse.wnba import espn_wnba_coach_season as _raw_espn_wnba_coach_season
from sportsdataverse.wnba import espn_wnba_coaches as _raw_espn_wnba_coaches
from sportsdataverse.wnba import espn_wnba_conferences as _raw_espn_wnba_conferences
from sportsdataverse.wnba import espn_wnba_franchise as _raw_espn_wnba_franchise
from sportsdataverse.wnba import espn_wnba_franchises as _raw_espn_wnba_franchises
from sportsdataverse.wnba import espn_wnba_game as _raw_espn_wnba_game
from sportsdataverse.wnba import espn_wnba_game_broadcasts as _raw_espn_wnba_game_broadcasts
from sportsdataverse.wnba import espn_wnba_game_competition as _raw_espn_wnba_game_competition
from sportsdataverse.wnba import espn_wnba_game_leaders as _raw_espn_wnba_game_leaders
from sportsdataverse.wnba import espn_wnba_game_odds as _raw_espn_wnba_game_odds
from sportsdataverse.wnba import espn_wnba_game_official_detail as _raw_espn_wnba_game_official_detail
from sportsdataverse.wnba import espn_wnba_game_play as _raw_espn_wnba_game_play
from sportsdataverse.wnba import espn_wnba_game_play_personnel as _raw_espn_wnba_game_play_personnel
from sportsdataverse.wnba import espn_wnba_game_plays as _raw_espn_wnba_game_plays
from sportsdataverse.wnba import espn_wnba_game_powerindex as _raw_espn_wnba_game_powerindex
from sportsdataverse.wnba import espn_wnba_game_predictor as _raw_espn_wnba_game_predictor
from sportsdataverse.wnba import espn_wnba_game_probabilities as _raw_espn_wnba_game_probabilities
from sportsdataverse.wnba import espn_wnba_game_propbets as _raw_espn_wnba_game_propbets
from sportsdataverse.wnba import espn_wnba_game_scoringplays as _raw_espn_wnba_game_scoringplays
from sportsdataverse.wnba import espn_wnba_game_situation as _raw_espn_wnba_game_situation
from sportsdataverse.wnba import espn_wnba_game_status as _raw_espn_wnba_game_status
from sportsdataverse.wnba import espn_wnba_game_team as _raw_espn_wnba_game_team
from sportsdataverse.wnba import espn_wnba_game_team_leaders as _raw_espn_wnba_game_team_leaders
from sportsdataverse.wnba import espn_wnba_game_team_linescores as _raw_espn_wnba_game_team_linescores
from sportsdataverse.wnba import espn_wnba_game_team_record as _raw_espn_wnba_game_team_record
from sportsdataverse.wnba import espn_wnba_game_team_roster as _raw_espn_wnba_game_team_roster
from sportsdataverse.wnba import espn_wnba_game_team_statistics as _raw_espn_wnba_game_team_statistics
from sportsdataverse.wnba import espn_wnba_game_teams as _raw_espn_wnba_game_teams
from sportsdataverse.wnba import espn_wnba_games as _raw_espn_wnba_games
from sportsdataverse.wnba import espn_wnba_injuries as _raw_espn_wnba_injuries
from sportsdataverse.wnba import espn_wnba_leaders as _raw_espn_wnba_leaders
from sportsdataverse.wnba import espn_wnba_leaders_core as _raw_espn_wnba_leaders_core
from sportsdataverse.wnba import espn_wnba_league_notes as _raw_espn_wnba_league_notes
from sportsdataverse.wnba import espn_wnba_league_root as _raw_espn_wnba_league_root
from sportsdataverse.wnba import espn_wnba_news as _raw_espn_wnba_news
from sportsdataverse.wnba import espn_wnba_player_awards as _raw_espn_wnba_player_awards
from sportsdataverse.wnba import espn_wnba_player_bio as _raw_espn_wnba_player_bio
from sportsdataverse.wnba import espn_wnba_player_career_stats as _raw_espn_wnba_player_career_stats
from sportsdataverse.wnba import espn_wnba_player_contracts as _raw_espn_wnba_player_contracts
from sportsdataverse.wnba import espn_wnba_player_core as _raw_espn_wnba_player_core
from sportsdataverse.wnba import espn_wnba_player_eventlog as _raw_espn_wnba_player_eventlog
from sportsdataverse.wnba import espn_wnba_player_gamelog as _raw_espn_wnba_player_gamelog
from sportsdataverse.wnba import espn_wnba_player_info as _raw_espn_wnba_player_info
from sportsdataverse.wnba import espn_wnba_player_injuries as _raw_espn_wnba_player_injuries
from sportsdataverse.wnba import espn_wnba_player_news as _raw_espn_wnba_player_news
from sportsdataverse.wnba import espn_wnba_player_notes as _raw_espn_wnba_player_notes
from sportsdataverse.wnba import espn_wnba_player_overview as _raw_espn_wnba_player_overview
from sportsdataverse.wnba import espn_wnba_player_records as _raw_espn_wnba_player_records
from sportsdataverse.wnba import espn_wnba_player_seasons as _raw_espn_wnba_player_seasons
from sportsdataverse.wnba import espn_wnba_player_splits as _raw_espn_wnba_player_splits
from sportsdataverse.wnba import espn_wnba_player_statisticslog as _raw_espn_wnba_player_statisticslog
from sportsdataverse.wnba import espn_wnba_player_stats_v3 as _raw_espn_wnba_player_stats_v3
from sportsdataverse.wnba import espn_wnba_player_vs_player as _raw_espn_wnba_player_vs_player
from sportsdataverse.wnba import espn_wnba_players_index as _raw_espn_wnba_players_index
from sportsdataverse.wnba import espn_wnba_position as _raw_espn_wnba_position
from sportsdataverse.wnba import espn_wnba_positions as _raw_espn_wnba_positions
from sportsdataverse.wnba import espn_wnba_scoreboard as _raw_espn_wnba_scoreboard
from sportsdataverse.wnba import espn_wnba_season_awards as _raw_espn_wnba_season_awards
from sportsdataverse.wnba import espn_wnba_season_coaches as _raw_espn_wnba_season_coaches
from sportsdataverse.wnba import espn_wnba_season_draft as _raw_espn_wnba_season_draft
from sportsdataverse.wnba import espn_wnba_season_draft_round_picks as _raw_espn_wnba_season_draft_round_picks
from sportsdataverse.wnba import espn_wnba_season_freeagents as _raw_espn_wnba_season_freeagents
from sportsdataverse.wnba import espn_wnba_season_futures as _raw_espn_wnba_season_futures
from sportsdataverse.wnba import espn_wnba_season_group as _raw_espn_wnba_season_group
from sportsdataverse.wnba import espn_wnba_season_group_children as _raw_espn_wnba_season_group_children
from sportsdataverse.wnba import espn_wnba_season_group_teams as _raw_espn_wnba_season_group_teams
from sportsdataverse.wnba import espn_wnba_season_groups as _raw_espn_wnba_season_groups
from sportsdataverse.wnba import espn_wnba_season_info as _raw_espn_wnba_season_info
from sportsdataverse.wnba import espn_wnba_season_players as _raw_espn_wnba_season_players
from sportsdataverse.wnba import espn_wnba_season_pointer as _raw_espn_wnba_season_pointer
from sportsdataverse.wnba import espn_wnba_season_powerindex as _raw_espn_wnba_season_powerindex
from sportsdataverse.wnba import espn_wnba_season_powerindex_leaders as _raw_espn_wnba_season_powerindex_leaders
from sportsdataverse.wnba import espn_wnba_season_team as _raw_espn_wnba_season_team
from sportsdataverse.wnba import espn_wnba_season_teams as _raw_espn_wnba_season_teams
from sportsdataverse.wnba import espn_wnba_season_type as _raw_espn_wnba_season_type
from sportsdataverse.wnba import espn_wnba_season_type_corrections as _raw_espn_wnba_season_type_corrections
from sportsdataverse.wnba import espn_wnba_season_type_leaders as _raw_espn_wnba_season_type_leaders
from sportsdataverse.wnba import espn_wnba_season_types as _raw_espn_wnba_season_types
from sportsdataverse.wnba import espn_wnba_season_week as _raw_espn_wnba_season_week
from sportsdataverse.wnba import espn_wnba_season_week_games as _raw_espn_wnba_season_week_games
from sportsdataverse.wnba import espn_wnba_season_weeks as _raw_espn_wnba_season_weeks
from sportsdataverse.wnba import espn_wnba_seasons as _raw_espn_wnba_seasons
from sportsdataverse.wnba import espn_wnba_standings_core as _raw_espn_wnba_standings_core
from sportsdataverse.wnba import espn_wnba_statistics_league as _raw_espn_wnba_statistics_league
from sportsdataverse.wnba import espn_wnba_summary as _raw_espn_wnba_summary
from sportsdataverse.wnba import espn_wnba_talentpicks as _raw_espn_wnba_talentpicks
from sportsdataverse.wnba import espn_wnba_team as _raw_espn_wnba_team
from sportsdataverse.wnba import espn_wnba_team_core as _raw_espn_wnba_team_core
from sportsdataverse.wnba import espn_wnba_team_depthcharts as _raw_espn_wnba_team_depthcharts
from sportsdataverse.wnba import espn_wnba_team_history as _raw_espn_wnba_team_history
from sportsdataverse.wnba import espn_wnba_team_injuries as _raw_espn_wnba_team_injuries
from sportsdataverse.wnba import espn_wnba_team_leaders as _raw_espn_wnba_team_leaders
from sportsdataverse.wnba import espn_wnba_team_news as _raw_espn_wnba_team_news
from sportsdataverse.wnba import espn_wnba_team_record as _raw_espn_wnba_team_record
from sportsdataverse.wnba import espn_wnba_team_schedule as _raw_espn_wnba_team_schedule
from sportsdataverse.wnba import espn_wnba_team_transactions as _raw_espn_wnba_team_transactions
from sportsdataverse.wnba import espn_wnba_teams_core as _raw_espn_wnba_teams_core
from sportsdataverse.wnba import espn_wnba_teams_site as _raw_espn_wnba_teams_site
from sportsdataverse.wnba import espn_wnba_tournaments as _raw_espn_wnba_tournaments
from sportsdataverse.wnba import espn_wnba_transactions as _raw_espn_wnba_transactions
from sportsdataverse.wnba import espn_wnba_venue as _raw_espn_wnba_venue
from sportsdataverse.wnba import espn_wnba_venues as _raw_espn_wnba_venues
from sportsdataverse.wnba import download as download  # noqa: F401
from sportsdataverse.wnba import espn_wnba_calendar as espn_wnba_calendar  # noqa: F401
from sportsdataverse.wnba import espn_wnba_draft as espn_wnba_draft  # noqa: F401
from sportsdataverse.wnba import espn_wnba_game_officials as espn_wnba_game_officials  # noqa: F401
from sportsdataverse.wnba import espn_wnba_game_rosters as espn_wnba_game_rosters  # noqa: F401
from sportsdataverse.wnba import espn_wnba_pbp as espn_wnba_pbp  # noqa: F401
from sportsdataverse.wnba import espn_wnba_player_stats as espn_wnba_player_stats  # noqa: F401
from sportsdataverse.wnba import espn_wnba_schedule as espn_wnba_schedule  # noqa: F401
from sportsdataverse.wnba import espn_wnba_standings as espn_wnba_standings  # noqa: F401
from sportsdataverse.wnba import espn_wnba_team_roster as espn_wnba_team_roster  # noqa: F401
from sportsdataverse.wnba import espn_wnba_team_stats as espn_wnba_team_stats  # noqa: F401
from sportsdataverse.wnba import espn_wnba_teams as espn_wnba_teams  # noqa: F401
from sportsdataverse.wnba import flatten_json_iterative as flatten_json_iterative  # noqa: F401
from sportsdataverse.wnba import helper_wnba_athlete_items as helper_wnba_athlete_items  # noqa: F401
from sportsdataverse.wnba import helper_wnba_game_data as helper_wnba_game_data  # noqa: F401
from sportsdataverse.wnba import helper_wnba_game_items as helper_wnba_game_items  # noqa: F401
from sportsdataverse.wnba import helper_wnba_pbp as helper_wnba_pbp  # noqa: F401
from sportsdataverse.wnba import helper_wnba_pbp_features as helper_wnba_pbp_features  # noqa: F401
from sportsdataverse.wnba import helper_wnba_pickcenter as helper_wnba_pickcenter  # noqa: F401
from sportsdataverse.wnba import helper_wnba_roster_items as helper_wnba_roster_items  # noqa: F401
from sportsdataverse.wnba import helper_wnba_team_items as helper_wnba_team_items  # noqa: F401
from sportsdataverse.wnba import load_wnba_draft as load_wnba_draft  # noqa: F401
from sportsdataverse.wnba import load_wnba_game_rosters as load_wnba_game_rosters  # noqa: F401
from sportsdataverse.wnba import load_wnba_officials as load_wnba_officials  # noqa: F401
from sportsdataverse.wnba import load_wnba_pbp as load_wnba_pbp  # noqa: F401
from sportsdataverse.wnba import load_wnba_player_boxscore as load_wnba_player_boxscore  # noqa: F401
from sportsdataverse.wnba import load_wnba_player_season_stats as load_wnba_player_season_stats  # noqa: F401
from sportsdataverse.wnba import load_wnba_rosters as load_wnba_rosters  # noqa: F401
from sportsdataverse.wnba import load_wnba_schedule as load_wnba_schedule  # noqa: F401
from sportsdataverse.wnba import load_wnba_shots as load_wnba_shots  # noqa: F401
from sportsdataverse.wnba import load_wnba_standings as load_wnba_standings  # noqa: F401
from sportsdataverse.wnba import load_wnba_stats_coaches as load_wnba_stats_coaches  # noqa: F401
from sportsdataverse.wnba import load_wnba_stats_draft as load_wnba_stats_draft  # noqa: F401
from sportsdataverse.wnba import load_wnba_stats_game_rosters as load_wnba_stats_game_rosters  # noqa: F401
from sportsdataverse.wnba import load_wnba_stats_lineups as load_wnba_stats_lineups  # noqa: F401
from sportsdataverse.wnba import load_wnba_stats_officials as load_wnba_stats_officials  # noqa: F401
from sportsdataverse.wnba import load_wnba_stats_pbp as load_wnba_stats_pbp  # noqa: F401
from sportsdataverse.wnba import load_wnba_stats_player_game_logs as load_wnba_stats_player_game_logs  # noqa: F401
from sportsdataverse.wnba import load_wnba_stats_player_season_stats as load_wnba_stats_player_season_stats  # noqa: F401
from sportsdataverse.wnba import load_wnba_stats_rosters as load_wnba_stats_rosters  # noqa: F401
from sportsdataverse.wnba import load_wnba_stats_schedules as load_wnba_stats_schedules  # noqa: F401
from sportsdataverse.wnba import load_wnba_stats_shots as load_wnba_stats_shots  # noqa: F401
from sportsdataverse.wnba import load_wnba_stats_standings as load_wnba_stats_standings  # noqa: F401
from sportsdataverse.wnba import load_wnba_stats_team_season_stats as load_wnba_stats_team_season_stats  # noqa: F401
from sportsdataverse.wnba import load_wnba_team_boxscore as load_wnba_team_boxscore  # noqa: F401
from sportsdataverse.wnba import load_wnba_team_season_stats as load_wnba_team_season_stats  # noqa: F401
from sportsdataverse.wnba import most_recent_wnba_season as most_recent_wnba_season  # noqa: F401
from sportsdataverse.wnba import scoreboard_event_parsing as scoreboard_event_parsing  # noqa: F401
from sportsdataverse.wnba import underscore as underscore  # noqa: F401
from sportsdataverse.wnba import wnba_pbp_disk as wnba_pbp_disk  # noqa: F401

__all__ = [
    "download",
    "espn_wnba_award",
    "espn_wnba_awards",
    "espn_wnba_calendar",
    "espn_wnba_calendar_offseason",
    "espn_wnba_calendar_ondays",
    "espn_wnba_calendar_postseason",
    "espn_wnba_calendar_regular_season",
    "espn_wnba_coach",
    "espn_wnba_coach_record",
    "espn_wnba_coach_season",
    "espn_wnba_coaches",
    "espn_wnba_conferences",
    "espn_wnba_draft",
    "espn_wnba_franchise",
    "espn_wnba_franchises",
    "espn_wnba_game",
    "espn_wnba_game_broadcasts",
    "espn_wnba_game_competition",
    "espn_wnba_game_leaders",
    "espn_wnba_game_odds",
    "espn_wnba_game_official_detail",
    "espn_wnba_game_officials",
    "espn_wnba_game_play",
    "espn_wnba_game_play_personnel",
    "espn_wnba_game_plays",
    "espn_wnba_game_powerindex",
    "espn_wnba_game_predictor",
    "espn_wnba_game_probabilities",
    "espn_wnba_game_propbets",
    "espn_wnba_game_rosters",
    "espn_wnba_game_scoringplays",
    "espn_wnba_game_situation",
    "espn_wnba_game_status",
    "espn_wnba_game_team",
    "espn_wnba_game_team_leaders",
    "espn_wnba_game_team_linescores",
    "espn_wnba_game_team_record",
    "espn_wnba_game_team_roster",
    "espn_wnba_game_team_statistics",
    "espn_wnba_game_teams",
    "espn_wnba_games",
    "espn_wnba_injuries",
    "espn_wnba_leaders",
    "espn_wnba_leaders_core",
    "espn_wnba_league_notes",
    "espn_wnba_league_root",
    "espn_wnba_news",
    "espn_wnba_pbp",
    "espn_wnba_player_awards",
    "espn_wnba_player_bio",
    "espn_wnba_player_career_stats",
    "espn_wnba_player_contracts",
    "espn_wnba_player_core",
    "espn_wnba_player_eventlog",
    "espn_wnba_player_gamelog",
    "espn_wnba_player_info",
    "espn_wnba_player_injuries",
    "espn_wnba_player_news",
    "espn_wnba_player_notes",
    "espn_wnba_player_overview",
    "espn_wnba_player_records",
    "espn_wnba_player_seasons",
    "espn_wnba_player_splits",
    "espn_wnba_player_statisticslog",
    "espn_wnba_player_stats",
    "espn_wnba_player_stats_v3",
    "espn_wnba_player_vs_player",
    "espn_wnba_players_index",
    "espn_wnba_position",
    "espn_wnba_positions",
    "espn_wnba_schedule",
    "espn_wnba_scoreboard",
    "espn_wnba_season_awards",
    "espn_wnba_season_coaches",
    "espn_wnba_season_draft",
    "espn_wnba_season_draft_round_picks",
    "espn_wnba_season_freeagents",
    "espn_wnba_season_futures",
    "espn_wnba_season_group",
    "espn_wnba_season_group_children",
    "espn_wnba_season_group_teams",
    "espn_wnba_season_groups",
    "espn_wnba_season_info",
    "espn_wnba_season_players",
    "espn_wnba_season_pointer",
    "espn_wnba_season_powerindex",
    "espn_wnba_season_powerindex_leaders",
    "espn_wnba_season_team",
    "espn_wnba_season_teams",
    "espn_wnba_season_type",
    "espn_wnba_season_type_corrections",
    "espn_wnba_season_type_leaders",
    "espn_wnba_season_types",
    "espn_wnba_season_week",
    "espn_wnba_season_week_games",
    "espn_wnba_season_weeks",
    "espn_wnba_seasons",
    "espn_wnba_standings",
    "espn_wnba_standings_core",
    "espn_wnba_statistics_league",
    "espn_wnba_summary",
    "espn_wnba_talentpicks",
    "espn_wnba_team",
    "espn_wnba_team_core",
    "espn_wnba_team_depthcharts",
    "espn_wnba_team_history",
    "espn_wnba_team_injuries",
    "espn_wnba_team_leaders",
    "espn_wnba_team_news",
    "espn_wnba_team_record",
    "espn_wnba_team_roster",
    "espn_wnba_team_schedule",
    "espn_wnba_team_stats",
    "espn_wnba_team_transactions",
    "espn_wnba_teams",
    "espn_wnba_teams_core",
    "espn_wnba_teams_site",
    "espn_wnba_tournaments",
    "espn_wnba_transactions",
    "espn_wnba_venue",
    "espn_wnba_venues",
    "flatten_json_iterative",
    "helper_wnba_athlete_items",
    "helper_wnba_game_data",
    "helper_wnba_game_items",
    "helper_wnba_pbp",
    "helper_wnba_pbp_features",
    "helper_wnba_pickcenter",
    "helper_wnba_roster_items",
    "helper_wnba_team_items",
    "load_wnba_draft",
    "load_wnba_game_rosters",
    "load_wnba_officials",
    "load_wnba_pbp",
    "load_wnba_player_boxscore",
    "load_wnba_player_season_stats",
    "load_wnba_rosters",
    "load_wnba_schedule",
    "load_wnba_shots",
    "load_wnba_standings",
    "load_wnba_stats_coaches",
    "load_wnba_stats_draft",
    "load_wnba_stats_game_rosters",
    "load_wnba_stats_lineups",
    "load_wnba_stats_officials",
    "load_wnba_stats_pbp",
    "load_wnba_stats_player_game_logs",
    "load_wnba_stats_player_season_stats",
    "load_wnba_stats_rosters",
    "load_wnba_stats_schedules",
    "load_wnba_stats_shots",
    "load_wnba_stats_standings",
    "load_wnba_stats_team_season_stats",
    "load_wnba_team_boxscore",
    "load_wnba_team_season_stats",
    "most_recent_wnba_season",
    "scoreboard_event_parsing",
    "underscore",
    "wnba_pbp_disk",
]


def espn_wnba_award(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_award``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_award` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_award(*args, **kwargs)


def espn_wnba_awards(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_awards``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_awards` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_awards(*args, **kwargs)


def espn_wnba_calendar_offseason(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_calendar_offseason``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_calendar_offseason` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_calendar_offseason(*args, **kwargs)


def espn_wnba_calendar_ondays(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_calendar_ondays``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_calendar_ondays` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_calendar_ondays(*args, **kwargs)


def espn_wnba_calendar_postseason(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_calendar_postseason``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_calendar_postseason` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_calendar_postseason(*args, **kwargs)


def espn_wnba_calendar_regular_season(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_calendar_regular_season``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_calendar_regular_season` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_calendar_regular_season(*args, **kwargs)


def espn_wnba_coach(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_coach``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_coach` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_coach(*args, **kwargs)


def espn_wnba_coach_record(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_coach_record``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_coach_record` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_coach_record(*args, **kwargs)


def espn_wnba_coach_season(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_coach_season``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_coach_season` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_coach_season(*args, **kwargs)


def espn_wnba_coaches(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_coaches``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_coaches` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_coaches(*args, **kwargs)


def espn_wnba_conferences(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_conferences``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_conferences` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_conferences(*args, **kwargs)


def espn_wnba_franchise(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_franchise``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_franchise` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_franchise(*args, **kwargs)


def espn_wnba_franchises(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_franchises``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_franchises` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_franchises(*args, **kwargs)


def espn_wnba_game(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_game``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_game` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_game(*args, **kwargs)


def espn_wnba_game_broadcasts(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_game_broadcasts``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_game_broadcasts` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_game_broadcasts(*args, **kwargs)


def espn_wnba_game_competition(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_game_competition``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_game_competition` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_game_competition(*args, **kwargs)


def espn_wnba_game_leaders(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_game_leaders``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_game_leaders` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_game_leaders(*args, **kwargs)


def espn_wnba_game_odds(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_game_odds``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_game_odds` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_game_odds(*args, **kwargs)


def espn_wnba_game_official_detail(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_game_official_detail``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_game_official_detail` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_game_official_detail(*args, **kwargs)


def espn_wnba_game_play(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_game_play``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_game_play` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_game_play(*args, **kwargs)


def espn_wnba_game_play_personnel(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_game_play_personnel``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_game_play_personnel` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_game_play_personnel(*args, **kwargs)


def espn_wnba_game_plays(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_game_plays``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_game_plays` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_game_plays(*args, **kwargs)


def espn_wnba_game_powerindex(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_game_powerindex``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_game_powerindex` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_game_powerindex(*args, **kwargs)


def espn_wnba_game_predictor(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_game_predictor``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_game_predictor` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_game_predictor(*args, **kwargs)


def espn_wnba_game_probabilities(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_game_probabilities``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_game_probabilities` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_game_probabilities(*args, **kwargs)


def espn_wnba_game_propbets(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_game_propbets``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_game_propbets` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_game_propbets(*args, **kwargs)


def espn_wnba_game_scoringplays(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_game_scoringplays``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_game_scoringplays` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_game_scoringplays(*args, **kwargs)


def espn_wnba_game_situation(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_game_situation``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_game_situation` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_game_situation(*args, **kwargs)


def espn_wnba_game_status(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_game_status``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_game_status` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_game_status(*args, **kwargs)


def espn_wnba_game_team(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_game_team``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_game_team` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_game_team(*args, **kwargs)


def espn_wnba_game_team_leaders(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_game_team_leaders``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_game_team_leaders` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_game_team_leaders(*args, **kwargs)


def espn_wnba_game_team_linescores(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_game_team_linescores``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_game_team_linescores` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_game_team_linescores(*args, **kwargs)


def espn_wnba_game_team_record(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_game_team_record``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_game_team_record` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_game_team_record(*args, **kwargs)


def espn_wnba_game_team_roster(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_game_team_roster``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_game_team_roster` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_game_team_roster(*args, **kwargs)


def espn_wnba_game_team_statistics(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_game_team_statistics``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_game_team_statistics` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_game_team_statistics(*args, **kwargs)


def espn_wnba_game_teams(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_game_teams``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_game_teams` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_game_teams(*args, **kwargs)


def espn_wnba_games(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_games``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_games` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_games(*args, **kwargs)


def espn_wnba_injuries(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_injuries``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_injuries` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_injuries(*args, **kwargs)


def espn_wnba_leaders(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_leaders``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_leaders` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_leaders(*args, **kwargs)


def espn_wnba_leaders_core(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_leaders_core``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_leaders_core` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_leaders_core(*args, **kwargs)


def espn_wnba_league_notes(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_league_notes``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_league_notes` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_league_notes(*args, **kwargs)


def espn_wnba_league_root(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_league_root``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_league_root` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_league_root(*args, **kwargs)


def espn_wnba_news(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_news``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_news` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_news(*args, **kwargs)


def espn_wnba_player_awards(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_player_awards``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_player_awards` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_player_awards(*args, **kwargs)


def espn_wnba_player_bio(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_player_bio``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_player_bio` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_player_bio(*args, **kwargs)


def espn_wnba_player_career_stats(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_player_career_stats``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_player_career_stats` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_player_career_stats(*args, **kwargs)


def espn_wnba_player_contracts(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_player_contracts``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_player_contracts` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_player_contracts(*args, **kwargs)


def espn_wnba_player_core(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_player_core``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_player_core` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_player_core(*args, **kwargs)


def espn_wnba_player_eventlog(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_player_eventlog``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_player_eventlog` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_player_eventlog(*args, **kwargs)


def espn_wnba_player_gamelog(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_player_gamelog``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_player_gamelog` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_player_gamelog(*args, **kwargs)


def espn_wnba_player_info(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_player_info``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_player_info` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_player_info(*args, **kwargs)


def espn_wnba_player_injuries(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_player_injuries``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_player_injuries` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_player_injuries(*args, **kwargs)


def espn_wnba_player_news(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_player_news``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_player_news` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_player_news(*args, **kwargs)


def espn_wnba_player_notes(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_player_notes``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_player_notes` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_player_notes(*args, **kwargs)


def espn_wnba_player_overview(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_player_overview``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_player_overview` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_player_overview(*args, **kwargs)


def espn_wnba_player_records(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_player_records``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_player_records` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_player_records(*args, **kwargs)


def espn_wnba_player_seasons(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_player_seasons``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_player_seasons` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_player_seasons(*args, **kwargs)


def espn_wnba_player_splits(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_player_splits``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_player_splits` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_player_splits(*args, **kwargs)


def espn_wnba_player_statisticslog(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_player_statisticslog``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_player_statisticslog` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_player_statisticslog(*args, **kwargs)


def espn_wnba_player_stats_v3(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_player_stats_v3``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_player_stats_v3` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_player_stats_v3(*args, **kwargs)


def espn_wnba_player_vs_player(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_player_vs_player``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_player_vs_player` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_player_vs_player(*args, **kwargs)


def espn_wnba_players_index(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_players_index``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_players_index` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_players_index(*args, **kwargs)


def espn_wnba_position(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_position``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_position` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_position(*args, **kwargs)


def espn_wnba_positions(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_positions``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_positions` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_positions(*args, **kwargs)


def espn_wnba_scoreboard(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_scoreboard``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_scoreboard` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_scoreboard(*args, **kwargs)


def espn_wnba_season_awards(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_season_awards``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_season_awards` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_season_awards(*args, **kwargs)


def espn_wnba_season_coaches(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_season_coaches``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_season_coaches` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_season_coaches(*args, **kwargs)


def espn_wnba_season_draft(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_season_draft``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_season_draft` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_season_draft(*args, **kwargs)


def espn_wnba_season_draft_round_picks(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_season_draft_round_picks``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_season_draft_round_picks` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_season_draft_round_picks(*args, **kwargs)


def espn_wnba_season_freeagents(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_season_freeagents``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_season_freeagents` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_season_freeagents(*args, **kwargs)


def espn_wnba_season_futures(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_season_futures``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_season_futures` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_season_futures(*args, **kwargs)


def espn_wnba_season_group(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_season_group``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_season_group` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_season_group(*args, **kwargs)


def espn_wnba_season_group_children(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_season_group_children``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_season_group_children` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_season_group_children(*args, **kwargs)


def espn_wnba_season_group_teams(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_season_group_teams``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_season_group_teams` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_season_group_teams(*args, **kwargs)


def espn_wnba_season_groups(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_season_groups``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_season_groups` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_season_groups(*args, **kwargs)


def espn_wnba_season_info(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_season_info``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_season_info` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_season_info(*args, **kwargs)


def espn_wnba_season_players(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_season_players``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_season_players` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_season_players(*args, **kwargs)


def espn_wnba_season_pointer(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_season_pointer``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_season_pointer` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_season_pointer(*args, **kwargs)


def espn_wnba_season_powerindex(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_season_powerindex``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_season_powerindex` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_season_powerindex(*args, **kwargs)


def espn_wnba_season_powerindex_leaders(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_season_powerindex_leaders``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_season_powerindex_leaders` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_season_powerindex_leaders(*args, **kwargs)


def espn_wnba_season_team(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_season_team``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_season_team` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_season_team(*args, **kwargs)


def espn_wnba_season_teams(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_season_teams``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_season_teams` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_season_teams(*args, **kwargs)


def espn_wnba_season_type(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_season_type``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_season_type` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_season_type(*args, **kwargs)


def espn_wnba_season_type_corrections(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_season_type_corrections``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_season_type_corrections` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_season_type_corrections(*args, **kwargs)


def espn_wnba_season_type_leaders(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_season_type_leaders``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_season_type_leaders` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_season_type_leaders(*args, **kwargs)


def espn_wnba_season_types(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_season_types``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_season_types` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_season_types(*args, **kwargs)


def espn_wnba_season_week(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_season_week``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_season_week` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_season_week(*args, **kwargs)


def espn_wnba_season_week_games(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_season_week_games``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_season_week_games` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_season_week_games(*args, **kwargs)


def espn_wnba_season_weeks(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_season_weeks``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_season_weeks` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_season_weeks(*args, **kwargs)


def espn_wnba_seasons(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_seasons``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_seasons` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_seasons(*args, **kwargs)


def espn_wnba_standings_core(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_standings_core``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_standings_core` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_standings_core(*args, **kwargs)


def espn_wnba_statistics_league(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_statistics_league``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_statistics_league` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_statistics_league(*args, **kwargs)


def espn_wnba_summary(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_summary``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_summary` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_summary(*args, **kwargs)


def espn_wnba_talentpicks(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_talentpicks``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_talentpicks` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_talentpicks(*args, **kwargs)


def espn_wnba_team(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_team``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_team` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_team(*args, **kwargs)


def espn_wnba_team_core(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_team_core``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_team_core` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_team_core(*args, **kwargs)


def espn_wnba_team_depthcharts(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_team_depthcharts``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_team_depthcharts` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_team_depthcharts(*args, **kwargs)


def espn_wnba_team_history(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_team_history``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_team_history` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_team_history(*args, **kwargs)


def espn_wnba_team_injuries(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_team_injuries``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_team_injuries` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_team_injuries(*args, **kwargs)


def espn_wnba_team_leaders(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_team_leaders``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_team_leaders` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_team_leaders(*args, **kwargs)


def espn_wnba_team_news(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_team_news``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_team_news` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_team_news(*args, **kwargs)


def espn_wnba_team_record(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_team_record``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_team_record` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_team_record(*args, **kwargs)


def espn_wnba_team_schedule(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_team_schedule``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_team_schedule` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_team_schedule(*args, **kwargs)


def espn_wnba_team_transactions(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_team_transactions``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_team_transactions` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_team_transactions(*args, **kwargs)


def espn_wnba_teams_core(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_teams_core``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_teams_core` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_teams_core(*args, **kwargs)


def espn_wnba_teams_site(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_teams_site``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_teams_site` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_teams_site(*args, **kwargs)


def espn_wnba_tournaments(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_tournaments``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_tournaments` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_tournaments(*args, **kwargs)


def espn_wnba_transactions(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_transactions``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_transactions` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_transactions(*args, **kwargs)


def espn_wnba_venue(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_venue``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_venue` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_venue(*args, **kwargs)


def espn_wnba_venues(*args, **kwargs):
    """``return_parsed=True`` by default (parsed.* mirror of ``wnba.espn_wnba_venues``).

    Pass ``return_parsed=False`` for the raw ``Dict``. See
    :func:`sportsdataverse.wnba.espn_wnba_venues` for full documentation.
    """
    kwargs.setdefault("return_parsed", True)
    return _raw_espn_wnba_venues(*args, **kwargs)
