# GENERATED by tools/codegen/generate.py -- DO NOT EDIT.
# Source: tools/codegen/endpoints/releases.yaml
"""sportsdataverse.pwhl dataset loaders (sportsdataverse-data releases). Generated."""

from __future__ import annotations

import polars as pl

from sportsdataverse._codegen_runtime import (
    SeasonNotFoundError,  # noqa: F401
    _as_season_list,
    _cast_ids_int64,  # noqa: F401  (used only by loaders declaring id_int64)
    _read_release_parquet,
    cli_warn,
)
from sportsdataverse._deprecation import warn_deprecated  # noqa: F401  (used only by deprecated_for shims)

__all__ = [
    "load_phf_pbp",
    "load_phf_player_boxscores",
    "load_phf_schedules",
    "load_phf_team_boxscores",
    "load_pwhl_game_info",
    "load_pwhl_game_rosters",
    "load_pwhl_shifts",
    "load_pwhl_goalie_boxscores",
    "load_pwhl_officials",
    "load_pwhl_pbp",
    "load_pwhl_xg_pbp",
    "load_pwhl_penalty_summary",
    "load_pwhl_player_boxscores",
    "load_pwhl_rosters",
    "load_pwhl_schedules",
    "load_pwhl_scoring_summary",
    "load_pwhl_shootout",
    "load_pwhl_shots_by_period",
    "load_pwhl_skater_boxscores",
    "load_pwhl_team_boxscores",
    "load_pwhl_three_stars",
]


def load_phf_pbp(seasons, return_as_pandas: bool = False):
    """Load phf_pbp (sportsdataverse-data release).

    Source: https://github.com/sportsdataverse/sportsdataverse-data/releases/tag/phf_pbp

    Args:
        seasons: an int or iterable of seasons (>= 2016).
        return_as_pandas: return a pandas DataFrame instead of polars.

    Returns:
        A polars (or pandas) DataFrame; seasons with no published asset are
        skipped with a warning rather than raising (404-safe).

        |col_name                  |type   |
        |:-------------------------|:------|
        |play_type                 |String |
        |team                      |String |
        |time                      |String |
        |play_description          |String |
        |period_id                 |Int32  |
        |game_id                   |Int32  |
        |game_date                 |String |
        |home_team                 |String |
        |home_location             |String |
        |home_nickname             |String |
        |home_abbreviation         |String |
        |home_score_total          |Int32  |
        |away_team                 |String |
        |away_location             |String |
        |away_nickname             |String |
        |away_abbreviation         |String |
        |away_score_total          |Int32  |
        |away_goalie               |String |
        |away_goalie_jersey        |String |
        |goalie_change             |String |
        |penalty                   |Int32  |
        |on_ice_situation          |String |
        |score                     |String |
        |minute_start              |Int32  |
        |second_start              |Int32  |
        |clock                     |String |
        |leader                    |String |
        |away_goals                |String |
        |home_goals                |String |
        |sec_from_start            |Int32  |
        |power_play_seconds        |Int32  |
        |time_elapsed              |String |
        |time_remaining            |String |
        |player_name_1             |String |
        |player_jersey_1           |String |
        |home_skaters              |Int32  |
        |away_skaters              |Int32  |
        |home_goalie               |String |
        |home_goalie_jersey        |String |
        |player_name_2             |String |
        |player_jersey_2           |String |
        |shot_result               |String |
        |goalie_involved           |String |
        |penalty_type              |String |
        |penalty_level             |String |
        |penalty_length            |String |
        |start_power_play          |Int32  |
        |end_power_play            |Int32  |
        |player_name_3             |String |
        |player_jersey_3           |String |
        |scoring_team_abbrev       |String |
        |scoring_team_on_ice       |String |
        |offensive_player_name_1   |String |
        |offensive_player_name_2   |String |
        |offensive_player_name_3   |String |
        |offensive_player_name_4   |String |
        |offensive_player_name_5   |String |
        |defending_team_abbrev     |String |
        |offensive_player_jersey_1 |String |
        |offensive_player_jersey_2 |String |
        |offensive_player_jersey_3 |String |
        |offensive_player_jersey_4 |String |
        |offensive_player_jersey_5 |String |
        |defending_team_on_ice     |String |
        |defensive_player_name_1   |String |
        |defensive_player_name_2   |String |
        |defensive_player_name_3   |String |
        |defensive_player_name_4   |String |
        |defensive_player_name_5   |String |
        |defensive_player_jersey_1 |String |
        |defensive_player_jersey_2 |String |
        |defensive_player_jersey_3 |String |
        |defensive_player_jersey_4 |String |
        |defensive_player_jersey_5 |String |
        |defensive_player_name_6   |String |
        |defensive_player_jersey_6 |String |
        |offensive_player_name_6   |String |
        |offensive_player_jersey_6 |String |
        |season                    |Int32  |

    Raises:
        SeasonNotFoundError: if a requested season is below 2016.

    Example:
        Quick start::

            load_phf_pbp(seasons=2023)
    """
    frames, missing = [], []
    for season in _as_season_list(seasons):
        if int(season) < 2016:
            raise SeasonNotFoundError("season cannot be less than 2016")
        df = _read_release_parquet(
            f"https://github.com/sportsdataverse/sportsdataverse-data/releases/download/phf_pbp/play_by_play_{season}.parquet"
        )
        if df is None:
            missing.append(season)
            continue
        frames.append(df)
    if missing:
        cli_warn("load_phf_pbp: no data for season(s) {missing} (skipped)".format(missing=missing))
    # diagonal: per-season release schemas can drift (columns added/dropped
    # over the years) -- union columns, null-fill gaps.
    out = pl.concat(frames, how="diagonal_relaxed") if frames else pl.DataFrame()
    return out.to_pandas(use_pyarrow_extension_array=True) if return_as_pandas else out


def load_phf_player_boxscores(seasons, return_as_pandas: bool = False):
    """Load phf_player_boxscores (sportsdataverse-data release).

    Source: https://github.com/sportsdataverse/sportsdataverse-data/releases/tag/phf_player_boxscores

    Args:
        seasons: an int or iterable of seasons (>= 2016).
        return_as_pandas: return a pandas DataFrame instead of polars.

    Returns:
        A polars (or pandas) DataFrame; seasons with no published asset are
        skipped with a warning rather than raising (404-safe).

        |col_name          |type    |
        |:-----------------|:-------|
        |player_jersey     |Int32   |
        |player_name       |String  |
        |position          |String  |
        |goals             |Int32   |
        |assists           |Int32   |
        |points            |Int32   |
        |penalty_minutes   |Int32   |
        |shots_on_goal     |Int32   |
        |blocks            |Int32   |
        |giveaways         |Int32   |
        |takeaways         |Int32   |
        |faceoffs_won_lost |String  |
        |faceoffs_win_pct  |Float64 |
        |powerplay_goals   |Int32   |
        |shorthanded_goals |Int32   |
        |shots             |Int32   |
        |shots_blocked     |Int32   |
        |faceoffs_won      |Int32   |
        |faceoffs_lost     |Int32   |
        |team              |String  |
        |skaters_href      |String  |
        |player_id         |String  |
        |game_id           |Int32   |
        |minutes_played    |String  |
        |shots_against     |Int32   |
        |goals_against     |Int32   |
        |saves             |Int32   |
        |save_percent      |Float64 |
        |goalies_href      |String  |
        |season            |Int32   |

    Raises:
        SeasonNotFoundError: if a requested season is below 2016.

    Example:
        Quick start::

            load_phf_player_boxscores(seasons=2023)
    """
    frames, missing = [], []
    for season in _as_season_list(seasons):
        if int(season) < 2016:
            raise SeasonNotFoundError("season cannot be less than 2016")
        df = _read_release_parquet(
            f"https://github.com/sportsdataverse/sportsdataverse-data/releases/download/phf_player_boxscores/player_box_{season}.parquet"
        )
        if df is None:
            missing.append(season)
            continue
        frames.append(df)
    if missing:
        cli_warn("load_phf_player_boxscores: no data for season(s) {missing} (skipped)".format(missing=missing))
    # diagonal: per-season release schemas can drift (columns added/dropped
    # over the years) -- union columns, null-fill gaps.
    out = pl.concat(frames, how="diagonal_relaxed") if frames else pl.DataFrame()
    return out.to_pandas(use_pyarrow_extension_array=True) if return_as_pandas else out


def load_phf_schedules(seasons, return_as_pandas: bool = False):
    """Load phf_schedules (sportsdataverse-data release).

    Source: https://github.com/sportsdataverse/sportsdataverse-data/releases/tag/phf_schedules

    Args:
        seasons: an int or iterable of seasons (>= 2016).
        return_as_pandas: return a pandas DataFrame instead of polars.

    Returns:
        A polars (or pandas) DataFrame; seasons with no published asset are
        skipped with a warning rather than raising (404-safe).

        |col_name                  |type                                      |
        |:-------------------------|:-----------------------------------------|
        |type                      |String                                    |
        |id                        |String                                    |
        |league_id                 |Int32                                     |
        |season_id                 |Int32                                     |
        |tournament_id             |Boolean                                   |
        |game_id                   |Int32                                     |
        |number                    |Int32                                     |
        |datetime                  |Datetime(time_unit='us', time_zone='UTC') |
        |datetime_tz               |Datetime(time_unit='us', time_zone='UTC') |
        |time_zone                 |String                                    |
        |time_zone_abbr            |String                                    |
        |updated_at                |Datetime(time_unit='us', time_zone='UTC') |
        |created_at                |Datetime(time_unit='us', time_zone='UTC') |
        |home_team_id              |Int32                                     |
        |home_team                 |String                                    |
        |home_team_short           |String                                    |
        |home_team_logo_url_full   |String                                    |
        |home_team_logo_url_small  |String                                    |
        |home_team_logo_url_medium |String                                    |
        |home_team_logo_url_large  |String                                    |
        |home_team_logo_url_50     |String                                    |
        |home_team_logo_url_100    |String                                    |
        |home_team_logo_url_200    |String                                    |
        |away_team_id              |Int32                                     |
        |away_team                 |String                                    |
        |away_team_short           |String                                    |
        |away_team_logo_url_full   |String                                    |
        |away_team_logo_url_small  |String                                    |
        |away_team_logo_url_medium |String                                    |
        |away_team_logo_url_large  |String                                    |
        |away_team_logo_url_50     |String                                    |
        |away_team_logo_url_100    |String                                    |
        |away_team_logo_url_200    |String                                    |
        |home_division_id          |Int32                                     |
        |home_division             |String                                    |
        |away_division_id          |Int32                                     |
        |away_division             |String                                    |
        |home_score                |Int32                                     |
        |away_score                |Int32                                     |
        |home_shots                |Int32                                     |
        |away_shots                |Int32                                     |
        |home_penalty_minutes      |Int32                                     |
        |away_penalty_minutes      |Int32                                     |
        |home_roster_count         |Int32                                     |
        |away_roster_count         |Int32                                     |
        |facility_id               |Int32                                     |
        |facility                  |String                                    |
        |facility_address          |String                                    |
        |rink_id                   |Boolean                                   |
        |rink                      |Boolean                                   |
        |game_type                 |String                                    |
        |notes                     |String                                    |
        |status                    |String                                    |
        |overtime                  |Boolean                                   |
        |shootout                  |Boolean                                   |
        |allow_players             |Boolean                                   |
        |tickets_url               |String                                    |
        |watch_live_url            |String                                    |
        |external_url              |Boolean                                   |
        |has_play_by_play          |Boolean                                   |
        |highlight_color           |Boolean                                   |
        |attendance                |Int32                                     |
        |date_group                |Date                                      |
        |winner                    |String                                    |
        |season                    |Int32                                     |
        |PBP                       |Boolean                                   |
        |team_box                  |Boolean                                   |
        |player_box                |Boolean                                   |

    Raises:
        SeasonNotFoundError: if a requested season is below 2016.

    Example:
        Quick start::

            load_phf_schedules(seasons=2023)
    """
    frames, missing = [], []
    for season in _as_season_list(seasons):
        if int(season) < 2016:
            raise SeasonNotFoundError("season cannot be less than 2016")
        df = _read_release_parquet(
            f"https://github.com/sportsdataverse/sportsdataverse-data/releases/download/phf_schedules/phf_schedule_{season}.parquet"
        )
        if df is None:
            missing.append(season)
            continue
        frames.append(df)
    if missing:
        cli_warn("load_phf_schedules: no data for season(s) {missing} (skipped)".format(missing=missing))
    # diagonal: per-season release schemas can drift (columns added/dropped
    # over the years) -- union columns, null-fill gaps.
    out = pl.concat(frames, how="diagonal_relaxed") if frames else pl.DataFrame()
    return out.to_pandas(use_pyarrow_extension_array=True) if return_as_pandas else out


def load_phf_team_boxscores(seasons, return_as_pandas: bool = False):
    """Load phf_team_boxscores (sportsdataverse-data release).

    Source: https://github.com/sportsdataverse/sportsdataverse-data/releases/tag/phf_team_boxscores

    Args:
        seasons: an int or iterable of seasons (>= 2016).
        return_as_pandas: return a pandas DataFrame instead of polars.

    Returns:
        A polars (or pandas) DataFrame; seasons with no published asset are
        skipped with a warning rather than raising (404-safe).

        |col_name                 |type    |
        |:------------------------|:-------|
        |team                     |String  |
        |game_id                  |Int32   |
        |winner                   |Boolean |
        |total_scoring            |Int32   |
        |successful_power_play    |Float64 |
        |power_play_opportunities |Float64 |
        |power_play_percent       |Float64 |
        |penalty_minutes          |Float64 |
        |faceoff_percent          |Float64 |
        |blocked_opponent_shots   |Float64 |
        |takeaways                |Float64 |
        |giveaways                |Float64 |
        |period_1_shots           |Int32   |
        |period_2_shots           |Int32   |
        |period_3_shots           |Int32   |
        |overtime_shots           |Int32   |
        |shootout_made_shots      |Int32   |
        |shootout_missed_shots    |Int32   |
        |total_shots              |Int32   |
        |period_1_scoring         |Int32   |
        |period_2_scoring         |Int32   |
        |period_3_scoring         |Int32   |
        |overtime_scoring         |Int32   |
        |shootout_made_scoring    |Float64 |
        |shootout_missed_scoring  |Float64 |
        |season                   |Int32   |

    Raises:
        SeasonNotFoundError: if a requested season is below 2016.

    Example:
        Quick start::

            load_phf_team_boxscores(seasons=2023)
    """
    frames, missing = [], []
    for season in _as_season_list(seasons):
        if int(season) < 2016:
            raise SeasonNotFoundError("season cannot be less than 2016")
        df = _read_release_parquet(
            f"https://github.com/sportsdataverse/sportsdataverse-data/releases/download/phf_team_boxscores/team_box_{season}.parquet"
        )
        if df is None:
            missing.append(season)
            continue
        frames.append(df)
    if missing:
        cli_warn("load_phf_team_boxscores: no data for season(s) {missing} (skipped)".format(missing=missing))
    # diagonal: per-season release schemas can drift (columns added/dropped
    # over the years) -- union columns, null-fill gaps.
    out = pl.concat(frames, how="diagonal_relaxed") if frames else pl.DataFrame()
    return out.to_pandas(use_pyarrow_extension_array=True) if return_as_pandas else out


def load_pwhl_game_info(seasons, return_as_pandas: bool = False):
    """Load pwhl_game_info (sportsdataverse-data release).

    Source: https://github.com/sportsdataverse/sportsdataverse-data/releases/tag/pwhl_game_info

    Args:
        seasons: an int or iterable of seasons (>= 2024).
        return_as_pandas: return a pandas DataFrame instead of polars.

    Returns:
        A polars (or pandas) DataFrame; seasons with no published asset are
        skipped with a warning rather than raising (404-safe).

        |col_name        |type   |
        |:---------------|:------|
        |game_id         |Int64  |
        |game_number     |String |
        |game_date       |String |
        |game_date_iso   |String |
        |start_time      |String |
        |end_time        |String |
        |game_duration   |String |
        |game_venue      |String |
        |attendance      |Int64  |
        |game_status     |String |
        |game_season_id  |Int64  |
        |started         |Int64  |
        |final           |Int64  |
        |home_team_id    |Int64  |
        |home_team       |String |
        |home_team_abbr  |String |
        |home_score      |Int64  |
        |away_team_id    |Int64  |
        |away_team       |String |
        |away_team_abbr  |String |
        |away_score      |Int64  |
        |has_shootout    |Int64  |
        |game_report_url |String |
        |boxscore_url    |String |

    Raises:
        SeasonNotFoundError: if a requested season is below 2024.

    Example:
        Quick start::

            load_pwhl_game_info(seasons=2024)
    """
    frames, missing = [], []
    for season in _as_season_list(seasons):
        if int(season) < 2024:
            raise SeasonNotFoundError("season cannot be less than 2024")
        df = _read_release_parquet(
            f"https://github.com/sportsdataverse/sportsdataverse-data/releases/download/pwhl_game_info/game_info_{season}.parquet"
        )
        if df is None:
            missing.append(season)
            continue
        frames.append(df)
    if missing:
        cli_warn("load_pwhl_game_info: no data for season(s) {missing} (skipped)".format(missing=missing))
    # diagonal: per-season release schemas can drift (columns added/dropped
    # over the years) -- union columns, null-fill gaps.
    out = pl.concat(frames, how="diagonal_relaxed") if frames else pl.DataFrame()
    return out.to_pandas(use_pyarrow_extension_array=True) if return_as_pandas else out


def load_pwhl_game_rosters(seasons, return_as_pandas: bool = False):
    """Load pwhl_game_rosters (sportsdataverse-data release).

    Source: https://github.com/sportsdataverse/sportsdataverse-data/releases/tag/pwhl_game_rosters

    Args:
        seasons: an int or iterable of seasons (>= 2024).
        return_as_pandas: return a pandas DataFrame instead of polars.

    Returns:
        A polars (or pandas) DataFrame; seasons with no published asset are
        skipped with a warning rather than raising (404-safe).

        |col_name      |type   |
        |:-------------|:------|
        |game_id       |Int64  |
        |team_id       |Int64  |
        |team          |String |
        |team_abbr     |String |
        |team_side     |String |
        |player_type   |String |
        |player_id     |Int64  |
        |first_name    |String |
        |last_name     |String |
        |jersey_number |Int64  |
        |position      |String |
        |birth_date    |String |
        |starting      |Int64  |
        |status        |String |

    Raises:
        SeasonNotFoundError: if a requested season is below 2024.

    Example:
        Quick start::

            load_pwhl_game_rosters(seasons=2024)
    """
    frames, missing = [], []
    for season in _as_season_list(seasons):
        if int(season) < 2024:
            raise SeasonNotFoundError("season cannot be less than 2024")
        df = _read_release_parquet(
            f"https://github.com/sportsdataverse/sportsdataverse-data/releases/download/pwhl_game_rosters/game_rosters_{season}.parquet"
        )
        if df is None:
            missing.append(season)
            continue
        frames.append(df)
    if missing:
        cli_warn("load_pwhl_game_rosters: no data for season(s) {missing} (skipped)".format(missing=missing))
    # diagonal: per-season release schemas can drift (columns added/dropped
    # over the years) -- union columns, null-fill gaps.
    out = pl.concat(frames, how="diagonal_relaxed") if frames else pl.DataFrame()
    return out.to_pandas(use_pyarrow_extension_array=True) if return_as_pandas else out


def load_pwhl_shifts(seasons, return_as_pandas: bool = False):
    """Load pwhl_shifts (sportsdataverse-data release).

    Source: https://github.com/sportsdataverse/sportsdataverse-data/releases/tag/pwhl_shifts

    Args:
        seasons: an int or iterable of seasons (>= 2024).
        return_as_pandas: return a pandas DataFrame instead of polars.

    Returns:
        A polars (or pandas) DataFrame; seasons with no published asset are
        skipped with a warning rather than raising (404-safe).

        |col_name         |type   |
        |:----------------|:------|
        |game_id          |Int64  |
        |player_id        |Int64  |
        |first_name       |String |
        |last_name        |String |
        |jersey_number    |String |
        |home             |Int64  |
        |period           |Int64  |
        |start_time       |String |
        |end_time         |String |
        |length           |String |
        |start_s          |Int64  |
        |end_s            |Int64  |
        |goal_on_shift    |Int64  |
        |penalty_on_shift |Int64  |

    Raises:
        SeasonNotFoundError: if a requested season is below 2024.

    Example:
        Quick start::

            load_pwhl_shifts(seasons=2025)
    """
    frames, missing = [], []
    for season in _as_season_list(seasons):
        if int(season) < 2024:
            raise SeasonNotFoundError("season cannot be less than 2024")
        df = _read_release_parquet(
            f"https://github.com/sportsdataverse/sportsdataverse-data/releases/download/pwhl_shifts/shifts_{season}.parquet"
        )
        if df is None:
            missing.append(season)
            continue
        frames.append(df)
    if missing:
        cli_warn("load_pwhl_shifts: no data for season(s) {missing} (skipped)".format(missing=missing))
    # diagonal: per-season release schemas can drift (columns added/dropped
    # over the years) -- union columns, null-fill gaps.
    out = pl.concat(frames, how="diagonal_relaxed") if frames else pl.DataFrame()
    return out.to_pandas(use_pyarrow_extension_array=True) if return_as_pandas else out


def load_pwhl_goalie_boxscores(seasons, return_as_pandas: bool = False):
    """Load pwhl_goalie_boxscores (sportsdataverse-data release).

    Source: https://github.com/sportsdataverse/sportsdataverse-data/releases/tag/pwhl_goalie_boxscores

    Args:
        seasons: an int or iterable of seasons (>= 2024).
        return_as_pandas: return a pandas DataFrame instead of polars.

    Returns:
        A polars (or pandas) DataFrame; seasons with no published asset are
        skipped with a warning rather than raising (404-safe).

        |col_name         |type    |
        |:----------------|:-------|
        |player_id        |String  |
        |first_name       |String  |
        |last_name        |String  |
        |position         |String  |
        |team_id          |Int64   |
        |game_id          |Int64   |
        |league           |String  |
        |toi              |String  |
        |time_on_ice      |Float64 |
        |saves            |Int64   |
        |goals_against    |Int64   |
        |shots_against    |Int64   |
        |goals            |Int64   |
        |assists          |Int64   |
        |points           |Int64   |
        |penalty_minutes  |Int64   |
        |faceoff_attempts |Int64   |
        |faceoff_wins     |Int64   |
        |faceoff_losses   |Int64   |
        |faceoff_pct      |Null    |
        |starting         |Int64   |

    Raises:
        SeasonNotFoundError: if a requested season is below 2024.

    Example:
        Quick start::

            load_pwhl_goalie_boxscores(seasons=2024)
    """
    frames, missing = [], []
    for season in _as_season_list(seasons):
        if int(season) < 2024:
            raise SeasonNotFoundError("season cannot be less than 2024")
        df = _read_release_parquet(
            f"https://github.com/sportsdataverse/sportsdataverse-data/releases/download/pwhl_goalie_boxscores/goalie_box_{season}.parquet"
        )
        if df is None:
            missing.append(season)
            continue
        frames.append(df)
    if missing:
        cli_warn("load_pwhl_goalie_boxscores: no data for season(s) {missing} (skipped)".format(missing=missing))
    # diagonal: per-season release schemas can drift (columns added/dropped
    # over the years) -- union columns, null-fill gaps.
    out = pl.concat(frames, how="diagonal_relaxed") if frames else pl.DataFrame()
    return out.to_pandas(use_pyarrow_extension_array=True) if return_as_pandas else out


def load_pwhl_officials(seasons, return_as_pandas: bool = False):
    """Load pwhl_officials (sportsdataverse-data release).

    Source: https://github.com/sportsdataverse/sportsdataverse-data/releases/tag/pwhl_officials

    Args:
        seasons: an int or iterable of seasons (>= 2024).
        return_as_pandas: return a pandas DataFrame instead of polars.

    Returns:
        A polars (or pandas) DataFrame; seasons with no published asset are
        skipped with a warning rather than raising (404-safe).

        |col_name      |type   |
        |:-------------|:------|
        |game_id       |Int64  |
        |role          |String |
        |first_name    |String |
        |last_name     |String |
        |jersey_number |Int64  |
        |official_role |String |

    Raises:
        SeasonNotFoundError: if a requested season is below 2024.

    Example:
        Quick start::

            load_pwhl_officials(seasons=2024)
    """
    frames, missing = [], []
    for season in _as_season_list(seasons):
        if int(season) < 2024:
            raise SeasonNotFoundError("season cannot be less than 2024")
        df = _read_release_parquet(
            f"https://github.com/sportsdataverse/sportsdataverse-data/releases/download/pwhl_officials/officials_{season}.parquet"
        )
        if df is None:
            missing.append(season)
            continue
        frames.append(df)
    if missing:
        cli_warn("load_pwhl_officials: no data for season(s) {missing} (skipped)".format(missing=missing))
    # diagonal: per-season release schemas can drift (columns added/dropped
    # over the years) -- union columns, null-fill gaps.
    out = pl.concat(frames, how="diagonal_relaxed") if frames else pl.DataFrame()
    return out.to_pandas(use_pyarrow_extension_array=True) if return_as_pandas else out


def load_pwhl_pbp(seasons, return_as_pandas: bool = False):
    """Load pwhl_pbp (sportsdataverse-data release).

    Source: https://github.com/sportsdataverse/sportsdataverse-data/releases/tag/pwhl_pbp

    Args:
        seasons: an int or iterable of seasons (>= 2024).
        return_as_pandas: return a pandas DataFrame instead of polars.

    Returns:
        A polars (or pandas) DataFrame; seasons with no published asset are
        skipped with a warning rather than raising (404-safe).

        |col_name                    |type    |
        |:---------------------------|:-------|
        |game_id                     |Int64   |
        |event                       |String  |
        |team_id                     |String  |
        |period_of_game              |String  |
        |time_of_period              |String  |
        |x_coord                     |Float64 |
        |y_coord                     |Float64 |
        |player_id                   |Int64   |
        |player_name_first           |String  |
        |player_name_last            |String  |
        |player_position             |String  |
        |goal                        |Boolean |
        |goalie_id                   |Int64   |
        |goalie_first                |String  |
        |goalie_last                 |String  |
        |home_win                    |String  |
        |player_team_id              |String  |
        |event_type                  |String  |
        |shot_quality                |String  |
        |empty_net                   |String  |
        |game_winner                 |String  |
        |penalty_shot                |String  |
        |insurance                   |String  |
        |short_handed                |String  |
        |power_play                  |String  |
        |player_two_id               |Int64   |
        |player_two_name_first       |String  |
        |player_two_name_last        |String  |
        |player_two_position         |String  |
        |player_three_id             |Int64   |
        |player_three_name_first     |String  |
        |player_three_name_last      |String  |
        |player_three_position       |String  |
        |plus_player_one_id          |Int64   |
        |plus_player_one_first       |String  |
        |plus_player_one_last        |String  |
        |plus_player_one_position    |String  |
        |plus_player_two_id          |Int64   |
        |plus_player_two_first       |String  |
        |plus_player_two_last        |String  |
        |plus_player_two_position    |String  |
        |plus_player_three_id        |Int64   |
        |plus_player_three_first     |String  |
        |plus_player_three_last      |String  |
        |plus_player_three_position  |String  |
        |plus_player_four_id         |Int64   |
        |plus_player_four_first      |String  |
        |plus_player_four_last       |String  |
        |plus_player_four_position   |String  |
        |plus_player_five_id         |Int64   |
        |plus_player_five_first      |String  |
        |plus_player_five_last       |String  |
        |plus_player_five_position   |String  |
        |minus_player_one_id         |Int64   |
        |minus_player_one_first      |String  |
        |minus_player_one_last       |String  |
        |minus_player_one_position   |String  |
        |minus_player_two_id         |Int64   |
        |minus_player_two_first      |String  |
        |minus_player_two_last       |String  |
        |minus_player_two_position   |String  |
        |minus_player_three_id       |Int64   |
        |minus_player_three_first    |String  |
        |minus_player_three_last     |String  |
        |minus_player_three_position |String  |
        |minus_player_four_id        |Int64   |
        |minus_player_four_first     |String  |
        |minus_player_four_last      |String  |
        |minus_player_four_position  |String  |
        |minus_player_five_id        |Int64   |
        |minus_player_five_first     |String  |
        |minus_player_five_last      |String  |
        |minus_player_five_position  |String  |
        |penalty_length              |String  |
        |game_date                   |String  |
        |game_season                 |Int64   |
        |game_season_id              |String  |
        |home_team                   |String  |
        |home_team_id                |String  |
        |away_team                   |String  |
        |away_team_id                |String  |
        |x_coord_original            |Int64   |
        |y_coord_original            |Int64   |
        |x_coord_neutral             |Int64   |
        |y_coord_neutral             |Int64   |
        |x_coord_fixed               |Float64 |
        |y_coord_fixed               |Float64 |
        |x_coord_right               |Float64 |
        |y_coord_right               |Float64 |
        |x_coord_vertical            |Float64 |
        |y_coord_vertical            |Float64 |
        |minute_start                |Int64   |
        |second_start                |Int64   |
        |clock                       |String  |
        |sec_from_start              |Int64   |
        |shot_distance               |Float64 |
        |shot_angle                  |Float64 |
        |scoring_chance              |Boolean |
        |on_ice_home                 |String  |
        |on_ice_away                 |String  |
        |skaters_home                |Int64   |
        |skaters_away                |Int64   |
        |strength_state              |String  |
        |strength_state_valid        |Boolean |

    Raises:
        SeasonNotFoundError: if a requested season is below 2024.

    Example:
        Quick start::

            load_pwhl_pbp(seasons=2024)
    """
    frames, missing = [], []
    for season in _as_season_list(seasons):
        if int(season) < 2024:
            raise SeasonNotFoundError("season cannot be less than 2024")
        df = _read_release_parquet(
            f"https://github.com/sportsdataverse/sportsdataverse-data/releases/download/pwhl_pbp/play_by_play_{season}.parquet"
        )
        if df is None:
            missing.append(season)
            continue
        frames.append(df)
    if missing:
        cli_warn("load_pwhl_pbp: no data for season(s) {missing} (skipped)".format(missing=missing))
    # diagonal: per-season release schemas can drift (columns added/dropped
    # over the years) -- union columns, null-fill gaps.
    out = pl.concat(frames, how="diagonal_relaxed") if frames else pl.DataFrame()
    return out.to_pandas(use_pyarrow_extension_array=True) if return_as_pandas else out


def load_pwhl_xg_pbp(seasons, return_as_pandas: bool = False):
    """Load pwhl_xg_pbp (sportsdataverse-data release).

    Source: https://github.com/sportsdataverse/sportsdataverse-data/releases/tag/pwhl_xg_pbp

    Args:
        seasons: an int or iterable of seasons (>= 2024).
        return_as_pandas: return a pandas DataFrame instead of polars.

    Returns:
        A polars (or pandas) DataFrame; seasons with no published asset are
        skipped with a warning rather than raising (404-safe).

        |col_name       |type    |
        |:--------------|:-------|
        |game_id        |Int32   |
        |game_season    |Int32   |
        |game_date      |String  |
        |team_id        |Int32   |
        |player_id      |Int32   |
        |goalie_id      |Int32   |
        |period_of_game |String  |
        |sec_from_start |Int32   |
        |clock          |String  |
        |x_coord        |Float64 |
        |y_coord        |Float64 |
        |shot_distance  |Float64 |
        |shot_angle     |Float64 |
        |event_type     |String  |
        |shot_quality   |String  |
        |power_play     |Int32   |
        |short_handed   |String  |
        |empty_net      |String  |
        |penalty_shot   |String  |
        |goal           |Boolean |
        |xg             |Float64 |

    Raises:
        SeasonNotFoundError: if a requested season is below 2024.

    Example:
        Quick start::

            load_pwhl_xg_pbp(seasons=2025)
    """
    frames, missing = [], []
    for season in _as_season_list(seasons):
        if int(season) < 2024:
            raise SeasonNotFoundError("season cannot be less than 2024")
        df = _read_release_parquet(
            f"https://github.com/sportsdataverse/sportsdataverse-data/releases/download/pwhl_xg_pbp/pwhl_xg_pbp_{season}.parquet"
        )
        if df is None:
            missing.append(season)
            continue
        frames.append(df)
    if missing:
        cli_warn("load_pwhl_xg_pbp: no data for season(s) {missing} (skipped)".format(missing=missing))
    # diagonal: per-season release schemas can drift (columns added/dropped
    # over the years) -- union columns, null-fill gaps.
    out = pl.concat(frames, how="diagonal_relaxed") if frames else pl.DataFrame()
    return out.to_pandas(use_pyarrow_extension_array=True) if return_as_pandas else out


def load_pwhl_penalty_summary(seasons, return_as_pandas: bool = False):
    """Load pwhl_penalty_summary (sportsdataverse-data release).

    Source: https://github.com/sportsdataverse/sportsdataverse-data/releases/tag/pwhl_penalty_summary

    Args:
        seasons: an int or iterable of seasons (>= 2024).
        return_as_pandas: return a pandas DataFrame instead of polars.

    Returns:
        A polars (or pandas) DataFrame; seasons with no published asset are
        skipped with a warning rather than raising (404-safe).

        |col_name          |type   |
        |:-----------------|:------|
        |game_id           |Int64  |
        |period_id         |Int64  |
        |period            |String |
        |time              |String |
        |team_id           |Int64  |
        |team              |String |
        |team_abbr         |String |
        |game_penalty_id   |Int64  |
        |minutes           |Int64  |
        |description       |String |
        |rule_number       |String |
        |is_power_play     |Int64  |
        |is_bench          |Int64  |
        |taken_by_id       |Int64  |
        |taken_by_first    |String |
        |taken_by_last     |String |
        |taken_by_position |String |
        |served_by_id      |Int64  |
        |served_by_first   |String |
        |served_by_last    |String |

    Raises:
        SeasonNotFoundError: if a requested season is below 2024.

    Example:
        Quick start::

            load_pwhl_penalty_summary(seasons=2024)
    """
    frames, missing = [], []
    for season in _as_season_list(seasons):
        if int(season) < 2024:
            raise SeasonNotFoundError("season cannot be less than 2024")
        df = _read_release_parquet(
            f"https://github.com/sportsdataverse/sportsdataverse-data/releases/download/pwhl_penalty_summary/penalty_summary_{season}.parquet"
        )
        if df is None:
            missing.append(season)
            continue
        frames.append(df)
    if missing:
        cli_warn("load_pwhl_penalty_summary: no data for season(s) {missing} (skipped)".format(missing=missing))
    # diagonal: per-season release schemas can drift (columns added/dropped
    # over the years) -- union columns, null-fill gaps.
    out = pl.concat(frames, how="diagonal_relaxed") if frames else pl.DataFrame()
    return out.to_pandas(use_pyarrow_extension_array=True) if return_as_pandas else out


def load_pwhl_player_boxscores(seasons, return_as_pandas: bool = False):
    """Load pwhl_player_boxscores (sportsdataverse-data release).

    Source: https://github.com/sportsdataverse/sportsdataverse-data/releases/tag/pwhl_player_boxscores

    Args:
        seasons: an int or iterable of seasons (>= 2024).
        return_as_pandas: return a pandas DataFrame instead of polars.

    Returns:
        A polars (or pandas) DataFrame; seasons with no published asset are
        skipped with a warning rather than raising (404-safe).

        |col_name         |type    |
        |:----------------|:-------|
        |player_id        |String  |
        |first_name       |String  |
        |last_name        |String  |
        |position         |String  |
        |team_id          |Int64   |
        |game_id          |Int64   |
        |league           |String  |
        |toi              |String  |
        |time_on_ice      |Float64 |
        |goals            |Int64   |
        |assists          |Int64   |
        |points           |Int64   |
        |shots            |Int64   |
        |hits             |Int64   |
        |blocked_shots    |Int64   |
        |penalty_minutes  |Int64   |
        |plus_minus       |Int64   |
        |faceoff_attempts |Int64   |
        |faceoff_wins     |Int64   |
        |faceoff_losses   |Int64   |
        |faceoff_pct      |Float64 |
        |starting         |Int64   |
        |player_type      |String  |
        |saves            |Int64   |
        |goals_against    |Int64   |
        |shots_against    |Int64   |

    Raises:
        SeasonNotFoundError: if a requested season is below 2024.

    Example:
        Quick start::

            load_pwhl_player_boxscores(seasons=2024)
    """
    frames, missing = [], []
    for season in _as_season_list(seasons):
        if int(season) < 2024:
            raise SeasonNotFoundError("season cannot be less than 2024")
        df = _read_release_parquet(
            f"https://github.com/sportsdataverse/sportsdataverse-data/releases/download/pwhl_player_boxscores/player_box_{season}.parquet"
        )
        if df is None:
            missing.append(season)
            continue
        frames.append(df)
    if missing:
        cli_warn("load_pwhl_player_boxscores: no data for season(s) {missing} (skipped)".format(missing=missing))
    # diagonal: per-season release schemas can drift (columns added/dropped
    # over the years) -- union columns, null-fill gaps.
    out = pl.concat(frames, how="diagonal_relaxed") if frames else pl.DataFrame()
    return out.to_pandas(use_pyarrow_extension_array=True) if return_as_pandas else out


def load_pwhl_rosters(seasons, return_as_pandas: bool = False):
    """Load pwhl_rosters (sportsdataverse-data release).

    Source: https://github.com/sportsdataverse/sportsdataverse-data/releases/tag/pwhl_rosters

    Args:
        seasons: an int or iterable of seasons (>= 2024).
        return_as_pandas: return a pandas DataFrame instead of polars.

    Returns:
        A polars (or pandas) DataFrame; seasons with no published asset are
        skipped with a warning rather than raising (404-safe).

        |col_name      |type   |
        |:-------------|:------|
        |team_id       |Int32  |
        |team          |String |
        |team_abbr     |String |
        |team_side     |String |
        |player_type   |String |
        |player_id     |Int32  |
        |first_name    |String |
        |last_name     |String |
        |jersey_number |Int32  |
        |position      |String |
        |birth_date    |String |
        |season        |Int32  |

    Raises:
        SeasonNotFoundError: if a requested season is below 2024.

    Example:
        Quick start::

            load_pwhl_rosters(seasons=2024)
    """
    frames, missing = [], []
    for season in _as_season_list(seasons):
        if int(season) < 2024:
            raise SeasonNotFoundError("season cannot be less than 2024")
        df = _read_release_parquet(
            f"https://github.com/sportsdataverse/sportsdataverse-data/releases/download/pwhl_rosters/rosters_{season}.parquet"
        )
        if df is None:
            missing.append(season)
            continue
        frames.append(df)
    if missing:
        cli_warn("load_pwhl_rosters: no data for season(s) {missing} (skipped)".format(missing=missing))
    # diagonal: per-season release schemas can drift (columns added/dropped
    # over the years) -- union columns, null-fill gaps.
    out = pl.concat(frames, how="diagonal_relaxed") if frames else pl.DataFrame()
    return out.to_pandas(use_pyarrow_extension_array=True) if return_as_pandas else out


def load_pwhl_schedules(seasons, return_as_pandas: bool = False):
    """Load pwhl_schedules (sportsdataverse-data release).

    Source: https://github.com/sportsdataverse/sportsdataverse-data/releases/tag/pwhl_schedules

    Args:
        seasons: an int or iterable of seasons (>= 2024).
        return_as_pandas: return a pandas DataFrame instead of polars.

    Returns:
        A polars (or pandas) DataFrame; seasons with no published asset are
        skipped with a warning rather than raising (404-safe).

        |col_name        |type    |
        |:---------------|:-------|
        |game_id         |String  |
        |season          |Int32   |
        |game_date       |String  |
        |game_status     |String  |
        |home_team       |String  |
        |home_team_id    |String  |
        |away_team       |String  |
        |away_team_id    |String  |
        |home_score      |String  |
        |away_score      |String  |
        |winner          |String  |
        |venue           |String  |
        |venue_url       |String  |
        |game_type       |String  |
        |game_json       |Boolean |
        |game_json_url   |String  |
        |PBP             |Boolean |
        |player_box      |Boolean |
        |skater_box      |Boolean |
        |goalie_box      |Boolean |
        |team_box        |Boolean |
        |game_info       |Boolean |
        |game_rosters    |Boolean |
        |scoring_summary |Boolean |
        |penalty_summary |Boolean |
        |three_stars     |Boolean |
        |officials       |Boolean |
        |shots_by_period |Boolean |
        |shootout        |Boolean |

    Raises:
        SeasonNotFoundError: if a requested season is below 2024.

    Example:
        Quick start::

            load_pwhl_schedules(seasons=2024)
    """
    frames, missing = [], []
    for season in _as_season_list(seasons):
        if int(season) < 2024:
            raise SeasonNotFoundError("season cannot be less than 2024")
        df = _read_release_parquet(
            f"https://github.com/sportsdataverse/sportsdataverse-data/releases/download/pwhl_schedules/pwhl_schedule_{season}.parquet"
        )
        if df is None:
            missing.append(season)
            continue
        frames.append(df)
    if missing:
        cli_warn("load_pwhl_schedules: no data for season(s) {missing} (skipped)".format(missing=missing))
    # diagonal: per-season release schemas can drift (columns added/dropped
    # over the years) -- union columns, null-fill gaps.
    out = pl.concat(frames, how="diagonal_relaxed") if frames else pl.DataFrame()
    return out.to_pandas(use_pyarrow_extension_array=True) if return_as_pandas else out


def load_pwhl_scoring_summary(seasons, return_as_pandas: bool = False):
    """Load pwhl_scoring_summary (sportsdataverse-data release).

    Source: https://github.com/sportsdataverse/sportsdataverse-data/releases/tag/pwhl_scoring_summary

    Args:
        seasons: an int or iterable of seasons (>= 2024).
        return_as_pandas: return a pandas DataFrame instead of polars.

    Returns:
        A polars (or pandas) DataFrame; seasons with no published asset are
        skipped with a warning rather than raising (404-safe).

        |col_name           |type   |
        |:------------------|:------|
        |game_id            |Int64  |
        |period_id          |Int64  |
        |period             |String |
        |time               |String |
        |team_id            |Int64  |
        |team               |String |
        |team_abbr          |String |
        |game_goal_id       |Int64  |
        |scorer_goal_number |Int64  |
        |scorer_id          |Int64  |
        |scorer_first       |String |
        |scorer_last        |String |
        |scorer_position    |String |
        |assist_1_id        |Int64  |
        |assist_1_first     |String |
        |assist_1_last      |String |
        |assist_2_id        |Int64  |
        |assist_2_first     |String |
        |assist_2_last      |String |
        |is_power_play      |Int64  |
        |is_short_handed    |Int64  |
        |is_empty_net       |Int64  |
        |is_penalty_shot    |Int64  |
        |is_insurance       |Int64  |
        |is_game_winning    |Int64  |
        |x_location         |Null   |
        |y_location         |Null   |

    Raises:
        SeasonNotFoundError: if a requested season is below 2024.

    Example:
        Quick start::

            load_pwhl_scoring_summary(seasons=2024)
    """
    frames, missing = [], []
    for season in _as_season_list(seasons):
        if int(season) < 2024:
            raise SeasonNotFoundError("season cannot be less than 2024")
        df = _read_release_parquet(
            f"https://github.com/sportsdataverse/sportsdataverse-data/releases/download/pwhl_scoring_summary/scoring_summary_{season}.parquet"
        )
        if df is None:
            missing.append(season)
            continue
        frames.append(df)
    if missing:
        cli_warn("load_pwhl_scoring_summary: no data for season(s) {missing} (skipped)".format(missing=missing))
    # diagonal: per-season release schemas can drift (columns added/dropped
    # over the years) -- union columns, null-fill gaps.
    out = pl.concat(frames, how="diagonal_relaxed") if frames else pl.DataFrame()
    return out.to_pandas(use_pyarrow_extension_array=True) if return_as_pandas else out


def load_pwhl_shootout(seasons, return_as_pandas: bool = False):
    """Load pwhl_shootout (sportsdataverse-data release).

    Source: https://github.com/sportsdataverse/sportsdataverse-data/releases/tag/pwhl_shootout

    Args:
        seasons: an int or iterable of seasons (>= 2026).
        return_as_pandas: return a pandas DataFrame instead of polars.

    Returns:
        A polars (or pandas) DataFrame; seasons with no published asset are
        skipped with a warning rather than raising (404-safe).

        |col_name      |type   |
        |:-------------|:------|
        |game_id       |Int64  |
        |round         |Int64  |
        |team_side     |String |
        |shooter_id    |Int64  |
        |shooter_first |String |
        |shooter_last  |String |
        |goalie_id     |Int64  |
        |goalie_first  |String |
        |goalie_last   |String |
        |is_goal       |Int64  |

    Raises:
        SeasonNotFoundError: if a requested season is below 2026.

    Example:
        Quick start::

            load_pwhl_shootout(seasons=2026)
    """
    frames, missing = [], []
    for season in _as_season_list(seasons):
        if int(season) < 2026:
            raise SeasonNotFoundError("season cannot be less than 2026")
        df = _read_release_parquet(
            f"https://github.com/sportsdataverse/sportsdataverse-data/releases/download/pwhl_shootout/shootout_summary_{season}.parquet"
        )
        if df is None:
            missing.append(season)
            continue
        frames.append(df)
    if missing:
        cli_warn("load_pwhl_shootout: no data for season(s) {missing} (skipped)".format(missing=missing))
    # diagonal: per-season release schemas can drift (columns added/dropped
    # over the years) -- union columns, null-fill gaps.
    out = pl.concat(frames, how="diagonal_relaxed") if frames else pl.DataFrame()
    return out.to_pandas(use_pyarrow_extension_array=True) if return_as_pandas else out


def load_pwhl_shots_by_period(seasons, return_as_pandas: bool = False):
    """Load pwhl_shots_by_period (sportsdataverse-data release).

    Source: https://github.com/sportsdataverse/sportsdataverse-data/releases/tag/pwhl_shots_by_period

    Args:
        seasons: an int or iterable of seasons (>= 2024).
        return_as_pandas: return a pandas DataFrame instead of polars.

    Returns:
        A polars (or pandas) DataFrame; seasons with no published asset are
        skipped with a warning rather than raising (404-safe).

        |col_name   |type   |
        |:----------|:------|
        |game_id    |Int64  |
        |period_id  |Int64  |
        |period     |String |
        |home_goals |Int64  |
        |home_shots |Int64  |
        |away_goals |Int64  |
        |away_shots |Int64  |

    Raises:
        SeasonNotFoundError: if a requested season is below 2024.

    Example:
        Quick start::

            load_pwhl_shots_by_period(seasons=2024)
    """
    frames, missing = [], []
    for season in _as_season_list(seasons):
        if int(season) < 2024:
            raise SeasonNotFoundError("season cannot be less than 2024")
        df = _read_release_parquet(
            f"https://github.com/sportsdataverse/sportsdataverse-data/releases/download/pwhl_shots_by_period/shots_by_period_{season}.parquet"
        )
        if df is None:
            missing.append(season)
            continue
        frames.append(df)
    if missing:
        cli_warn("load_pwhl_shots_by_period: no data for season(s) {missing} (skipped)".format(missing=missing))
    # diagonal: per-season release schemas can drift (columns added/dropped
    # over the years) -- union columns, null-fill gaps.
    out = pl.concat(frames, how="diagonal_relaxed") if frames else pl.DataFrame()
    return out.to_pandas(use_pyarrow_extension_array=True) if return_as_pandas else out


def load_pwhl_skater_boxscores(seasons, return_as_pandas: bool = False):
    """Load pwhl_skater_boxscores (sportsdataverse-data release).

    Source: https://github.com/sportsdataverse/sportsdataverse-data/releases/tag/pwhl_skater_boxscores

    Args:
        seasons: an int or iterable of seasons (>= 2024).
        return_as_pandas: return a pandas DataFrame instead of polars.

    Returns:
        A polars (or pandas) DataFrame; seasons with no published asset are
        skipped with a warning rather than raising (404-safe).

        |col_name         |type    |
        |:----------------|:-------|
        |player_id        |String  |
        |first_name       |String  |
        |last_name        |String  |
        |position         |String  |
        |team_id          |Int64   |
        |game_id          |Int64   |
        |league           |String  |
        |toi              |String  |
        |time_on_ice      |Float64 |
        |goals            |Int64   |
        |assists          |Int64   |
        |points           |Int64   |
        |shots            |Int64   |
        |hits             |Int64   |
        |blocked_shots    |Int64   |
        |penalty_minutes  |Int64   |
        |plus_minus       |Int64   |
        |faceoff_attempts |Int64   |
        |faceoff_wins     |Int64   |
        |faceoff_losses   |Int64   |
        |faceoff_pct      |Float64 |
        |starting         |Int64   |

    Raises:
        SeasonNotFoundError: if a requested season is below 2024.

    Example:
        Quick start::

            load_pwhl_skater_boxscores(seasons=2024)
    """
    frames, missing = [], []
    for season in _as_season_list(seasons):
        if int(season) < 2024:
            raise SeasonNotFoundError("season cannot be less than 2024")
        df = _read_release_parquet(
            f"https://github.com/sportsdataverse/sportsdataverse-data/releases/download/pwhl_skater_boxscores/skater_box_{season}.parquet"
        )
        if df is None:
            missing.append(season)
            continue
        frames.append(df)
    if missing:
        cli_warn("load_pwhl_skater_boxscores: no data for season(s) {missing} (skipped)".format(missing=missing))
    # diagonal: per-season release schemas can drift (columns added/dropped
    # over the years) -- union columns, null-fill gaps.
    out = pl.concat(frames, how="diagonal_relaxed") if frames else pl.DataFrame()
    return out.to_pandas(use_pyarrow_extension_array=True) if return_as_pandas else out


def load_pwhl_team_boxscores(seasons, return_as_pandas: bool = False):
    """Load pwhl_team_boxscores (sportsdataverse-data release).

    Source: https://github.com/sportsdataverse/sportsdataverse-data/releases/tag/pwhl_team_boxscores

    Args:
        seasons: an int or iterable of seasons (>= 2024).
        return_as_pandas: return a pandas DataFrame instead of polars.

    Returns:
        A polars (or pandas) DataFrame; seasons with no published asset are
        skipped with a warning rather than raising (404-safe).

        |col_name         |type    |
        |:----------------|:-------|
        |game_id          |Int64   |
        |team_id          |Int64   |
        |team             |String  |
        |team_abbr        |String  |
        |team_side        |String  |
        |shots            |Int64   |
        |goals            |Int64   |
        |hits             |Int64   |
        |pp_goals         |Int64   |
        |pp_opportunities |Int64   |
        |goal_count       |Int64   |
        |assist_count     |Int64   |
        |penalty_minutes  |Int64   |
        |infraction_count |Int64   |
        |faceoff_attempts |Int64   |
        |faceoff_wins     |Int64   |
        |faceoff_win_pct  |Float64 |
        |season_wins      |Int64   |
        |season_losses    |Int64   |
        |season_ot_wins   |Int64   |
        |season_ot_losses |Int64   |
        |season_so_losses |Int64   |
        |season_record    |String  |

    Raises:
        SeasonNotFoundError: if a requested season is below 2024.

    Example:
        Quick start::

            load_pwhl_team_boxscores(seasons=2024)
    """
    frames, missing = [], []
    for season in _as_season_list(seasons):
        if int(season) < 2024:
            raise SeasonNotFoundError("season cannot be less than 2024")
        df = _read_release_parquet(
            f"https://github.com/sportsdataverse/sportsdataverse-data/releases/download/pwhl_team_boxscores/team_box_{season}.parquet"
        )
        if df is None:
            missing.append(season)
            continue
        frames.append(df)
    if missing:
        cli_warn("load_pwhl_team_boxscores: no data for season(s) {missing} (skipped)".format(missing=missing))
    # diagonal: per-season release schemas can drift (columns added/dropped
    # over the years) -- union columns, null-fill gaps.
    out = pl.concat(frames, how="diagonal_relaxed") if frames else pl.DataFrame()
    return out.to_pandas(use_pyarrow_extension_array=True) if return_as_pandas else out


def load_pwhl_three_stars(seasons, return_as_pandas: bool = False):
    """Load pwhl_three_stars (sportsdataverse-data release).

    Source: https://github.com/sportsdataverse/sportsdataverse-data/releases/tag/pwhl_three_stars

    Args:
        seasons: an int or iterable of seasons (>= 2024).
        return_as_pandas: return a pandas DataFrame instead of polars.

    Returns:
        A polars (or pandas) DataFrame; seasons with no published asset are
        skipped with a warning rather than raising (404-safe).

        |col_name      |type   |
        |:-------------|:------|
        |game_id       |Int64  |
        |star          |Int64  |
        |team_id       |Int64  |
        |team          |String |
        |team_abbr     |String |
        |player_id     |Int64  |
        |first_name    |String |
        |last_name     |String |
        |jersey_number |Int64  |
        |position      |String |
        |is_goalie     |Int64  |
        |is_home       |Int64  |
        |goals         |Int64  |
        |assists       |Int64  |
        |points        |Int64  |
        |shots         |Int64  |
        |saves         |Int64  |
        |shots_against |Int64  |
        |goals_against |Int64  |
        |time_on_ice   |String |

    Raises:
        SeasonNotFoundError: if a requested season is below 2024.

    Example:
        Quick start::

            load_pwhl_three_stars(seasons=2024)
    """
    frames, missing = [], []
    for season in _as_season_list(seasons):
        if int(season) < 2024:
            raise SeasonNotFoundError("season cannot be less than 2024")
        df = _read_release_parquet(
            f"https://github.com/sportsdataverse/sportsdataverse-data/releases/download/pwhl_three_stars/three_stars_{season}.parquet"
        )
        if df is None:
            missing.append(season)
            continue
        frames.append(df)
    if missing:
        cli_warn("load_pwhl_three_stars: no data for season(s) {missing} (skipped)".format(missing=missing))
    # diagonal: per-season release schemas can drift (columns added/dropped
    # over the years) -- union columns, null-fill gaps.
    out = pl.concat(frames, how="diagonal_relaxed") if frames else pl.DataFrame()
    return out.to_pandas(use_pyarrow_extension_array=True) if return_as_pandas else out
