"""Metric registry -- one source for every published metric's display metadata.

``metrics.yaml`` holds one entry per BASE metric (``EPAplay``, ``success``,
``havoc``, ...): label, short label, axis label, format, polarity, family,
qualifier, glossary slug and per-basis variants. :func:`resolve` maps any
published column (``EPAplay_off_pass_rank``, ``adj_def_epa``, ``havoc_margin``)
onto its entry plus the column's side, phase, suffix and effective polarity.
:func:`render_ts` renders the registry as a TypeScript module for Game on Paper
and the web platform (``python -m sportsdataverse.registry --ts --target gop``).

Descriptions stay in ``manual_column_descriptions.yaml``; the registry is
display metadata only. PyYAML does not ship in the wheel, so the file is read
by :func:`parse`, a strict reader for the subset it is written in (pinned
against PyYAML in the test suite, like ``validation/thresholds.py``).

Example:
    Resolve a published column and read its effective polarity::

        from sportsdataverse.registry import resolve

        resolve("third_down_distance_def")["polarity"]  # 'higher' (flipped)
        resolve("EPAplay_off_pass")["short"]  # 'EPA/DB'

See Also:
    * ``docs/docs/architecture/metric-registry.md`` -- the resolver grammar
      and the TypeScript contract both consumers generate against.
"""

from __future__ import annotations

import hashlib
import json
import re
from functools import lru_cache
from importlib.metadata import PackageNotFoundError, version
from importlib.resources import files
from pathlib import Path
from typing import Any, Literal

__all__ = [
    "FAMILIES",
    "FORMATS",
    "KEYS",
    "PATH",
    "POLARITIES",
    "QUALIFIERS",
    "load_metric_registry",
    "parse",
    "render_ts",
    "resolve",
]

#: The packaged file, read through ``importlib.resources`` so it resolves in a wheel.
PATH = Path(str(files("sportsdataverse.registry") / "metrics.yaml"))

#: The ten keys every entry carries, in file order.
KEYS = ("key", "label", "short", "axis", "format", "polarity", "family", "qualifier", "glossary_slug", "variants")
#: GOP ``[1,2,2]`` / ``[1,2,1]`` / ``[100,2,1]`` / ``[1,2,0]``.
FORMATS = ("num2", "num1", "pct1", "int")
POLARITIES = ("higher", "lower")
FAMILIES = ("efficiency", "explosiveness", "volume", "tendency", "situational", "drive", "adjusted")
QUALIFIERS = ("dropbacks", "carries", "targets")

_SIDES = ("off", "def", "margin")
_PHASES = ("pass", "rush")
# longest first, so ``_pos_pct`` / ``_conf_pct`` are not read as ``_pct``
_SUFFIXES = ("_pos_pct", "_conf_pct", "_rank", "_pct", "_n")

_PLAY_WORD = re.compile(r"\bPlays?\b")
# GOP ``generateTeamMetricTitle``: a per-play title names the phase's play, any
# other title takes the phase as a prefix. ``short`` abbreviates the dropback.
_LABEL_WORDS = {
    "pass": ("Pass", {"Play": "Dropback", "Plays": "Dropbacks"}),
    "rush": ("Rush", {"Play": "Rush", "Plays": "Rushes"}),
}
_SHORT_WORDS = {
    "pass": ("Pass", {"Play": "DB", "Plays": "Dropbacks"}),
    "rush": _LABEL_WORDS["rush"],
}

_TS_HEADER = "// generated by sportsdataverse.registry"

# ``\t`` marks one indent level; ``render_ts`` swaps it for the target's width.
_TS_TEMPLATE = """export type Polarity = "higher" | "lower";
export type MetricFormat = "num2" | "num1" | "pct1" | "int";
export type MetricFamily = "efficiency" | "explosiveness" | "volume" | "tendency" | "situational" | "drive" | "adjusted";
export type MetricQualifier = "dropbacks" | "carries" | "targets" | null;
export type MetricSide = "off" | "def" | "margin";
export type MetricPhase = "pass" | "rush";

export interface MetricEntry {
\tkey: string;
\tlabel: string;
\tshort: string;
\taxis: string;
\tformat: MetricFormat;
\tpolarity: Polarity;
\tfamily: MetricFamily;
\tqualifier: MetricQualifier;
\tglossary_slug: string | null;
\tvariants: Record<string, string>;
}

/** A resolved column: its base entry, the column's side / phase / suffix and the EFFECTIVE polarity. */
export type ResolvedMetric = MetricEntry & { side?: MetricSide; phase?: MetricPhase; suffix?: string; polarity: Polarity };

export const METRICS: Record<string, MetricEntry> = __METRICS__;

const SUFFIXES = ["_pos_pct", "_conf_pct", "_rank", "_pct", "_n"];
const PHASES: MetricPhase[] = ["pass", "rush"];
const SIDES: MetricSide[] = ["off", "def", "margin"];
type PhaseWords = Record<MetricPhase, [string, Record<string, string>]>;
const LABEL_WORDS: PhaseWords = { pass: ["Pass", { Play: "Dropback", Plays: "Dropbacks" }], rush: ["Rush", { Play: "Rush", Plays: "Rushes" }] };
const SHORT_WORDS: PhaseWords = { pass: ["Pass", { Play: "DB", Plays: "Dropbacks" }], rush: LABEL_WORDS.rush };
const has = (key: string): boolean => Object.prototype.hasOwnProperty.call(METRICS, key);

function phased(text: string, phase: MetricPhase | undefined, words: PhaseWords): string {
\tif (!phase) return text;
\tconst [prefix, swap] = words[phase];
\tif (/\\bPlays?\\b/.test(text)) return text.replace(/\\bPlays?\\b/g, (m) => swap[m]);
\treturn text.startsWith(prefix) ? text : `${prefix} ${text}`;
}

function split(column: string): [string, MetricSide | undefined, MetricPhase | undefined, string | undefined] | null {
\tfor (const suffix of [...SUFFIXES, undefined]) {
\t\tif (suffix !== undefined && !column.endsWith(suffix)) continue;
\t\tlet stem = suffix ? column.slice(0, -suffix.length) : column;
\t\tconst phase = PHASES.find((p) => stem.endsWith(`_${p}`));
\t\tif (phase) stem = stem.slice(0, -phase.length - 1);
\t\tconst side = SIDES.find((s) => stem.endsWith(`_${s}`));
\t\tif (side) stem = stem.slice(0, -side.length - 1);
\t\tif (has(stem)) return [stem, side, phase, suffix];
\t\tif (!side && !phase) {
\t\t\t// prefix / infix sides: net_adj_epa, adj_off_epa, off_strength_faced
\t\t\tconst net = /^net_(.+)$/.exec(stem);
\t\t\tif (net && has(net[1])) return [net[1], "margin", undefined, suffix];
\t\t\tconst infix = /^(?:(.+)_)?(off|def)_(.+)$/.exec(stem);
\t\t\tif (infix) {
\t\t\t\tconst base = infix[1] ? `${infix[1]}_${infix[3]}` : infix[3];
\t\t\t\tif (has(base)) return [base, infix[2] as MetricSide, undefined, suffix];
\t\t\t}
\t\t}
\t}
\treturn null;
}

/** The entry behind a published column, or null. `_def` flips the polarity; a `_margin` is always higher-is-better. */
export function resolveMetric(column: string): ResolvedMetric | null {
\tconst found = split(column);
\tif (!found) return null;
\tconst [key, side, phase, suffix] = found;
\tconst entry = METRICS[key];
\tlet polarity: Polarity = entry.polarity;
\tif (side === "def") polarity = polarity === "higher" ? "lower" : "higher";
\telse if (side === "margin") polarity = "higher";
\tconst out: ResolvedMetric = {
\t\t...entry,
\t\tvariants: { ...entry.variants },
\t\tlabel: phased(entry.label, phase, LABEL_WORDS),
\t\tshort: phased(entry.short, phase, SHORT_WORDS),
\t\tpolarity,
\t};
\tif (side) out.side = side;
\tif (phase) out.phase = phase;
\tif (suffix) out.suffix = suffix;
\treturn out;
}
"""


def _scalar(text: str, line_no: int) -> str | dict[str, str] | None:
    if text in ("null", "~"):
        return None
    if text == "{}":
        return {}
    if len(text) >= 2 and text[0] == text[-1] and text[0] in "\"'":
        return text[1:-1]
    if not text or text[0] in "[{\"'&*!|>%@`" or " #" in text:
        raise ValueError(f"metrics.yaml line {line_no}: {text!r} is not a plain scalar")
    return text


def parse(text: str) -> list[dict[str, Any]]:
    """Entries from the constrained YAML ``metrics.yaml`` is written in.

    Args:
        text: the file's contents.

    Returns:
        list[dict]: one dict per ``- key:`` entry, in file order; a ``variants:``
        block becomes a nested ``dict[str, str]``.

    Raises:
        ValueError: If a line is not a comment, a blank, an entry opener
            ``- key: NAME``, a two-space ``field: value`` or a four-space row of
            an open ``variants:`` block -- the reader never guesses at a
            construct it was not written for.
    """
    entries: list[dict[str, Any]] = []
    block: dict[str, Any] | None = None
    for line_no, raw in enumerate(text.splitlines(), 1):
        if not raw.strip() or raw.lstrip().startswith("#"):
            continue
        indent = len(raw) - len(raw.lstrip(" "))
        body = raw.strip()
        if indent == 0:
            if not body.startswith("- "):
                raise ValueError(f"metrics.yaml line {line_no}: expected an entry opener '- key: ...'")
            entries.append({})
            body, indent = body[2:].strip(), 2
        name, sep, value = body.partition(":")
        if not sep or not name or (value and not value.startswith(" ")):
            raise ValueError(f"metrics.yaml line {line_no}: expected 'name: value'")
        name, value = name.strip(), value.strip()
        if indent == 2 and entries:
            block = None
            if value == "":
                block = entries[-1][name] = {}
            else:
                entries[-1][name] = _scalar(value, line_no)
        elif indent == 4 and block is not None:
            block[name] = _scalar(value, line_no)
        else:
            raise ValueError(f"metrics.yaml line {line_no}: unexpected indentation")
    return entries


def _validate(entries: list[dict[str, Any]]) -> None:
    seen: set[str] = set()
    for e in entries:
        key = e.get("key")
        missing, extra = set(KEYS) - set(e), set(e) - set(KEYS)
        if missing or extra:
            raise ValueError(f"metrics.yaml entry {key!r}: missing {sorted(missing)}, unexpected {sorted(extra)}")
        if key in seen:
            raise ValueError(f"metrics.yaml: duplicate key {key!r}")
        for field in ("key", "label", "short", "axis"):
            if not isinstance(e[field], str) or not e[field]:
                raise ValueError(f"metrics.yaml entry {key!r}: {field} must be a non-empty string")
        for field, allowed in (("format", FORMATS), ("polarity", POLARITIES), ("family", FAMILIES)):
            if e[field] not in allowed:
                raise ValueError(f"metrics.yaml entry {key!r}: {field} {e[field]!r} not in {allowed}")
        if e["qualifier"] is not None and e["qualifier"] not in QUALIFIERS:
            raise ValueError(f"metrics.yaml entry {key!r}: qualifier {e['qualifier']!r} not in {QUALIFIERS}")
        if e["glossary_slug"] is not None and not isinstance(e["glossary_slug"], str):
            raise ValueError(f"metrics.yaml entry {key!r}: glossary_slug must be a string or null")
        if not isinstance(e["variants"], dict) or not all(isinstance(v, str) for v in e["variants"].values()):
            raise ValueError(f"metrics.yaml entry {key!r}: variants must map basis -> metric key")
        seen.add(e["key"])
    for e in entries:
        unknown = set(e["variants"].values()) - seen
        if unknown:
            raise ValueError(f"metrics.yaml entry {e['key']!r}: variants name unknown metrics {sorted(unknown)}")


def load_metric_registry() -> list[dict[str, Any]]:
    """The validated entries of the packaged ``metrics.yaml``, in file order.

    Returns:
        list[dict]: one dict per base metric carrying exactly :data:`KEYS` --
        ``key``, ``label``, ``short``, ``axis``, ``format``, ``polarity``,
        ``family``, ``qualifier``, ``glossary_slug`` and ``variants``.

    Raises:
        ValueError: If the file fails validation -- a missing or unexpected key,
            an unknown ``format`` / ``polarity`` / ``family`` / ``qualifier``, a
            duplicate key, or a ``variants`` value naming an unknown metric.
    """
    entries = parse(PATH.read_text(encoding="utf-8"))
    _validate(entries)
    return entries


@lru_cache(maxsize=1)
def _index() -> dict[str, dict[str, Any]]:
    return {e["key"]: e for e in load_metric_registry()}


def _split(column: str) -> tuple[str, str | None, str | None, str | None] | None:
    """``(key, side, phase, suffix)`` for a published column, or None."""
    index = _index()
    for suffix in (*_SUFFIXES, None):
        if suffix is not None and not column.endswith(suffix):
            continue
        stem = column[: -len(suffix)] if suffix else column
        phase = next((p for p in _PHASES if stem.endswith(f"_{p}")), None)
        if phase:
            stem = stem[: -len(phase) - 1]
        side = next((s for s in _SIDES if stem.endswith(f"_{s}")), None)
        if side:
            stem = stem[: -len(side) - 1]
        if stem in index:
            return stem, side, phase, suffix
        if side is None and phase is None:
            # prefix / infix sides: net_adj_epa, adj_off_epa, off_strength_faced
            net = re.fullmatch(r"net_(.+)", stem)
            if net and net[1] in index:
                return net[1], "margin", None, suffix
            infix = re.fullmatch(r"(?:(.+)_)?(off|def)_(.+)", stem)
            if infix:
                base = f"{infix[1]}_{infix[3]}" if infix[1] else infix[3]
                if base in index:
                    return base, infix[2], None, suffix
    return None


def _phased(text: str, phase: str | None, words: dict[str, tuple[str, dict[str, str]]]) -> str:
    if phase is None:
        return text
    prefix, swap = words[phase]
    if _PLAY_WORD.search(text):
        return _PLAY_WORD.sub(lambda m: swap[m[0]], text)
    return text if text.startswith(prefix) else f"{prefix} {text}"


def resolve(column: str) -> dict[str, Any] | None:
    """The registry entry behind a published column, with the column's parts.

    The grammar is ``base [_off|_def|_margin] [_pass|_rush]
    [_rank|_pct|_n|_pos_pct|_conf_pct]``, plus the prefix / infix spellings
    the adjusted columns use (``adj_off_epa``, ``net_adj_epa``,
    ``off_strength_faced``).

    Args:
        column: a published column name, e.g. ``"EPAplay_off_pass_rank"``.

    Returns:
        dict | None: the entry's ten keys plus ``side``, ``phase``, ``suffix``
        (each ``None`` when absent) and the EFFECTIVE ``polarity`` -- ``_def``
        flips the base's, a ``_margin`` is always ``higher`` (every producer
        margin is good-minus-bad), anything else keeps it. ``label`` and
        ``short`` are rewritten for a phase (``EPA/Play`` -> ``EPA/DB`` /
        ``EPA/Rush``, ``SR%`` -> ``Pass SR%``). ``None`` for an unknown column.
    """
    found = _split(column)
    if found is None:
        return None
    key, side, phase, suffix = found
    entry = _index()[key]
    polarity = entry["polarity"]
    if side == "def":
        polarity = "lower" if polarity == "higher" else "higher"
    elif side == "margin":
        polarity = "higher"
    return {
        **entry,
        "variants": dict(entry["variants"]),
        "label": _phased(entry["label"], phase, _LABEL_WORDS),
        "short": _phased(entry["short"], phase, _SHORT_WORDS),
        "side": side,
        "phase": phase,
        "suffix": suffix,
        "polarity": polarity,
    }


def _version() -> str:
    try:
        return version("sportsdataverse")
    except PackageNotFoundError:
        return "unknown"


def render_ts(entries: list[dict[str, Any]], *, target: Literal["gop", "web"]) -> str:
    """The registry as a deterministic TypeScript module.

    Args:
        entries: what :func:`load_metric_registry` returned.
        target: ``"gop"`` (4-space indent, Game on Paper's astro style) or
            ``"web"`` (2-space, the platform's prettier style). The exported
            shape is identical: ``METRICS: Record<string, MetricEntry>`` and
            ``resolveMetric(column)``, mirroring :func:`resolve`.

    Returns:
        str: the module, headed by ``// generated by sportsdataverse.registry``,
        the sdv-py version and ``// sha256:`` of everything below the three
        header lines, so a consumer can verify its copy was not hand-edited.
    """
    pad = {"gop": "    ", "web": "  "}[target]
    data = json.dumps({e["key"]: e for e in entries}, indent=len(pad), ensure_ascii=False)
    body = _TS_TEMPLATE.replace("\t", pad).replace("__METRICS__", data)
    digest = hashlib.sha256(body.encode("utf-8")).hexdigest()
    return f"{_TS_HEADER}\n// sportsdataverse {_version()} -- target {target}\n// sha256: {digest}\n{body}"
