# GENERATED by tools/codegen/generate.py -- DO NOT EDIT.
# Source: tools/codegen/endpoints/releases.yaml
"""sportsdataverse.wnba dataset loaders (sportsdataverse-data releases). Generated."""

from __future__ import annotations

import polars as pl

from sportsdataverse._codegen_runtime import (
    SeasonNotFoundError,  # noqa: F401
    _as_season_list,
    _read_release_parquet,
    cli_warn,
)

__all__ = [
    "load_wnba_pbp",
    "load_wnba_player_boxscore",
    "load_wnba_schedule",
    "load_wnba_team_boxscore",
    "load_wnba_draft",
    "load_wnba_game_rosters",
    "load_wnba_officials",
    "load_wnba_player_season_stats",
    "load_wnba_rosters",
    "load_wnba_shots",
    "load_wnba_standings",
    "load_wnba_team_season_stats",
    "load_wnba_stats_coaches",
    "load_wnba_stats_draft",
    "load_wnba_stats_game_rosters",
    "load_wnba_stats_lineups",
    "load_wnba_stats_officials",
    "load_wnba_stats_pbp",
    "load_wnba_stats_player_game_logs",
    "load_wnba_stats_player_season_stats",
    "load_wnba_stats_rosters",
    "load_wnba_stats_schedules",
    "load_wnba_stats_shots",
    "load_wnba_stats_standings",
    "load_wnba_stats_team_season_stats",
]


def load_wnba_pbp(seasons, return_as_pandas: bool = False):
    """Load espn_wnba_pbp (sportsdataverse-data release).

    Source: https://github.com/sportsdataverse/sportsdataverse-data/releases/tag/espn_wnba_pbp

    Args:
        seasons: an int or iterable of seasons (>= 2002).
        return_as_pandas: return a pandas DataFrame instead of polars.

    Returns:
        A polars (or pandas) DataFrame; seasons with no published asset are
        skipped with a warning rather than raising (404-safe).

        |col_name                        |type                                                   |
        |:-------------------------------|:------------------------------------------------------|
        |id                              |Float64                                                |
        |sequence_number                 |String                                                 |
        |type_id                         |Int32                                                  |
        |type_text                       |String                                                 |
        |text                            |String                                                 |
        |away_score                      |Int32                                                  |
        |home_score                      |Int32                                                  |
        |period_number                   |Int32                                                  |
        |period_display_value            |String                                                 |
        |clock_display_value             |String                                                 |
        |scoring_play                    |Boolean                                                |
        |score_value                     |Int32                                                  |
        |shooting_play                   |Boolean                                                |
        |coordinate_x_raw                |Float64                                                |
        |coordinate_y_raw                |Float64                                                |
        |season                          |Int32                                                  |
        |season_type                     |Int32                                                  |
        |away_team_id                    |Int32                                                  |
        |away_team_name                  |String                                                 |
        |away_team_mascot                |String                                                 |
        |away_team_abbrev                |String                                                 |
        |away_team_name_alt              |String                                                 |
        |home_team_id                    |Int32                                                  |
        |home_team_name                  |String                                                 |
        |home_team_mascot                |String                                                 |
        |home_team_abbrev                |String                                                 |
        |home_team_name_alt              |String                                                 |
        |home_team_spread                |Float64                                                |
        |game_spread                     |Float64                                                |
        |home_favorite                   |Boolean                                                |
        |game_spread_available           |Boolean                                                |
        |game_id                         |Int32                                                  |
        |qtr                             |Int32                                                  |
        |time                            |String                                                 |
        |clock_minutes                   |Int32                                                  |
        |clock_seconds                   |Float64                                                |
        |half                            |String                                                 |
        |game_half                       |String                                                 |
        |lead_qtr                        |Int32                                                  |
        |lead_game_half                  |String                                                 |
        |start_quarter_seconds_remaining |Int32                                                  |
        |start_half_seconds_remaining    |Int32                                                  |
        |start_game_seconds_remaining    |Int32                                                  |
        |game_play_number                |Int32                                                  |
        |end_quarter_seconds_remaining   |Int32                                                  |
        |end_half_seconds_remaining      |Int32                                                  |
        |end_game_seconds_remaining      |Int32                                                  |
        |period                          |Int32                                                  |
        |team_id                         |Int32                                                  |
        |athlete_id_1                    |Int32                                                  |
        |athlete_id_2                    |Int32                                                  |
        |athlete_id_3                    |Int32                                                  |
        |lag_qtr                         |Int32                                                  |
        |lag_game_half                   |String                                                 |
        |coordinate_x                    |Float64                                                |
        |coordinate_y                    |Float64                                                |
        |game_date                       |Date                                                   |
        |game_date_time                  |Datetime(time_unit='us', time_zone='America/New_York') |
        |type_abbreviation               |String                                                 |

    Example:
        Quick start::

            load_wnba_pbp(seasons=2024)
    """
    frames, missing = [], []
    for season in _as_season_list(seasons):
        if int(season) < 2002:
            raise SeasonNotFoundError("season cannot be less than 2002")
        df = _read_release_parquet(
            f"https://github.com/sportsdataverse/sportsdataverse-data/releases/download/espn_wnba_pbp/play_by_play_{season}.parquet"
        )
        if df is None:
            missing.append(season)
            continue
        frames.append(df)
    if missing:
        cli_warn("load_wnba_pbp: no data for season(s) {missing} (skipped)".format(missing=missing))
    out = pl.concat(frames, how="vertical_relaxed") if frames else pl.DataFrame()
    return out.to_pandas(use_pyarrow_extension_array=True) if return_as_pandas else out


def load_wnba_player_boxscore(seasons, return_as_pandas: bool = False):
    """Load espn_wnba_player_boxscores (sportsdataverse-data release).

    Source: https://github.com/sportsdataverse/sportsdataverse-data/releases/tag/espn_wnba_player_boxscores

    Args:
        seasons: an int or iterable of seasons (>= 2002).
        return_as_pandas: return a pandas DataFrame instead of polars.

    Returns:
        A polars (or pandas) DataFrame; seasons with no published asset are
        skipped with a warning rather than raising (404-safe).

        |col_name                      |type    |
        |:-----------------------------|:-------|
        |athlete_display_name          |String  |
        |team_short_display_name       |String  |
        |min                           |String  |
        |fg                            |String  |
        |fg3                           |String  |
        |ft                            |String  |
        |oreb                          |String  |
        |dreb                          |String  |
        |reb                           |String  |
        |ast                           |String  |
        |stl                           |String  |
        |blk                           |String  |
        |to                            |String  |
        |pf                            |String  |
        |plus_minus                    |String  |
        |pts                           |String  |
        |starter                       |Boolean |
        |ejected                       |Boolean |
        |did_not_play                  |Boolean |
        |active                        |Boolean |
        |athlete_jersey                |String  |
        |athlete_id                    |String  |
        |athlete_short_name            |String  |
        |athlete_position_name         |String  |
        |athlete_position_abbreviation |String  |
        |team_name                     |String  |
        |team_logo                     |String  |
        |team_id                       |String  |
        |team_abbreviation             |String  |
        |team_color                    |String  |
        |game_id                       |Int32   |
        |season                        |Int32   |
        |season_type                   |Int32   |
        |game_date                     |Date    |
        |athlete_headshot_href         |String  |

    Example:
        Quick start::

            load_wnba_player_boxscore(seasons=2024)
    """
    frames, missing = [], []
    for season in _as_season_list(seasons):
        if int(season) < 2002:
            raise SeasonNotFoundError("season cannot be less than 2002")
        df = _read_release_parquet(
            f"https://github.com/sportsdataverse/sportsdataverse-data/releases/download/espn_wnba_player_boxscores/player_box_{season}.parquet"
        )
        if df is None:
            missing.append(season)
            continue
        frames.append(df)
    if missing:
        cli_warn("load_wnba_player_boxscore: no data for season(s) {missing} (skipped)".format(missing=missing))
    out = pl.concat(frames, how="vertical_relaxed") if frames else pl.DataFrame()
    return out.to_pandas(use_pyarrow_extension_array=True) if return_as_pandas else out


def load_wnba_schedule(seasons, return_as_pandas: bool = False):
    """Load espn_wnba_schedules (sportsdataverse-data release).

    Source: https://github.com/sportsdataverse/sportsdataverse-data/releases/tag/espn_wnba_schedules

    Args:
        seasons: an int or iterable of seasons (>= 2002).
        return_as_pandas: return a pandas DataFrame instead of polars.

    Returns:
        A polars (or pandas) DataFrame; seasons with no published asset are
        skipped with a warning rather than raising (404-safe).

        |col_name                  |type                                                   |
        |:-------------------------|:------------------------------------------------------|
        |id                        |Int32                                                  |
        |uid                       |String                                                 |
        |date                      |String                                                 |
        |attendance                |Float64                                                |
        |time_valid                |Boolean                                                |
        |neutral_site              |Boolean                                                |
        |conference_competition    |Boolean                                                |
        |recent                    |Boolean                                                |
        |start_date                |String                                                 |
        |notes_type                |String                                                 |
        |notes_headline            |String                                                 |
        |type_id                   |Int32                                                  |
        |type_abbreviation         |String                                                 |
        |status_clock              |Float64                                                |
        |status_display_clock      |String                                                 |
        |status_period             |Float64                                                |
        |status_type_id            |Int32                                                  |
        |status_type_name          |String                                                 |
        |status_type_state         |String                                                 |
        |status_type_completed     |Boolean                                                |
        |status_type_description   |String                                                 |
        |status_type_detail        |String                                                 |
        |status_type_short_detail  |String                                                 |
        |format_regulation_periods |Float64                                                |
        |home_id                   |Int32                                                  |
        |home_uid                  |String                                                 |
        |home_location             |String                                                 |
        |home_name                 |String                                                 |
        |home_abbreviation         |String                                                 |
        |home_display_name         |String                                                 |
        |home_short_display_name   |String                                                 |
        |home_color                |String                                                 |
        |home_alternate_color      |String                                                 |
        |home_is_active            |Boolean                                                |
        |home_venue_id             |Int32                                                  |
        |home_logo                 |String                                                 |
        |home_score                |Int32                                                  |
        |home_winner               |Boolean                                                |
        |away_id                   |Int32                                                  |
        |away_uid                  |String                                                 |
        |away_location             |String                                                 |
        |away_name                 |String                                                 |
        |away_abbreviation         |String                                                 |
        |away_display_name         |String                                                 |
        |away_short_display_name   |String                                                 |
        |away_is_active            |Boolean                                                |
        |away_venue_id             |Int32                                                  |
        |away_score                |Int32                                                  |
        |away_winner               |Boolean                                                |
        |game_id                   |Int32                                                  |
        |season                    |Int32                                                  |
        |season_type               |Int32                                                  |
        |venue_id                  |Int32                                                  |
        |venue_full_name           |String                                                 |
        |venue_address_city        |String                                                 |
        |venue_address_state       |String                                                 |
        |venue_capacity            |Float64                                                |
        |venue_indoor              |Boolean                                                |
        |away_color                |String                                                 |
        |away_alternate_color      |String                                                 |
        |away_logo                 |String                                                 |
        |status_type_alt_detail    |String                                                 |
        |game_json                 |Boolean                                                |
        |game_json_url             |String                                                 |
        |game_date_time            |Datetime(time_unit='us', time_zone='America/New_York') |
        |game_date                 |Date                                                   |
        |PBP                       |Boolean                                                |
        |team_box                  |Boolean                                                |
        |player_box                |Boolean                                                |

    Example:
        Quick start::

            load_wnba_schedule(seasons=2024)
    """
    frames, missing = [], []
    for season in _as_season_list(seasons):
        if int(season) < 2002:
            raise SeasonNotFoundError("season cannot be less than 2002")
        df = _read_release_parquet(
            f"https://github.com/sportsdataverse/sportsdataverse-data/releases/download/espn_wnba_schedules/wnba_schedule_{season}.parquet"
        )
        if df is None:
            missing.append(season)
            continue
        frames.append(df)
    if missing:
        cli_warn("load_wnba_schedule: no data for season(s) {missing} (skipped)".format(missing=missing))
    out = pl.concat(frames, how="vertical_relaxed") if frames else pl.DataFrame()
    return out.to_pandas(use_pyarrow_extension_array=True) if return_as_pandas else out


def load_wnba_team_boxscore(seasons, return_as_pandas: bool = False):
    """Load espn_wnba_team_boxscores (sportsdataverse-data release).

    Source: https://github.com/sportsdataverse/sportsdataverse-data/releases/tag/espn_wnba_team_boxscores

    Args:
        seasons: an int or iterable of seasons (>= 2002).
        return_as_pandas: return a pandas DataFrame instead of polars.

    Returns:
        A polars (or pandas) DataFrame; seasons with no published asset are
        skipped with a warning rather than raising (404-safe).

        |col_name                          |type                                                   |
        |:---------------------------------|:------------------------------------------------------|
        |game_id                           |Int32                                                  |
        |season                            |Int32                                                  |
        |season_type                       |Int32                                                  |
        |game_date                         |Date                                                   |
        |game_date_time                    |Datetime(time_unit='us', time_zone='America/New_York') |
        |team_id                           |Int32                                                  |
        |team_uid                          |String                                                 |
        |team_slug                         |String                                                 |
        |team_location                     |String                                                 |
        |team_name                         |String                                                 |
        |team_abbreviation                 |String                                                 |
        |team_display_name                 |String                                                 |
        |team_short_display_name           |String                                                 |
        |team_color                        |String                                                 |
        |team_alternate_color              |String                                                 |
        |team_logo                         |String                                                 |
        |team_home_away                    |String                                                 |
        |team_score                        |Int32                                                  |
        |team_winner                       |Boolean                                                |
        |assists                           |Int32                                                  |
        |blocks                            |Int32                                                  |
        |defensive_rebounds                |Int32                                                  |
        |fast_break_points                 |String                                                 |
        |field_goal_pct                    |Float64                                                |
        |field_goals_made                  |Int32                                                  |
        |field_goals_attempted             |Int32                                                  |
        |flagrant_fouls                    |Int32                                                  |
        |fouls                             |Int32                                                  |
        |free_throw_pct                    |Float64                                                |
        |free_throws_made                  |Int32                                                  |
        |free_throws_attempted             |Int32                                                  |
        |largest_lead                      |String                                                 |
        |offensive_rebounds                |Int32                                                  |
        |points_in_paint                   |String                                                 |
        |steals                            |Int32                                                  |
        |team_turnovers                    |Int32                                                  |
        |technical_fouls                   |Int32                                                  |
        |three_point_field_goal_pct        |Float64                                                |
        |three_point_field_goals_made      |Int32                                                  |
        |three_point_field_goals_attempted |Int32                                                  |
        |total_rebounds                    |Int32                                                  |
        |total_technical_fouls             |Int32                                                  |
        |total_turnovers                   |Int32                                                  |
        |turnover_points                   |String                                                 |
        |turnovers                         |Int32                                                  |
        |opponent_team_id                  |Int32                                                  |
        |opponent_team_uid                 |String                                                 |
        |opponent_team_slug                |String                                                 |
        |opponent_team_location            |String                                                 |
        |opponent_team_name                |String                                                 |
        |opponent_team_abbreviation        |String                                                 |
        |opponent_team_display_name        |String                                                 |
        |opponent_team_short_display_name  |String                                                 |
        |opponent_team_color               |String                                                 |
        |opponent_team_alternate_color     |String                                                 |
        |opponent_team_logo                |String                                                 |
        |opponent_team_score               |Int32                                                  |

    Example:
        Quick start::

            load_wnba_team_boxscore(seasons=2024)
    """
    frames, missing = [], []
    for season in _as_season_list(seasons):
        if int(season) < 2002:
            raise SeasonNotFoundError("season cannot be less than 2002")
        df = _read_release_parquet(
            f"https://github.com/sportsdataverse/sportsdataverse-data/releases/download/espn_wnba_team_boxscores/team_box_{season}.parquet"
        )
        if df is None:
            missing.append(season)
            continue
        frames.append(df)
    if missing:
        cli_warn("load_wnba_team_boxscore: no data for season(s) {missing} (skipped)".format(missing=missing))
    out = pl.concat(frames, how="vertical_relaxed") if frames else pl.DataFrame()
    return out.to_pandas(use_pyarrow_extension_array=True) if return_as_pandas else out


def load_wnba_draft(seasons, return_as_pandas: bool = False):
    """Load espn_wnba_draft (sportsdataverse-data release).

    Source: https://github.com/sportsdataverse/sportsdataverse-data/releases/tag/espn_wnba_draft

    Args:
        seasons: an int or iterable of seasons (>= 2026).
        return_as_pandas: return a pandas DataFrame instead of polars.

    Returns:
        A polars (or pandas) DataFrame; seasons with no published asset are
        skipped with a warning rather than raising (404-safe).

        |col_name                      |type   |
        |:-----------------------------|:------|
        |season                        |Int32  |
        |round                         |Int32  |
        |round_display_name            |String |
        |pick                          |Int32  |
        |overall_pick                  |Int32  |
        |pick_traded                   |String |
        |pick_notes                    |String |
        |athlete_id                    |Int32  |
        |athlete_uid                   |String |
        |athlete_guid                  |String |
        |athlete_first_name            |String |
        |athlete_last_name             |String |
        |athlete_full_name             |String |
        |athlete_display_name          |String |
        |athlete_short_name            |String |
        |athlete_height                |String |
        |athlete_weight                |String |
        |athlete_position_abbreviation |String |
        |athlete_position_name         |String |
        |athlete_headshot_href         |String |
        |college_id                    |Int32  |
        |college_name                  |String |
        |college_short_name            |String |
        |college_abbreviation          |String |
        |team_id                       |Int32  |
        |team_uid                      |String |
        |team_slug                     |String |
        |team_location                 |String |
        |team_name                     |String |
        |team_abbreviation             |String |
        |team_display_name             |String |
        |team_short_display_name       |String |
        |team_color                    |String |
        |team_alternate_color          |String |
        |team_logo                     |String |

    Example:
        Quick start::

            load_wnba_draft(seasons=2026)
    """
    frames, missing = [], []
    for season in _as_season_list(seasons):
        if int(season) < 2026:
            raise SeasonNotFoundError("season cannot be less than 2026")
        df = _read_release_parquet(
            f"https://github.com/sportsdataverse/sportsdataverse-data/releases/download/espn_wnba_draft/draft_{season}.parquet"
        )
        if df is None:
            missing.append(season)
            continue
        frames.append(df)
    if missing:
        cli_warn("load_wnba_draft: no data for season(s) {missing} (skipped)".format(missing=missing))
    out = pl.concat(frames, how="vertical_relaxed") if frames else pl.DataFrame()
    return out.to_pandas(use_pyarrow_extension_array=True) if return_as_pandas else out


def load_wnba_game_rosters(seasons, return_as_pandas: bool = False):
    """Load espn_wnba_game_rosters (sportsdataverse-data release).

    Source: https://github.com/sportsdataverse/sportsdataverse-data/releases/tag/espn_wnba_game_rosters

    Args:
        seasons: an int or iterable of seasons (>= 2024).
        return_as_pandas: return a pandas DataFrame instead of polars.

    Returns:
        A polars (or pandas) DataFrame; seasons with no published asset are
        skipped with a warning rather than raising (404-safe).

        |col_name             |type    |
        |:--------------------|:-------|
        |season               |Int32   |
        |game_id              |String  |
        |team_id              |Int32   |
        |team_slug            |String  |
        |team_abbreviation    |String  |
        |team_display_name    |String  |
        |home_away            |String  |
        |athlete_id           |Int32   |
        |athlete_uid          |String  |
        |athlete_guid         |String  |
        |athlete_display_name |String  |
        |athlete_short_name   |String  |
        |athlete_first_name   |String  |
        |athlete_last_name    |String  |
        |athlete_jersey       |String  |
        |athlete_position     |String  |
        |athlete_headshot     |String  |
        |starter              |Boolean |
        |did_not_play         |Boolean |
        |active               |Boolean |
        |ejected              |Boolean |
        |reason               |String  |

    Example:
        Quick start::

            load_wnba_game_rosters(seasons=2024)
    """
    frames, missing = [], []
    for season in _as_season_list(seasons):
        if int(season) < 2024:
            raise SeasonNotFoundError("season cannot be less than 2024")
        df = _read_release_parquet(
            f"https://github.com/sportsdataverse/sportsdataverse-data/releases/download/espn_wnba_game_rosters/game_rosters_{season}.parquet"
        )
        if df is None:
            missing.append(season)
            continue
        frames.append(df)
    if missing:
        cli_warn("load_wnba_game_rosters: no data for season(s) {missing} (skipped)".format(missing=missing))
    out = pl.concat(frames, how="vertical_relaxed") if frames else pl.DataFrame()
    return out.to_pandas(use_pyarrow_extension_array=True) if return_as_pandas else out


def load_wnba_officials(seasons, return_as_pandas: bool = False):
    """Load espn_wnba_officials (sportsdataverse-data release).

    Source: https://github.com/sportsdataverse/sportsdataverse-data/releases/tag/espn_wnba_officials

    Args:
        seasons: an int or iterable of seasons (>= 2024).
        return_as_pandas: return a pandas DataFrame instead of polars.

    Returns:
        A polars (or pandas) DataFrame; seasons with no published asset are
        skipped with a warning rather than raising (404-safe).

        |col_name              |type   |
        |:---------------------|:------|
        |season                |Int32  |
        |game_id               |String |
        |official_id           |Int32  |
        |official_uid          |String |
        |official_full_name    |String |
        |official_display_name |String |
        |official_first_name   |String |
        |official_last_name    |String |
        |official_order        |Int32  |
        |position_name         |String |
        |position_display_name |String |

    Example:
        Quick start::

            load_wnba_officials(seasons=2024)
    """
    frames, missing = [], []
    for season in _as_season_list(seasons):
        if int(season) < 2024:
            raise SeasonNotFoundError("season cannot be less than 2024")
        df = _read_release_parquet(
            f"https://github.com/sportsdataverse/sportsdataverse-data/releases/download/espn_wnba_officials/officials_{season}.parquet"
        )
        if df is None:
            missing.append(season)
            continue
        frames.append(df)
    if missing:
        cli_warn("load_wnba_officials: no data for season(s) {missing} (skipped)".format(missing=missing))
    out = pl.concat(frames, how="vertical_relaxed") if frames else pl.DataFrame()
    return out.to_pandas(use_pyarrow_extension_array=True) if return_as_pandas else out


def load_wnba_player_season_stats(seasons, return_as_pandas: bool = False):
    """Load espn_wnba_player_season_stats (sportsdataverse-data release).

    Source: https://github.com/sportsdataverse/sportsdataverse-data/releases/tag/espn_wnba_player_season_stats

    Args:
        seasons: an int or iterable of seasons (>= 2024).
        return_as_pandas: return a pandas DataFrame instead of polars.

    Returns:
        A polars (or pandas) DataFrame; seasons with no published asset are
        skipped with a warning rather than raising (404-safe).

        |col_name                      |type    |
        |:-----------------------------|:-------|
        |season                        |Int32   |
        |athlete_id                    |Int32   |
        |athlete_display_name          |String  |
        |athlete_first_name            |String  |
        |athlete_last_name             |String  |
        |athlete_position_abbreviation |String  |
        |athlete_jersey                |String  |
        |team_id                       |Int32   |
        |team_display_name             |String  |
        |category                      |String  |
        |stat_label                    |String  |
        |stat_name                     |String  |
        |stat_display_name             |String  |
        |stat_description              |String  |
        |display_value                 |String  |
        |value                         |Float64 |

    Example:
        Quick start::

            load_wnba_player_season_stats(seasons=2024)
    """
    frames, missing = [], []
    for season in _as_season_list(seasons):
        if int(season) < 2024:
            raise SeasonNotFoundError("season cannot be less than 2024")
        df = _read_release_parquet(
            f"https://github.com/sportsdataverse/sportsdataverse-data/releases/download/espn_wnba_player_season_stats/player_season_stats_{season}.parquet"
        )
        if df is None:
            missing.append(season)
            continue
        frames.append(df)
    if missing:
        cli_warn("load_wnba_player_season_stats: no data for season(s) {missing} (skipped)".format(missing=missing))
    out = pl.concat(frames, how="vertical_relaxed") if frames else pl.DataFrame()
    return out.to_pandas(use_pyarrow_extension_array=True) if return_as_pandas else out


def load_wnba_rosters(seasons, return_as_pandas: bool = False):
    """Load espn_wnba_rosters (sportsdataverse-data release).

    Source: https://github.com/sportsdataverse/sportsdataverse-data/releases/tag/espn_wnba_rosters

    Args:
        seasons: an int or iterable of seasons (>= 2024).
        return_as_pandas: return a pandas DataFrame instead of polars.

    Returns:
        A polars (or pandas) DataFrame; seasons with no published asset are
        skipped with a warning rather than raising (404-safe).

        |col_name                 |type   |
        |:------------------------|:------|
        |season                   |Int32  |
        |team_id                  |Int32  |
        |team_slug                |String |
        |team_abbreviation        |String |
        |team_display_name        |String |
        |team_short_display_name  |String |
        |team_color               |String |
        |team_alternate_color     |String |
        |team_logo                |String |
        |athlete_id               |String |
        |uid                      |String |
        |guid                     |String |
        |full_name                |String |
        |display_name             |String |
        |short_name               |String |
        |first_name               |String |
        |last_name                |String |
        |jersey                   |String |
        |position_abbreviation    |String |
        |position_name            |String |
        |position_id              |String |
        |height                   |String |
        |weight                   |String |
        |age                      |String |
        |date_of_birth            |String |
        |birth_place_city         |String |
        |birth_place_state        |String |
        |birth_place_country      |String |
        |experience_years         |String |
        |experience_display_value |String |
        |headshot_href            |String |
        |headshot_alt             |String |
        |link_web                 |String |
        |status_id                |String |
        |status_name              |String |
        |status_type              |String |

    Example:
        Quick start::

            load_wnba_rosters(seasons=2024)
    """
    frames, missing = [], []
    for season in _as_season_list(seasons):
        if int(season) < 2024:
            raise SeasonNotFoundError("season cannot be less than 2024")
        df = _read_release_parquet(
            f"https://github.com/sportsdataverse/sportsdataverse-data/releases/download/espn_wnba_rosters/rosters_{season}.parquet"
        )
        if df is None:
            missing.append(season)
            continue
        frames.append(df)
    if missing:
        cli_warn("load_wnba_rosters: no data for season(s) {missing} (skipped)".format(missing=missing))
    out = pl.concat(frames, how="vertical_relaxed") if frames else pl.DataFrame()
    return out.to_pandas(use_pyarrow_extension_array=True) if return_as_pandas else out


def load_wnba_shots(seasons, return_as_pandas: bool = False):
    """Load espn_wnba_shots (sportsdataverse-data release).

    Source: https://github.com/sportsdataverse/sportsdataverse-data/releases/tag/espn_wnba_shots

    Args:
        seasons: an int or iterable of seasons (>= 2024).
        return_as_pandas: return a pandas DataFrame instead of polars.

    Returns:
        A polars (or pandas) DataFrame; seasons with no published asset are
        skipped with a warning rather than raising (404-safe).

        |col_name            |type    |
        |:-------------------|:-------|
        |game_id             |Int32   |
        |season              |Int32   |
        |period_number       |Int32   |
        |clock_display_value |String  |
        |team_id             |Int32   |
        |athlete_id_1        |Int32   |
        |athlete_id_2        |Int32   |
        |type_id             |Int32   |
        |type_text           |String  |
        |scoring_play        |Boolean |
        |score_value         |Int32   |
        |coordinate_x        |Float64 |
        |coordinate_y        |Float64 |
        |coordinate_x_raw    |Float64 |
        |coordinate_y_raw    |Float64 |

    Example:
        Quick start::

            load_wnba_shots(seasons=2024)
    """
    frames, missing = [], []
    for season in _as_season_list(seasons):
        if int(season) < 2024:
            raise SeasonNotFoundError("season cannot be less than 2024")
        df = _read_release_parquet(
            f"https://github.com/sportsdataverse/sportsdataverse-data/releases/download/espn_wnba_shots/shots_{season}.parquet"
        )
        if df is None:
            missing.append(season)
            continue
        frames.append(df)
    if missing:
        cli_warn("load_wnba_shots: no data for season(s) {missing} (skipped)".format(missing=missing))
    out = pl.concat(frames, how="vertical_relaxed") if frames else pl.DataFrame()
    return out.to_pandas(use_pyarrow_extension_array=True) if return_as_pandas else out


def load_wnba_standings(seasons, return_as_pandas: bool = False):
    """Load espn_wnba_standings (sportsdataverse-data release).

    Source: https://github.com/sportsdataverse/sportsdataverse-data/releases/tag/espn_wnba_standings

    Args:
        seasons: an int or iterable of seasons (>= 2024).
        return_as_pandas: return a pandas DataFrame instead of polars.

    Returns:
        A polars (or pandas) DataFrame; seasons with no published asset are
        skipped with a warning rather than raising (404-safe).

        |col_name                |type    |
        |:-----------------------|:-------|
        |season                  |Int32   |
        |group_id                |String  |
        |group_name              |String  |
        |group_abbreviation      |String  |
        |group_short_name        |String  |
        |team_id                 |Int32   |
        |team_uid                |String  |
        |team_slug               |String  |
        |team_location           |String  |
        |team_name               |String  |
        |team_abbreviation       |String  |
        |team_display_name       |String  |
        |team_short_display_name |String  |
        |team_color              |String  |
        |team_alternate_color    |String  |
        |team_logo               |String  |
        |stat_name               |String  |
        |stat_display_name       |String  |
        |stat_short_display_name |String  |
        |stat_description        |String  |
        |stat_abbreviation       |String  |
        |stat_type               |String  |
        |display_value           |String  |
        |value                   |Float64 |

    Example:
        Quick start::

            load_wnba_standings(seasons=2024)
    """
    frames, missing = [], []
    for season in _as_season_list(seasons):
        if int(season) < 2024:
            raise SeasonNotFoundError("season cannot be less than 2024")
        df = _read_release_parquet(
            f"https://github.com/sportsdataverse/sportsdataverse-data/releases/download/espn_wnba_standings/standings_{season}.parquet"
        )
        if df is None:
            missing.append(season)
            continue
        frames.append(df)
    if missing:
        cli_warn("load_wnba_standings: no data for season(s) {missing} (skipped)".format(missing=missing))
    out = pl.concat(frames, how="vertical_relaxed") if frames else pl.DataFrame()
    return out.to_pandas(use_pyarrow_extension_array=True) if return_as_pandas else out


def load_wnba_team_season_stats(seasons, return_as_pandas: bool = False):
    """Load espn_wnba_team_season_stats (sportsdataverse-data release).

    Source: https://github.com/sportsdataverse/sportsdataverse-data/releases/tag/espn_wnba_team_season_stats

    Args:
        seasons: an int or iterable of seasons (>= 2024).
        return_as_pandas: return a pandas DataFrame instead of polars.

    Returns:
        A polars (or pandas) DataFrame; seasons with no published asset are
        skipped with a warning rather than raising (404-safe).

        |col_name                |type    |
        |:-----------------------|:-------|
        |season                  |Int32   |
        |team_id                 |Int32   |
        |team_slug               |String  |
        |team_abbreviation       |String  |
        |team_display_name       |String  |
        |team_short_display_name |String  |
        |team_color              |String  |
        |team_alternate_color    |String  |
        |team_logo               |String  |
        |category                |String  |
        |stat_label              |String  |
        |stat_name               |String  |
        |stat_display_name       |String  |
        |stat_description        |String  |
        |display_value           |String  |
        |value                   |Float64 |

    Example:
        Quick start::

            load_wnba_team_season_stats(seasons=2024)
    """
    frames, missing = [], []
    for season in _as_season_list(seasons):
        if int(season) < 2024:
            raise SeasonNotFoundError("season cannot be less than 2024")
        df = _read_release_parquet(
            f"https://github.com/sportsdataverse/sportsdataverse-data/releases/download/espn_wnba_team_season_stats/team_season_stats_{season}.parquet"
        )
        if df is None:
            missing.append(season)
            continue
        frames.append(df)
    if missing:
        cli_warn("load_wnba_team_season_stats: no data for season(s) {missing} (skipped)".format(missing=missing))
    out = pl.concat(frames, how="vertical_relaxed") if frames else pl.DataFrame()
    return out.to_pandas(use_pyarrow_extension_array=True) if return_as_pandas else out


def load_wnba_stats_coaches(seasons, return_as_pandas: bool = False):
    """Load wnba_stats_coaches (sportsdataverse-data release).

    Source: https://github.com/sportsdataverse/sportsdataverse-data/releases/tag/wnba_stats_coaches

    Args:
        seasons: an int or iterable of seasons (>= 2026).
        return_as_pandas: return a pandas DataFrame instead of polars.

    Returns:
        A polars (or pandas) DataFrame; seasons with no published asset are
        skipped with a warning rather than raising (404-safe).

        |col_name          |type   |
        |:-----------------|:------|
        |team_id           |String |
        |season            |Int32  |
        |coach_id          |String |
        |first_name        |String |
        |last_name         |String |
        |coach_name        |String |
        |is_assistant      |String |
        |coach_type        |String |
        |sort_sequence     |String |
        |sub_sort_sequence |String |
        |season_2          |Int32  |
        |team_id_lookup    |Int32  |

    Example:
        Quick start::

            load_wnba_stats_coaches(seasons=2026)
    """
    frames, missing = [], []
    for season in _as_season_list(seasons):
        if int(season) < 2026:
            raise SeasonNotFoundError("season cannot be less than 2026")
        df = _read_release_parquet(
            f"https://github.com/sportsdataverse/sportsdataverse-data/releases/download/wnba_stats_coaches/coaches_{season}.parquet"
        )
        if df is None:
            missing.append(season)
            continue
        frames.append(df)
    if missing:
        cli_warn("load_wnba_stats_coaches: no data for season(s) {missing} (skipped)".format(missing=missing))
    out = pl.concat(frames, how="vertical_relaxed") if frames else pl.DataFrame()
    return out.to_pandas(use_pyarrow_extension_array=True) if return_as_pandas else out


def load_wnba_stats_draft(seasons, return_as_pandas: bool = False):
    """Load wnba_stats_draft (sportsdataverse-data release).

    Source: https://github.com/sportsdataverse/sportsdataverse-data/releases/tag/wnba_stats_draft

    Args:
        seasons: an int or iterable of seasons (>= 2025).
        return_as_pandas: return a pandas DataFrame instead of polars.

    Returns:
        A polars (or pandas) DataFrame; seasons with no published asset are
        skipped with a warning rather than raising (404-safe).

        |col_name            |type   |
        |:-------------------|:------|
        |person_id           |String |
        |player_name         |String |
        |season              |Int32  |
        |round_number        |String |
        |round_pick          |String |
        |overall_pick        |String |
        |draft_type          |String |
        |team_id             |String |
        |team_city           |String |
        |team_name           |String |
        |team_abbreviation   |String |
        |organization        |String |
        |organization_type   |String |
        |player_profile_flag |String |
        |season_2            |Int32  |

    Example:
        Quick start::

            load_wnba_stats_draft(seasons=2025)
    """
    frames, missing = [], []
    for season in _as_season_list(seasons):
        if int(season) < 2025:
            raise SeasonNotFoundError("season cannot be less than 2025")
        df = _read_release_parquet(
            f"https://github.com/sportsdataverse/sportsdataverse-data/releases/download/wnba_stats_draft/draft_{season}.parquet"
        )
        if df is None:
            missing.append(season)
            continue
        frames.append(df)
    if missing:
        cli_warn("load_wnba_stats_draft: no data for season(s) {missing} (skipped)".format(missing=missing))
    out = pl.concat(frames, how="vertical_relaxed") if frames else pl.DataFrame()
    return out.to_pandas(use_pyarrow_extension_array=True) if return_as_pandas else out


def load_wnba_stats_game_rosters(seasons, return_as_pandas: bool = False):
    """Load wnba_stats_game_rosters (sportsdataverse-data release).

    Source: https://github.com/sportsdataverse/sportsdataverse-data/releases/tag/wnba_stats_game_rosters

    Args:
        seasons: an int or iterable of seasons (>= 2026).
        return_as_pandas: return a pandas DataFrame instead of polars.

    Returns:
        A polars (or pandas) DataFrame; seasons with no published asset are
        skipped with a warning rather than raising (404-safe).

        |col_name          |type   |
        |:-----------------|:------|
        |player_id         |String |
        |first_name        |String |
        |last_name         |String |
        |jersey_num        |String |
        |team_id           |String |
        |team_city         |String |
        |team_name         |String |
        |team_abbreviation |String |
        |game_id           |String |
        |season            |Int32  |

    Example:
        Quick start::

            load_wnba_stats_game_rosters(seasons=2026)
    """
    frames, missing = [], []
    for season in _as_season_list(seasons):
        if int(season) < 2026:
            raise SeasonNotFoundError("season cannot be less than 2026")
        df = _read_release_parquet(
            f"https://github.com/sportsdataverse/sportsdataverse-data/releases/download/wnba_stats_game_rosters/game_rosters_{season}.parquet"
        )
        if df is None:
            missing.append(season)
            continue
        frames.append(df)
    if missing:
        cli_warn("load_wnba_stats_game_rosters: no data for season(s) {missing} (skipped)".format(missing=missing))
    out = pl.concat(frames, how="vertical_relaxed") if frames else pl.DataFrame()
    return out.to_pandas(use_pyarrow_extension_array=True) if return_as_pandas else out


def load_wnba_stats_lineups(seasons, return_as_pandas: bool = False):
    """Load wnba_stats_lineups (sportsdataverse-data release).

    Source: https://github.com/sportsdataverse/sportsdataverse-data/releases/tag/wnba_stats_lineups

    Args:
        seasons: an int or iterable of seasons (>= 2026).
        return_as_pandas: return a pandas DataFrame instead of polars.

    Returns:
        A polars (or pandas) DataFrame; seasons with no published asset are
        skipped with a warning rather than raising (404-safe).

        |col_name          |type   |
        |:-----------------|:------|
        |group_set         |String |
        |group_id          |String |
        |group_name        |String |
        |team_id           |String |
        |team_abbreviation |String |
        |gp                |String |
        |w                 |String |
        |l                 |String |
        |w_pct             |String |
        |min               |String |
        |fgm               |String |
        |fga               |String |
        |fg_pct            |String |
        |fg3m              |String |
        |fg3a              |String |
        |fg3_pct           |String |
        |ftm               |String |
        |fta               |String |
        |ft_pct            |String |
        |oreb              |String |
        |dreb              |String |
        |reb               |String |
        |ast               |String |
        |tov               |String |
        |stl               |String |
        |blk               |String |
        |blka              |String |
        |pf                |String |
        |pfd               |String |
        |pts               |String |
        |plus_minus        |String |
        |gp_rank           |String |
        |w_rank            |String |
        |l_rank            |String |
        |w_pct_rank        |String |
        |min_rank          |String |
        |fgm_rank          |String |
        |fga_rank          |String |
        |fg_pct_rank       |String |
        |fg3m_rank         |String |
        |fg3a_rank         |String |
        |fg3_pct_rank      |String |
        |ftm_rank          |String |
        |fta_rank          |String |
        |ft_pct_rank       |String |
        |oreb_rank         |String |
        |dreb_rank         |String |
        |reb_rank          |String |
        |ast_rank          |String |
        |tov_rank          |String |
        |stl_rank          |String |
        |blk_rank          |String |
        |blka_rank         |String |
        |pf_rank           |String |
        |pfd_rank          |String |
        |pts_rank          |String |
        |plus_minus_rank   |String |
        |sum_time_played   |String |
        |season            |Int32  |
        |season_type       |String |
        |measure_type      |String |
        |e_off_rating      |String |
        |off_rating        |String |
        |e_def_rating      |String |
        |def_rating        |String |
        |e_net_rating      |String |
        |net_rating        |String |
        |ast_pct           |String |
        |ast_to            |String |
        |ast_ratio         |String |
        |oreb_pct          |String |
        |dreb_pct          |String |
        |reb_pct           |String |
        |tm_tov_pct        |String |
        |efg_pct           |String |
        |ts_pct            |String |
        |e_pace            |String |
        |pace              |String |
        |pace_per40        |String |
        |poss              |String |
        |pie               |String |
        |off_rating_rank   |String |
        |def_rating_rank   |String |
        |net_rating_rank   |String |
        |ast_pct_rank      |String |
        |ast_to_rank       |String |
        |ast_ratio_rank    |String |
        |oreb_pct_rank     |String |
        |dreb_pct_rank     |String |
        |reb_pct_rank      |String |
        |tm_tov_pct_rank   |String |
        |efg_pct_rank      |String |
        |ts_pct_rank       |String |
        |pace_rank         |String |
        |pie_rank          |String |

    Example:
        Quick start::

            load_wnba_stats_lineups(seasons=2026)
    """
    frames, missing = [], []
    for season in _as_season_list(seasons):
        if int(season) < 2026:
            raise SeasonNotFoundError("season cannot be less than 2026")
        df = _read_release_parquet(
            f"https://github.com/sportsdataverse/sportsdataverse-data/releases/download/wnba_stats_lineups/lineups_{season}.parquet"
        )
        if df is None:
            missing.append(season)
            continue
        frames.append(df)
    if missing:
        cli_warn("load_wnba_stats_lineups: no data for season(s) {missing} (skipped)".format(missing=missing))
    out = pl.concat(frames, how="vertical_relaxed") if frames else pl.DataFrame()
    return out.to_pandas(use_pyarrow_extension_array=True) if return_as_pandas else out


def load_wnba_stats_officials(seasons, return_as_pandas: bool = False):
    """Load wnba_stats_officials (sportsdataverse-data release).

    Source: https://github.com/sportsdataverse/sportsdataverse-data/releases/tag/wnba_stats_officials

    Args:
        seasons: an int or iterable of seasons (>= 2026).
        return_as_pandas: return a pandas DataFrame instead of polars.

    Returns:
        A polars (or pandas) DataFrame; seasons with no published asset are
        skipped with a warning rather than raising (404-safe).

        |col_name    |type   |
        |:-----------|:------|
        |official_id |String |
        |first_name  |String |
        |last_name   |String |
        |jersey_num  |String |
        |game_id     |String |
        |season      |Int32  |

    Example:
        Quick start::

            load_wnba_stats_officials(seasons=2026)
    """
    frames, missing = [], []
    for season in _as_season_list(seasons):
        if int(season) < 2026:
            raise SeasonNotFoundError("season cannot be less than 2026")
        df = _read_release_parquet(
            f"https://github.com/sportsdataverse/sportsdataverse-data/releases/download/wnba_stats_officials/officials_{season}.parquet"
        )
        if df is None:
            missing.append(season)
            continue
        frames.append(df)
    if missing:
        cli_warn("load_wnba_stats_officials: no data for season(s) {missing} (skipped)".format(missing=missing))
    out = pl.concat(frames, how="vertical_relaxed") if frames else pl.DataFrame()
    return out.to_pandas(use_pyarrow_extension_array=True) if return_as_pandas else out


def load_wnba_stats_pbp(seasons, return_as_pandas: bool = False):
    """Load wnba_stats_pbp (sportsdataverse-data release).

    Source: https://github.com/sportsdataverse/sportsdataverse-data/releases/tag/wnba_stats_pbp

    Args:
        seasons: an int or iterable of seasons (>= 2026).
        return_as_pandas: return a pandas DataFrame instead of polars.

    Returns:
        A polars (or pandas) DataFrame; seasons with no published asset are
        skipped with a warning rather than raising (404-safe).

        |col_name                  |type    |
        |:-------------------------|:-------|
        |game_id                   |String  |
        |event_num                 |String  |
        |event_type                |String  |
        |event_action_type         |String  |
        |period                    |Int32   |
        |clock                     |String  |
        |minute_game               |Float64 |
        |time_remaining            |Float64 |
        |time_quarter              |String  |
        |minute_remaining_quarter  |Int32   |
        |seconds_remaining_quarter |Int32   |
        |action_type               |String  |
        |sub_type                  |String  |
        |neutral_description       |String  |
        |description               |String  |
        |location                  |String  |
        |score                     |String  |
        |away_score                |Int32   |
        |home_score                |Int32   |
        |score_margin              |String  |
        |person1type               |String  |
        |player1_id                |String  |
        |player1_name              |String  |
        |player1_team_id           |String  |
        |player1_team_abbreviation |String  |
        |video_available_flag      |String  |
        |team_leading              |String  |
        |x_legacy                  |Int32   |
        |y_legacy                  |Int32   |
        |shot_distance             |Int32   |
        |shot_result               |String  |
        |is_field_goal             |Int32   |
        |points_total              |Int32   |
        |shot_value                |Int32   |
        |action_number             |Int32   |
        |team_id                   |Int32   |
        |team_tricode              |String  |
        |person_id                 |Int32   |
        |player_name               |String  |
        |player_name_i             |String  |
        |score_home                |String  |
        |score_away                |String  |
        |video_available           |Int32   |
        |action_id                 |Int32   |
        |away_player1              |Int32   |
        |away_player2              |Int32   |
        |away_player3              |Int32   |
        |away_player4              |Int32   |
        |away_player5              |Int32   |
        |home_player1              |Int32   |
        |home_player2              |Int32   |
        |home_player3              |Int32   |
        |home_player4              |Int32   |
        |home_player5              |Int32   |
        |home_description          |String  |
        |player1_team_city         |String  |
        |player1_team_nickname     |String  |
        |visitor_description       |String  |
        |player2_id                |String  |
        |player2_name              |String  |
        |player2_team_id           |String  |
        |player2_team_city         |String  |
        |player2_team_nickname     |String  |
        |player2_team_abbreviation |String  |
        |player3_id                |String  |
        |player3_name              |String  |
        |player3_team_id           |String  |
        |player3_team_city         |String  |
        |player3_team_nickname     |String  |
        |player3_team_abbreviation |String  |
        |score_value               |Int32   |
        |msg_type                  |Int32   |
        |act_type                  |Int32   |
        |slug_team                 |String  |
        |shot_pts                  |Int32   |
        |secs_passed_game          |Float64 |
        |team_away                 |String  |
        |team_home                 |String  |
        |off_slug_team             |String  |
        |number_event              |Int32   |
        |possession                |Int32   |
        |total_starters_home       |Int32   |
        |total_starters_away       |Int32   |
        |garbage_time              |Int32   |
        |season                    |Int32   |

    Example:
        Quick start::

            load_wnba_stats_pbp(seasons=2026)
    """
    frames, missing = [], []
    for season in _as_season_list(seasons):
        if int(season) < 2026:
            raise SeasonNotFoundError("season cannot be less than 2026")
        df = _read_release_parquet(
            f"https://github.com/sportsdataverse/sportsdataverse-data/releases/download/wnba_stats_pbp/play_by_play_{season}.parquet"
        )
        if df is None:
            missing.append(season)
            continue
        frames.append(df)
    if missing:
        cli_warn("load_wnba_stats_pbp: no data for season(s) {missing} (skipped)".format(missing=missing))
    out = pl.concat(frames, how="vertical_relaxed") if frames else pl.DataFrame()
    return out.to_pandas(use_pyarrow_extension_array=True) if return_as_pandas else out


def load_wnba_stats_player_game_logs(seasons, return_as_pandas: bool = False):
    """Load wnba_stats_player_game_logs (sportsdataverse-data release).

    Source: https://github.com/sportsdataverse/sportsdataverse-data/releases/tag/wnba_stats_player_game_logs

    Args:
        seasons: an int or iterable of seasons (>= 2025).
        return_as_pandas: return a pandas DataFrame instead of polars.

    Returns:
        A polars (or pandas) DataFrame; seasons with no published asset are
        skipped with a warning rather than raising (404-safe).

        |col_name          |type   |
        |:-----------------|:------|
        |season_id         |String |
        |player_id         |Int32  |
        |player_name       |String |
        |team_id           |Int32  |
        |team_abbreviation |String |
        |team_name         |String |
        |game_id           |String |
        |game_date         |String |
        |matchup           |String |
        |wl                |String |
        |min               |String |
        |fgm               |String |
        |fga               |String |
        |fg_pct            |String |
        |fg3m              |String |
        |fg3a              |String |
        |fg3_pct           |String |
        |ftm               |String |
        |fta               |String |
        |ft_pct            |String |
        |oreb              |String |
        |dreb              |String |
        |reb               |String |
        |ast               |String |
        |stl               |String |
        |blk               |String |
        |tov               |String |
        |pf                |String |
        |pts               |String |
        |plus_minus        |String |
        |fantasy_pts       |String |
        |video_available   |String |
        |team_location     |String |
        |season            |Int32  |

    Example:
        Quick start::

            load_wnba_stats_player_game_logs(seasons=2025)
    """
    frames, missing = [], []
    for season in _as_season_list(seasons):
        if int(season) < 2025:
            raise SeasonNotFoundError("season cannot be less than 2025")
        df = _read_release_parquet(
            f"https://github.com/sportsdataverse/sportsdataverse-data/releases/download/wnba_stats_player_game_logs/player_game_logs_{season}.parquet"
        )
        if df is None:
            missing.append(season)
            continue
        frames.append(df)
    if missing:
        cli_warn("load_wnba_stats_player_game_logs: no data for season(s) {missing} (skipped)".format(missing=missing))
    out = pl.concat(frames, how="vertical_relaxed") if frames else pl.DataFrame()
    return out.to_pandas(use_pyarrow_extension_array=True) if return_as_pandas else out


def load_wnba_stats_player_season_stats(seasons, return_as_pandas: bool = False):
    """Load wnba_stats_player_season_stats (sportsdataverse-data release).

    Source: https://github.com/sportsdataverse/sportsdataverse-data/releases/tag/wnba_stats_player_season_stats

    Args:
        seasons: an int or iterable of seasons (>= 2026).
        return_as_pandas: return a pandas DataFrame instead of polars.

    Returns:
        A polars (or pandas) DataFrame; seasons with no published asset are
        skipped with a warning rather than raising (404-safe).

        |col_name                |type   |
        |:-----------------------|:------|
        |player_id               |String |
        |player_name             |String |
        |nickname                |String |
        |team_id                 |String |
        |team_abbreviation       |String |
        |age                     |String |
        |gp                      |String |
        |w                       |String |
        |l                       |String |
        |w_pct                   |String |
        |min                     |String |
        |fgm                     |String |
        |fga                     |String |
        |fg_pct                  |String |
        |fg3m                    |String |
        |fg3a                    |String |
        |fg3_pct                 |String |
        |ftm                     |String |
        |fta                     |String |
        |ft_pct                  |String |
        |oreb                    |String |
        |dreb                    |String |
        |reb                     |String |
        |ast                     |String |
        |tov                     |String |
        |stl                     |String |
        |blk                     |String |
        |blka                    |String |
        |pf                      |String |
        |pfd                     |String |
        |pts                     |String |
        |plus_minus              |String |
        |nba_fantasy_pts         |String |
        |dd2                     |String |
        |td3                     |String |
        |wnba_fantasy_pts        |String |
        |gp_rank                 |String |
        |w_rank                  |String |
        |l_rank                  |String |
        |w_pct_rank              |String |
        |min_rank                |String |
        |fgm_rank                |String |
        |fga_rank                |String |
        |fg_pct_rank             |String |
        |fg3m_rank               |String |
        |fg3a_rank               |String |
        |fg3_pct_rank            |String |
        |ftm_rank                |String |
        |fta_rank                |String |
        |ft_pct_rank             |String |
        |oreb_rank               |String |
        |dreb_rank               |String |
        |reb_rank                |String |
        |ast_rank                |String |
        |tov_rank                |String |
        |stl_rank                |String |
        |blk_rank                |String |
        |blka_rank               |String |
        |pf_rank                 |String |
        |pfd_rank                |String |
        |pts_rank                |String |
        |plus_minus_rank         |String |
        |nba_fantasy_pts_rank    |String |
        |dd2_rank                |String |
        |td3_rank                |String |
        |wnba_fantasy_pts_rank   |String |
        |team_count              |String |
        |season                  |Int32  |
        |season_type             |String |
        |measure_type            |String |
        |e_off_rating            |String |
        |off_rating              |String |
        |sp_work_off_rating      |String |
        |e_def_rating            |String |
        |def_rating              |String |
        |sp_work_def_rating      |String |
        |e_net_rating            |String |
        |net_rating              |String |
        |sp_work_net_rating      |String |
        |ast_pct                 |String |
        |ast_to                  |String |
        |ast_ratio               |String |
        |oreb_pct                |String |
        |dreb_pct                |String |
        |reb_pct                 |String |
        |tm_tov_pct              |String |
        |e_tov_pct               |String |
        |efg_pct                 |String |
        |ts_pct                  |String |
        |usg_pct                 |String |
        |e_usg_pct               |String |
        |e_pace                  |String |
        |pace                    |String |
        |pace_per40              |String |
        |sp_work_pace            |String |
        |pie                     |String |
        |poss                    |String |
        |fgm_pg                  |String |
        |fga_pg                  |String |
        |e_off_rating_rank       |String |
        |off_rating_rank         |String |
        |sp_work_off_rating_rank |String |
        |e_def_rating_rank       |String |
        |def_rating_rank         |String |
        |sp_work_def_rating_rank |String |
        |e_net_rating_rank       |String |
        |net_rating_rank         |String |
        |sp_work_net_rating_rank |String |
        |ast_pct_rank            |String |
        |ast_to_rank             |String |
        |ast_ratio_rank          |String |
        |oreb_pct_rank           |String |
        |dreb_pct_rank           |String |
        |reb_pct_rank            |String |
        |tm_tov_pct_rank         |String |
        |e_tov_pct_rank          |String |
        |efg_pct_rank            |String |
        |ts_pct_rank             |String |
        |usg_pct_rank            |String |
        |e_usg_pct_rank          |String |
        |e_pace_rank             |String |
        |pace_rank               |String |
        |sp_work_pace_rank       |String |
        |pie_rank                |String |
        |fgm_pg_rank             |String |
        |fga_pg_rank             |String |
        |pts_off_tov             |String |
        |pts_2nd_chance          |String |
        |pts_fb                  |String |
        |pts_paint               |String |
        |opp_pts_off_tov         |String |
        |opp_pts_2nd_chance      |String |
        |opp_pts_fb              |String |
        |opp_pts_paint           |String |
        |pts_off_tov_rank        |String |
        |pts_2nd_chance_rank     |String |
        |pts_fb_rank             |String |
        |pts_paint_rank          |String |
        |opp_pts_off_tov_rank    |String |
        |opp_pts_2nd_chance_rank |String |
        |opp_pts_fb_rank         |String |
        |opp_pts_paint_rank      |String |
        |pct_fga_2pt             |String |
        |pct_fga_3pt             |String |
        |pct_pts_2pt             |String |
        |pct_pts_2pt_mr          |String |
        |pct_pts_3pt             |String |
        |pct_pts_fb              |String |
        |pct_pts_ft              |String |
        |pct_pts_off_tov         |String |
        |pct_pts_paint           |String |
        |pct_ast_2pm             |String |
        |pct_uast_2pm            |String |
        |pct_ast_3pm             |String |
        |pct_uast_3pm            |String |
        |pct_ast_fgm             |String |
        |pct_uast_fgm            |String |
        |pct_fga_2pt_rank        |String |
        |pct_fga_3pt_rank        |String |
        |pct_pts_2pt_rank        |String |
        |pct_pts_2pt_mr_rank     |String |
        |pct_pts_3pt_rank        |String |
        |pct_pts_fb_rank         |String |
        |pct_pts_ft_rank         |String |
        |pct_pts_off_tov_rank    |String |
        |pct_pts_paint_rank      |String |
        |pct_ast_2pm_rank        |String |
        |pct_uast_2pm_rank       |String |
        |pct_ast_3pm_rank        |String |
        |pct_uast_3pm_rank       |String |
        |pct_ast_fgm_rank        |String |
        |pct_uast_fgm_rank       |String |
        |pct_fgm                 |String |
        |pct_fga                 |String |
        |pct_fg3m                |String |
        |pct_fg3a                |String |
        |pct_ftm                 |String |
        |pct_fta                 |String |
        |pct_oreb                |String |
        |pct_dreb                |String |
        |pct_reb                 |String |
        |pct_ast                 |String |
        |pct_tov                 |String |
        |pct_stl                 |String |
        |pct_blk                 |String |
        |pct_blka                |String |
        |pct_pf                  |String |
        |pct_pfd                 |String |
        |pct_pts                 |String |
        |pct_fgm_rank            |String |
        |pct_fga_rank            |String |
        |pct_fg3m_rank           |String |
        |pct_fg3a_rank           |String |
        |pct_ftm_rank            |String |
        |pct_fta_rank            |String |
        |pct_oreb_rank           |String |
        |pct_dreb_rank           |String |
        |pct_reb_rank            |String |
        |pct_ast_rank            |String |
        |pct_tov_rank            |String |
        |pct_stl_rank            |String |
        |pct_blk_rank            |String |
        |pct_blka_rank           |String |
        |pct_pf_rank             |String |
        |pct_pfd_rank            |String |
        |pct_pts_rank            |String |
        |def_ws                  |String |
        |def_ws_raw              |String |
        |def_ws_rank             |String |

    Example:
        Quick start::

            load_wnba_stats_player_season_stats(seasons=2026)
    """
    frames, missing = [], []
    for season in _as_season_list(seasons):
        if int(season) < 2026:
            raise SeasonNotFoundError("season cannot be less than 2026")
        df = _read_release_parquet(
            f"https://github.com/sportsdataverse/sportsdataverse-data/releases/download/wnba_stats_player_season_stats/player_season_stats_{season}.parquet"
        )
        if df is None:
            missing.append(season)
            continue
        frames.append(df)
    if missing:
        cli_warn(
            "load_wnba_stats_player_season_stats: no data for season(s) {missing} (skipped)".format(missing=missing)
        )
    out = pl.concat(frames, how="vertical_relaxed") if frames else pl.DataFrame()
    return out.to_pandas(use_pyarrow_extension_array=True) if return_as_pandas else out


def load_wnba_stats_rosters(seasons, return_as_pandas: bool = False):
    """Load wnba_stats_rosters (sportsdataverse-data release).

    Source: https://github.com/sportsdataverse/sportsdataverse-data/releases/tag/wnba_stats_rosters

    Args:
        seasons: an int or iterable of seasons (>= 2026).
        return_as_pandas: return a pandas DataFrame instead of polars.

    Returns:
        A polars (or pandas) DataFrame; seasons with no published asset are
        skipped with a warning rather than raising (404-safe).

        |col_name       |type   |
        |:--------------|:------|
        |team_id        |String |
        |season         |Int32  |
        |league_id      |String |
        |player         |String |
        |nickname       |String |
        |player_slug    |String |
        |num            |String |
        |position       |String |
        |height         |String |
        |weight         |String |
        |birth_date     |String |
        |age            |String |
        |exp            |String |
        |school         |String |
        |player_id      |String |
        |how_acquired   |String |
        |season_2       |Int32  |
        |team_id_lookup |Int32  |

    Example:
        Quick start::

            load_wnba_stats_rosters(seasons=2026)
    """
    frames, missing = [], []
    for season in _as_season_list(seasons):
        if int(season) < 2026:
            raise SeasonNotFoundError("season cannot be less than 2026")
        df = _read_release_parquet(
            f"https://github.com/sportsdataverse/sportsdataverse-data/releases/download/wnba_stats_rosters/rosters_{season}.parquet"
        )
        if df is None:
            missing.append(season)
            continue
        frames.append(df)
    if missing:
        cli_warn("load_wnba_stats_rosters: no data for season(s) {missing} (skipped)".format(missing=missing))
    out = pl.concat(frames, how="vertical_relaxed") if frames else pl.DataFrame()
    return out.to_pandas(use_pyarrow_extension_array=True) if return_as_pandas else out


def load_wnba_stats_schedules(seasons, return_as_pandas: bool = False):
    """Load wnba_stats_schedules (sportsdataverse-data release).

    Source: https://github.com/sportsdataverse/sportsdataverse-data/releases/tag/wnba_stats_schedules

    Args:
        seasons: an int or iterable of seasons (>= 2025).
        return_as_pandas: return a pandas DataFrame instead of polars.

    Returns:
        A polars (or pandas) DataFrame; seasons with no published asset are
        skipped with a warning rather than raising (404-safe).

        |col_name          |type   |
        |:-----------------|:------|
        |SEASON_ID         |String |
        |TEAM_ID           |String |
        |TEAM_ABBREVIATION |String |
        |TEAM_NAME         |String |
        |GAME_ID           |String |
        |GAME_DATE         |String |
        |MATCHUP           |String |
        |WL                |String |
        |MIN               |String |
        |PTS               |String |
        |FGM               |String |
        |FGA               |String |
        |FG_PCT            |String |
        |FG3M              |String |
        |FG3A              |String |
        |FG3_PCT           |String |
        |FTM               |String |
        |FTA               |String |
        |FT_PCT            |String |
        |OREB              |String |
        |DREB              |String |
        |REB               |String |
        |AST               |String |
        |STL               |String |
        |BLK               |String |
        |TOV               |String |
        |PF                |String |
        |PLUS_MINUS        |String |
        |season            |Int32  |

    Example:
        Quick start::

            load_wnba_stats_schedules(seasons=2025)
    """
    frames, missing = [], []
    for season in _as_season_list(seasons):
        if int(season) < 2025:
            raise SeasonNotFoundError("season cannot be less than 2025")
        df = _read_release_parquet(
            f"https://github.com/sportsdataverse/sportsdataverse-data/releases/download/wnba_stats_schedules/wnba_stats_schedule_{season}.parquet"
        )
        if df is None:
            missing.append(season)
            continue
        frames.append(df)
    if missing:
        cli_warn("load_wnba_stats_schedules: no data for season(s) {missing} (skipped)".format(missing=missing))
    out = pl.concat(frames, how="vertical_relaxed") if frames else pl.DataFrame()
    return out.to_pandas(use_pyarrow_extension_array=True) if return_as_pandas else out


def load_wnba_stats_shots(seasons, return_as_pandas: bool = False):
    """Load wnba_stats_shots (sportsdataverse-data release).

    Source: https://github.com/sportsdataverse/sportsdataverse-data/releases/tag/wnba_stats_shots

    Args:
        seasons: an int or iterable of seasons (>= 2026).
        return_as_pandas: return a pandas DataFrame instead of polars.

    Returns:
        A polars (or pandas) DataFrame; seasons with no published asset are
        skipped with a warning rather than raising (404-safe).

        |col_name      |type   |
        |:-------------|:------|
        |game_id       |String |
        |season        |Int32  |
        |period        |Int32  |
        |clock         |String |
        |team_id       |Int32  |
        |person_id     |Int32  |
        |action_type   |String |
        |sub_type      |String |
        |description   |String |
        |x_legacy      |Int32  |
        |y_legacy      |Int32  |
        |shot_distance |Int32  |
        |shot_value    |Int32  |
        |shot_result   |String |
        |points_total  |Int32  |

    Example:
        Quick start::

            load_wnba_stats_shots(seasons=2026)
    """
    frames, missing = [], []
    for season in _as_season_list(seasons):
        if int(season) < 2026:
            raise SeasonNotFoundError("season cannot be less than 2026")
        df = _read_release_parquet(
            f"https://github.com/sportsdataverse/sportsdataverse-data/releases/download/wnba_stats_shots/shots_{season}.parquet"
        )
        if df is None:
            missing.append(season)
            continue
        frames.append(df)
    if missing:
        cli_warn("load_wnba_stats_shots: no data for season(s) {missing} (skipped)".format(missing=missing))
    out = pl.concat(frames, how="vertical_relaxed") if frames else pl.DataFrame()
    return out.to_pandas(use_pyarrow_extension_array=True) if return_as_pandas else out


def load_wnba_stats_standings(seasons, return_as_pandas: bool = False):
    """Load wnba_stats_standings (sportsdataverse-data release).

    Source: https://github.com/sportsdataverse/sportsdataverse-data/releases/tag/wnba_stats_standings

    Args:
        seasons: an int or iterable of seasons (>= 2026).
        return_as_pandas: return a pandas DataFrame instead of polars.

    Returns:
        A polars (or pandas) DataFrame; seasons with no published asset are
        skipped with a warning rather than raising (404-safe).

        |col_name                  |type   |
        |:-------------------------|:------|
        |league_id                 |String |
        |season_id                 |String |
        |team_id                   |String |
        |team_city                 |String |
        |team_name                 |String |
        |team_slug                 |String |
        |conference                |String |
        |conference_record         |String |
        |playoff_rank              |String |
        |clinch_indicator          |String |
        |division                  |String |
        |division_record           |String |
        |division_rank             |String |
        |wins                      |String |
        |losses                    |String |
        |win_pct                   |String |
        |league_rank               |String |
        |record                    |String |
        |home                      |String |
        |road                      |String |
        |l10                       |String |
        |last10home                |String |
        |last10road                |String |
        |ot                        |String |
        |three_pts_or_less         |String |
        |ten_pts_or_more           |String |
        |long_home_streak          |String |
        |str_long_home_streak      |String |
        |long_road_streak          |String |
        |str_long_road_streak      |String |
        |long_win_streak           |String |
        |long_loss_streak          |String |
        |current_home_streak       |String |
        |str_current_home_streak   |String |
        |current_road_streak       |String |
        |str_current_road_streak   |String |
        |current_streak            |String |
        |str_current_streak        |String |
        |conference_games_back     |String |
        |division_games_back       |String |
        |clinched_conference_title |String |
        |clinched_division_title   |String |
        |clinched_playoff_birth    |String |
        |clinched_play_in          |String |
        |eliminated_conference     |String |
        |eliminated_division       |String |
        |ahead_at_half             |String |
        |behind_at_half            |String |
        |tied_at_half              |String |
        |ahead_at_third            |String |
        |behind_at_third           |String |
        |tied_at_third             |String |
        |score100pts               |String |
        |opp_score100pts           |String |
        |opp_over500               |String |
        |lead_in_fgpct             |String |
        |lead_in_reb               |String |
        |fewer_turnovers           |String |
        |points_pg                 |String |
        |opp_points_pg             |String |
        |diff_points_pg            |String |
        |vs_east                   |String |
        |vs_atlantic               |String |
        |vs_central                |String |
        |vs_southeast              |String |
        |vs_west                   |String |
        |vs_northwest              |String |
        |vs_pacific                |String |
        |vs_southwest              |String |
        |jan                       |String |
        |feb                       |String |
        |mar                       |String |
        |apr                       |String |
        |may                       |String |
        |jun                       |String |
        |jul                       |String |
        |aug                       |String |
        |sep                       |String |
        |oct                       |String |
        |nov                       |String |
        |dec                       |String |
        |score_80_plus             |String |
        |opp_score_80_plus         |String |
        |score_below_80            |String |
        |opp_score_below_80        |String |
        |total_points              |String |
        |opp_total_points          |String |
        |diff_total_points         |String |
        |league_games_back         |String |
        |playoff_seeding           |String |
        |clinched_post_season      |String |
        |neutral                   |String |
        |season                    |Int32  |

    Example:
        Quick start::

            load_wnba_stats_standings(seasons=2026)
    """
    frames, missing = [], []
    for season in _as_season_list(seasons):
        if int(season) < 2026:
            raise SeasonNotFoundError("season cannot be less than 2026")
        df = _read_release_parquet(
            f"https://github.com/sportsdataverse/sportsdataverse-data/releases/download/wnba_stats_standings/standings_{season}.parquet"
        )
        if df is None:
            missing.append(season)
            continue
        frames.append(df)
    if missing:
        cli_warn("load_wnba_stats_standings: no data for season(s) {missing} (skipped)".format(missing=missing))
    out = pl.concat(frames, how="vertical_relaxed") if frames else pl.DataFrame()
    return out.to_pandas(use_pyarrow_extension_array=True) if return_as_pandas else out


def load_wnba_stats_team_season_stats(seasons, return_as_pandas: bool = False):
    """Load wnba_stats_team_season_stats (sportsdataverse-data release).

    Source: https://github.com/sportsdataverse/sportsdataverse-data/releases/tag/wnba_stats_team_season_stats

    Args:
        seasons: an int or iterable of seasons (>= 2026).
        return_as_pandas: return a pandas DataFrame instead of polars.

    Returns:
        A polars (or pandas) DataFrame; seasons with no published asset are
        skipped with a warning rather than raising (404-safe).

        |col_name                |type   |
        |:-----------------------|:------|
        |team_id                 |String |
        |team_name               |String |
        |gp                      |String |
        |w                       |String |
        |l                       |String |
        |w_pct                   |String |
        |min                     |String |
        |fgm                     |String |
        |fga                     |String |
        |fg_pct                  |String |
        |fg3m                    |String |
        |fg3a                    |String |
        |fg3_pct                 |String |
        |ftm                     |String |
        |fta                     |String |
        |ft_pct                  |String |
        |oreb                    |String |
        |dreb                    |String |
        |reb                     |String |
        |ast                     |String |
        |tov                     |String |
        |stl                     |String |
        |blk                     |String |
        |blka                    |String |
        |pf                      |String |
        |pfd                     |String |
        |pts                     |String |
        |plus_minus              |String |
        |gp_rank                 |String |
        |w_rank                  |String |
        |l_rank                  |String |
        |w_pct_rank              |String |
        |min_rank                |String |
        |fgm_rank                |String |
        |fga_rank                |String |
        |fg_pct_rank             |String |
        |fg3m_rank               |String |
        |fg3a_rank               |String |
        |fg3_pct_rank            |String |
        |ftm_rank                |String |
        |fta_rank                |String |
        |ft_pct_rank             |String |
        |oreb_rank               |String |
        |dreb_rank               |String |
        |reb_rank                |String |
        |ast_rank                |String |
        |tov_rank                |String |
        |stl_rank                |String |
        |blk_rank                |String |
        |blka_rank               |String |
        |pf_rank                 |String |
        |pfd_rank                |String |
        |pts_rank                |String |
        |plus_minus_rank         |String |
        |season                  |Int32  |
        |season_type             |String |
        |measure_type            |String |
        |e_off_rating            |String |
        |off_rating              |String |
        |e_def_rating            |String |
        |def_rating              |String |
        |e_net_rating            |String |
        |net_rating              |String |
        |ast_pct                 |String |
        |ast_to                  |String |
        |ast_ratio               |String |
        |oreb_pct                |String |
        |dreb_pct                |String |
        |reb_pct                 |String |
        |tm_tov_pct              |String |
        |efg_pct                 |String |
        |ts_pct                  |String |
        |e_pace                  |String |
        |pace                    |String |
        |pace_per40              |String |
        |poss                    |String |
        |pie                     |String |
        |off_rating_rank         |String |
        |def_rating_rank         |String |
        |net_rating_rank         |String |
        |ast_pct_rank            |String |
        |ast_to_rank             |String |
        |ast_ratio_rank          |String |
        |oreb_pct_rank           |String |
        |dreb_pct_rank           |String |
        |reb_pct_rank            |String |
        |tm_tov_pct_rank         |String |
        |efg_pct_rank            |String |
        |ts_pct_rank             |String |
        |pace_rank               |String |
        |pie_rank                |String |
        |pts_off_tov             |String |
        |pts_2nd_chance          |String |
        |pts_fb                  |String |
        |pts_paint               |String |
        |opp_pts_off_tov         |String |
        |opp_pts_2nd_chance      |String |
        |opp_pts_fb              |String |
        |opp_pts_paint           |String |
        |pts_off_tov_rank        |String |
        |pts_2nd_chance_rank     |String |
        |pts_fb_rank             |String |
        |pts_paint_rank          |String |
        |opp_pts_off_tov_rank    |String |
        |opp_pts_2nd_chance_rank |String |
        |opp_pts_fb_rank         |String |
        |opp_pts_paint_rank      |String |
        |pct_fga_2pt             |String |
        |pct_fga_3pt             |String |
        |pct_pts_2pt             |String |
        |pct_pts_2pt_mr          |String |
        |pct_pts_3pt             |String |
        |pct_pts_fb              |String |
        |pct_pts_ft              |String |
        |pct_pts_off_tov         |String |
        |pct_pts_paint           |String |
        |pct_ast_2pm             |String |
        |pct_uast_2pm            |String |
        |pct_ast_3pm             |String |
        |pct_uast_3pm            |String |
        |pct_ast_fgm             |String |
        |pct_uast_fgm            |String |
        |pct_fga_2pt_rank        |String |
        |pct_fga_3pt_rank        |String |
        |pct_pts_2pt_rank        |String |
        |pct_pts_2pt_mr_rank     |String |
        |pct_pts_3pt_rank        |String |
        |pct_pts_fb_rank         |String |
        |pct_pts_ft_rank         |String |
        |pct_pts_off_tov_rank    |String |
        |pct_pts_paint_rank      |String |
        |pct_ast_2pm_rank        |String |
        |pct_uast_2pm_rank       |String |
        |pct_ast_3pm_rank        |String |
        |pct_uast_3pm_rank       |String |
        |pct_ast_fgm_rank        |String |
        |pct_uast_fgm_rank       |String |
        |opp_fgm                 |String |
        |opp_fga                 |String |
        |opp_fg_pct              |String |
        |opp_fg3m                |String |
        |opp_fg3a                |String |
        |opp_fg3_pct             |String |
        |opp_ftm                 |String |
        |opp_fta                 |String |
        |opp_ft_pct              |String |
        |opp_oreb                |String |
        |opp_dreb                |String |
        |opp_reb                 |String |
        |opp_ast                 |String |
        |opp_tov                 |String |
        |opp_stl                 |String |
        |opp_blk                 |String |
        |opp_blka                |String |
        |opp_pf                  |String |
        |opp_pfd                 |String |
        |opp_pts                 |String |
        |opp_fgm_rank            |String |
        |opp_fga_rank            |String |
        |opp_fg_pct_rank         |String |
        |opp_fg3m_rank           |String |
        |opp_fg3a_rank           |String |
        |opp_fg3_pct_rank        |String |
        |opp_ftm_rank            |String |
        |opp_fta_rank            |String |
        |opp_ft_pct_rank         |String |
        |opp_oreb_rank           |String |
        |opp_dreb_rank           |String |
        |opp_reb_rank            |String |
        |opp_ast_rank            |String |
        |opp_tov_rank            |String |
        |opp_stl_rank            |String |
        |opp_blk_rank            |String |
        |opp_blka_rank           |String |
        |opp_pf_rank             |String |
        |opp_pfd_rank            |String |
        |opp_pts_rank            |String |

    Example:
        Quick start::

            load_wnba_stats_team_season_stats(seasons=2026)
    """
    frames, missing = [], []
    for season in _as_season_list(seasons):
        if int(season) < 2026:
            raise SeasonNotFoundError("season cannot be less than 2026")
        df = _read_release_parquet(
            f"https://github.com/sportsdataverse/sportsdataverse-data/releases/download/wnba_stats_team_season_stats/team_season_stats_{season}.parquet"
        )
        if df is None:
            missing.append(season)
            continue
        frames.append(df)
    if missing:
        cli_warn("load_wnba_stats_team_season_stats: no data for season(s) {missing} (skipped)".format(missing=missing))
    out = pl.concat(frames, how="vertical_relaxed") if frames else pl.DataFrame()
    return out.to_pandas(use_pyarrow_extension_array=True) if return_as_pandas else out
