columns:
- description: ''
  name: player_id
  type: character
- description: ''
  name: alias_url
  type: character
- description: ''
  name: alias_subpages
  type: character
- description: ''
  name: sport_name
  type: character
- description: ''
  name: first_name
  type: character
- description: ''
  name: last_name
  type: character
- description: ''
  name: display_name
  type: character
- description: ''
  name: college
  type: character
- description: ''
  name: birth_state
  type: character
- description: ''
  name: birth_city
  type: character
- description: ''
  name: birth_country
  type: character
- description: ''
  name: birth_date
  type: character
- description: ''
  name: height
  type: integer
- description: ''
  name: display_height
  type: character
- description: ''
  name: weight
  type: integer
- description: ''
  name: status
  type: character
- description: ''
  name: active
  type: logical
- description: ''
  name: suggested_headshot
  type: character
- description: ''
  name: uniform_number
  type: character
- description: ''
  name: positions
  type: character
- description: ''
  name: team_id
  type: character
- description: ''
  name: team_team_id
  type: character
- description: ''
  name: team_display_name
  type: character
- description: ''
  name: team_full_name
  type: character
- description: ''
  name: team_alias
  type: character
- description: ''
  name: team_team_logo
  type: character
- description: ''
  name: team_team_logo_white
  type: character
- description: ''
  name: team_primary_color
  type: character
- description: ''
  name: team_secondary_color
  type: character
- description: ''
  name: draft_position
  type: character
- description: ''
  name: player_seasons
  type: character
- description: ''
  name: header_stats_passing
  type: character
- description: ''
  name: season_stats_passing
  type: character
- description: ''
  name: header_stats_rushing
  type: character
- description: ''
  name: season_stats_rushing
  type: character
- description: ''
  name: header_stats_receiving
  type: character
- description: ''
  name: season_stats_receiving
  type: character
- description: ''
  name: header_stats_defense
  type: character
- description: ''
  name: season_stats_defense
  type: character
- description: ''
  name: header_stats_kicking
  type: character
- description: ''
  name: season_stats_kicking
  type: character
- description: ''
  name: header_stats_punting
  type: character
- description: ''
  name: season_stats_punting
  type: character
- description: ''
  name: earnings
  type: character
- description: ''
  name: first_year
  type: character
- description: ''
  name: last_year
  type: integer
- description: ''
  name: injury
  type: character
kind: dataframe
schema: playbook_player
