#!/usr/bin/env python
"""Emit Quarto ``.qmd`` reference stubs for one sport (MLB) from package metadata.

This is a *tiny* analogue of the production ``tools/codegen/generate.py --docs``
pipeline. It proves the **codegen → .qmd** path: the same endpoint YAML +
live-signature metadata that drives the Docusaurus markdown reference can target
Quarto ``.qmd`` just as readily.

For each universal ESPN Site-v2 endpoint it:

1. resolves the live ``espn_mlb_<short>`` callable in ``sportsdataverse.mlb``,
2. reads its real ``inspect.signature`` and docstring summary,
3. reads the endpoint's params / parser / returns-schema from the YAML, and
4. writes ``reference/generated/<short>.qmd`` with a signature, a parameters
   table, a returns note, and an **executable example** for the handful of
   endpoints that are safe to call with no required args.

It also writes ``reference/generated/index.qmd`` listing every stub.

Usage
-----
    cd docs-quarto
    python _gen_reference.py

The output is deterministic and idempotent — re-running overwrites the stubs.
"""

from __future__ import annotations

import inspect
import pathlib
import warnings

warnings.filterwarnings("ignore")

import yaml  # noqa: E402

PREFIX = "mlb"
SPORT_LABEL = "MLB"
HERE = pathlib.Path(__file__).resolve().parent
OUT_DIR = HERE / "reference" / "generated"

# Walk up to the repo root that holds tools/codegen.
REPO_ROOT = HERE
for _ in range(5):
    if (REPO_ROOT / "tools" / "codegen" / "endpoints").exists():
        break
    REPO_ROOT = REPO_ROOT.parent

ENDPOINT_YAML = REPO_ROOT / "tools" / "codegen" / "endpoints" / "espn_site_v2.yaml"

# Endpoints we can call live with no required args → emit a real executable cell.
# (Past-dated where a date is needed, so the render is reproducible.)
EXECUTABLE = {
    "teams_site": "espn_mlb_teams_site()",
    "scoreboard": "espn_mlb_scoreboard(dates='20240615')",
    "news": "espn_mlb_news()",
    "conferences": "espn_mlb_conferences()",
}


def _summary(fn) -> str:
    doc = inspect.getdoc(fn) or ""
    first = doc.strip().splitlines()[0] if doc.strip() else ""
    # docstrings often start "espn_mlb_x - <summary>."; keep the human half.
    if " - " in first:
        first = first.split(" - ", 1)[1]
    return first or "ESPN endpoint."


def _param_table(ep: dict, fn) -> str:
    rows = []
    for kind in ("path_params", "extra_params"):
        for p in ep.get(kind, []) or []:
            required = "Y" if p.get("required") else ""
            default = p.get("default", "")
            # escape the pipe in union types (e.g. int|str) so it doesn't break
            # the markdown table column boundaries.
            ptype = str(p.get("type", "")).replace("|", "\\|")
            rows.append(f"| `{p['name']}` | `{ptype}` | `{default}` | {required} |")
    # always-present passthrough flags
    rows.append("| `return_parsed` | `bool` | `True` | |")
    rows.append("| `return_as_pandas` | `bool` | `False` | |")
    header = "| Parameter | Type | Default | Required |\n|---|---|---|:---:|\n"
    return header + "\n".join(rows)


def _returns_note(ep: dict) -> str:
    parser = ep.get("parser")
    schema = ep.get("returns_schema")
    if parser:
        note = f"**`return_parsed=True`** (default) — a tidy `polars.DataFrame` (parser: `{parser}`)"
        if schema:
            note += f"; the column schema is declared in `schemas/{schema}`"
        note += ". Pass `return_as_pandas=True` for pandas, or `return_parsed=False` for the raw JSON `Dict`."
        return note
    return "Raw JSON `Dict` (no parser registered for this endpoint)."


def main() -> int:
    import sportsdataverse.mlb as mlb  # imported here so failures are clear

    data = yaml.safe_load(ENDPOINT_YAML.read_text(encoding="utf-8"))
    endpoints = [e for e in data.get("endpoints", []) if e.get("scope") == "universal"]

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    written: list[tuple[str, str]] = []

    for ep in endpoints:
        short = ep["short"]
        fn_name = f"espn_{PREFIX}_{short}"
        fn = getattr(mlb, fn_name, None)
        if fn is None:
            continue  # YAML short doesn't resolve to a live callable for this league

        try:
            sig = str(inspect.signature(fn))
        except (TypeError, ValueError):
            sig = "(...)"

        lines = [
            "---",
            f'title: "`{fn_name}`"',
            "---",
            "",
            '::: {.callout-note appearance="simple"}',
            "Generated by [`_gen_reference.py`](../../_gen_reference.py) from endpoint "
            "YAML + live signature metadata. Do not edit by hand.",
            ":::",
            "",
            "```python",
            f"{fn_name}{sig}",
            "```",
            "",
            _summary(fn),
            "",
            f"**Endpoint path:** `{ep.get('path', '')}`  ",
            f"**Parser:** `{ep.get('parser', '—')}`",
            "",
            "## Parameters",
            "",
            _param_table(ep, fn),
            "",
            "## Returns",
            "",
            _returns_note(ep),
            "",
        ]

        if short in EXECUTABLE:
            call = EXECUTABLE[short]
            lines += [
                "## Example",
                "",
                "```{python}",
                "#| echo: true",
                "import warnings; warnings.filterwarnings('ignore')",
                f"from sportsdataverse.mlb import {fn_name}",
                f"_df = {call}",
                'print("shape:", getattr(_df, "shape", None))',
                "_df.head(5) if hasattr(_df, 'head') else _df",
                "```",
                "",
            ]

        (OUT_DIR / f"{short}.qmd").write_text("\n".join(lines), encoding="utf-8")
        written.append((short, fn_name))

    # index
    idx = [
        "---",
        f'title: "Generated {SPORT_LABEL} reference stubs"',
        "---",
        "",
        "These pages are emitted mechanically by "
        "[`_gen_reference.py`](../../_gen_reference.py) from the **same endpoint "
        "YAML** (`tools/codegen/endpoints/espn_site_v2.yaml`) that drives the "
        "production Docusaurus reference, plus each function's live "
        "`inspect.signature` and docstring. They prove the **codegen → .qmd** path.",
        "",
        f"{len(written)} {SPORT_LABEL} endpoints generated:",
        "",
        "| Endpoint | Function |",
        "|---|---|",
    ]
    for short, fn_name in written:
        idx.append(f"| `{short}` | [`{fn_name}`]({short}.qmd) |")
    idx += [
        "",
        "::: {.callout-tip}",
        "Compare these mechanical stubs with the **hand-written** "
        "[MLB reference](../mlb.qmd) — the hand-written pages add executable "
        "examples that render the real frame for *every* function, which is the "
        "literate-docs value Quarto adds over a schema table.",
        ":::",
    ]
    (OUT_DIR / "index.qmd").write_text("\n".join(idx), encoding="utf-8")

    print(f"Wrote {len(written)} stubs + index to {OUT_DIR.relative_to(HERE)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
