# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Test Python Package
on: [pull_request, workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13', '3.14']
    name: Python ${{ matrix.python-version }} tests
    steps:
    - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        # Install a specific version of uv.
        version: "0.9.26"
        enable-cache: true
        python-version: ${{ matrix.python-version }}
    - name: Set up Python
      run: uv python install
    - name: Install dependencies
      run: uv sync --locked --all-extras --dev
    - name: Run basic tests
      env:
        CI: "true"
      run: |
        uv run pytest ./tests/cfb
        uv run pytest ./tests/mbb
    - name: Build distributions
      run: uv build
